### ISSUE TITLE
Add support for database API

### ISSUE THREAD

**Issue by JulienRineau** [logspace-ai/langflow#104]
Adding support for database API such as Pinecone, Weaviate or other vector databases

**Comment by ogabrielluiz** [comment]
This is in the works. We should have a release for that soon.

**Comment by Elliot-Construct** [comment]
Exactly how long will it be? How can I help?

**Comment by TNSHuseyin** [comment]
Any update on this, @ogabrielluiz ?

**Comment by ogabrielluiz** [comment]
VectorStores are deployed you can check them out in https://huggingface.co/spaces/Logspace/LangFlow

**Comment by Elliot-Construct** [comment]
But how long till weaviate is supported?
