### ISSUE TITLE
How to connect custom LLM models provided by AWS

### ISSUE THREAD

**Issue by andriimazur93** [logspace-ai/langflow#1041]
I am trying to use AWS LLM model "titan" in langflow, is there a way how to do it?

**Comment by yamonkjd** [comment]
You can put the llm's endpoint and other parameters directly into the code of the agent node that needs to provide llm in your flow. (Langchain as is), but if you want to use it for general purposes. It is a good idea to write and use your own custom component. Just specify the output of the custom component as llm type.
