### ISSUE TITLE
Will langflow be able to support Baidu Qianfan in the future?

### ISSUE THREAD

**Issue by ygytest** [logspace-ai/langflow#1044]
Feature request
New features to support Baudu's Qianfan

Motivation
I believe that Baidu's recently launched LLM platform, Qianfan, which offers a range of APIs, will soon become widely adopted. It would be beneficial to consider incorporating features that facilitate seamless integration between Langflow and Qianfan, making it easier for developers to build applications.

**Comment by dadadadakai** [comment]
try it https://github.com/logspace-ai/langflow/pull/1045
