### ISSUE TITLE
[Feature Request] Multi-media I/O (Image, Sound, Video)

### ISSUE THREAD

**Issue by ysekiy** [logspace-ai/langflow#1054]
Hello all,

Thanks for this awesome work.

I'd like to use this with Multi-Media( Image, Sound, Video). Are there anyone working on this?
Happy to help or contribute regarding this if not.

Thanks

**Comment by yamonkjd** [comment]
I am using langchain's documentloader to use gpt4 vision.

https://python.langchain.com/docs/integrations/document_loaders/image

**Comment by yamonkjd** [comment]
Recently, I have been researching various aspects to use chainlit's multimodal function that works with Langflow, but it is not working well.

As another suggestion, it would be nice if LLaVA could be used in Langflow.
