### ISSUE TITLE
Could not find: ArceeWrapper

### ISSUE THREAD

**Issue by pandab0y** [logspace-ai/langflow#1064]
langflow  0.5.0    langchain 0.0.315

request  url:
http://localhost:3000/api/v1/all

response: 
{"detail":"Could not find: ArceeWrapper"}

exception code

in  langflow.interface.utilities.base.py

def type_to_loader_dict():
....
   self.type_dict = {
                utility_name: import_class(f"langchain.utilities.{utility_name}")
                for utility_name in utilities.__all__
            }

from  langchain      utilities.__all__    cause  error     in  langchain.utilities__init__.py

------------------------------------
 elif name == "WikipediaAPIWrapper":
        return _import_wikipedia()
    elif name == "WolframAlphaAPIWrapper":
        return _import_wolfram_alpha()
    elif name == "ZapierNLAWrapper":
        return _import_zapier()
    else:
        raise AttributeError(f"Could not find: {name}")

275  line number
-------------------------

please,  tell me  the  Appropriate version  of langchain  can  solve the  error

**Comment by ogabrielluiz** [comment]
Hey

This still hasn't been fixed in Langchain. 
We'll push a fix for this today. Sorry for the delayed response.
