### ISSUE TITLE
BUG: Chat Widget HTML not consistent with Langflow Chat client

### ISSUE THREAD

**Issue by damhack** [logspace-ai/langflow#1080]
**Describe the bug**
When using the Chat Widget WebComponent, its behaviour does not match that of the Langflow chat client.  Specifically, either the context is lost or the chain of a flow appears to be broken.

Example: the community example template for "Basic Chat with Prompt and History" works fine in the Langflow chat client but loses context after the first response when loaded via the Chat Widget WebComponent.

**Browser and Version**
All

**To Reproduce**
1. Fork "Basic Chat with Prompt and History"
2. Build the flow
3. View the Code for the Chat and copy the "Chat Widget HTML" code.
4. Paste the WebComponent code into a Web page on a server.
5. Alter the script tag to point to a local copy of the bundle.min.js (NOTE: the CDN version now requires authentication and so is broken)
6. Browse to the Web page containing the WebComponent and use the Chat Widget
7. Ask a question and wait for a response
8. Ask a follow-up question about something that appeared in the response
9. The LLM will fail to answer based on the previous response - no history/context/memory.

**Screenshots**
![Screenshot 2023-10-24 at 04 46 34](https://github.com/logspace-ai/langflow/assets/1200106/c30d5e29-46f0-47c7-b5f3-02ce2a120b3b)
![Screenshot 2023-10-24 at 04 44 36](https://github.com/logspace-ai/langflow/assets/1200106/333e81ab-967e-46dd-ac64-614a3cea0df9)

**Additional context**

**Comment by yamonkjd** [comment]
I am experiencing similar symptoms as you. This also applies when directly calling and using the endpoint provided by Langflow. Since a new session is returned every time I call it (i.e. the session is not maintained), I would like to know a way to maintain the session, and I think that would be a useful solution for web components as well.

**Comment by anovazzi1** [comment]
added a fix for this in this [pull request](https://github.com/logspace-ai/langflow-embedded-chat/pull/6), i think it's keeping state now.
