### ISSUE TITLE
[Question] How to maintain a session?

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#1087]
If we look at the return value of the API end point created by Langflow, it seems to be returning a session, but we are curious about how to maintain a session in Langflow. If we call it directly and operate it, it seems that the session is initialized each time we call it. It seems to be related to the account management taking place in Dev Brunch.

**Comment by ogabrielluiz** [comment]
Hey, @yamonkjd 

Once you have the session_id, you can pass it in the request and it should reuse the components attached to that session_id.
