### ISSUE TITLE
How to take the multiple inputs from users using the Prompt template?

### ISSUE THREAD

**Issue by Bhavana6867** [logspace-ai/langflow#1088]
We have one chatbot with prompt template. There we need to take the multiple inputs from the user to the Prompt Template component and get the response. How we can implement this?

**Comment by ogabrielluiz** [comment]
Hey @Bhavana6867 

When using the API you can pass tweaks. By passing the tweaks to the PromptTemplate component with values pointing to the field you want to fill you can achieve something close to what you are looking for. Something like `{ "PromptTemplate-kd2Df":{"my_variable": "New value"}}`

**Comment by TheBearguy** [comment]
i'm in a similar state right now. i'm using an agent to extract the fields from the prompt. Is there a better solution?
