### ISSUE TITLE
Loading a Custom Langchain tool into Langflow

### ISSUE THREAD

**Issue by KimathiNewton** [logspace-ai/langflow#1091]
How do I load a custom tool that I have created using langchain , to use it on Langflow?

**Comment by mingduan99** [comment]
1.define your own class, Inherits langflow.CustomComponent by `from langflow import CustomComponent`. Sample code can be viewed in [https://github.com/logspace-ai/langflow/tree/dev/src/backend/langflow/components/utilities](https://github.com/logspace-ai/langflow/tree/dev/src/backend/langflow/components/utilities)

2.add your custom dir to flangflow `COMPONENTS_PATH`:

> XF_COMPONENTS_PATH = str(Path(__file__).parent.parent.parent.parent / "xf_langflow/components")
> ...
> @validator("COMPONENTS_PATH", pre=True)
>     def set_components_path(cls, value):
>         ...
>         # logger.debug(f"Add xf langflow component path:{XF_COMPONENTS_PATH}")
>         # value.append(XF_COMPONENTS_PATH)
>         return value

**Comment by Newton23-nk** [comment]
Hello, Thank you, it worked. However, when I loaded the tool in langflow
Ui, when creating a flow, the agents do not show my tool in the available
input components. What should I do?
