### ISSUE TITLE
Unable to see sign in/sign uppage in my local ?

### ISSUE THREAD

**Issue by satyagofylo** [logspace-ai/langflow#1092]
I have installed Langflow in my local set up and I want to use username and password, so i followed this documentation https://docs.langflow.org/guidelines/login 

installtion method : pip install langflow
 can you help me how to run this in local with username and password?

**Comment by satyagofylo** [comment]
not sure i tried docker as well but could able to enable the login screen, not sure if i am missing anything here even

`langflow run --env-file .env this is not working, when i tried in my console to see langflow run --help 
![Uploading Screenshot 2023-10-29 at 8.30.45 PM.png…]()


`

**Comment by satyagofylo** [comment]
resolved in local

**Comment by Developer-atomic-amardeep** [comment]
> resolved in local

how man can you help me please, i am also facing the same issue
