### ISSUE TITLE
[Feature Request] Have a more user friendly UI for Langfolow

### ISSUE THREAD

**Issue by gyliu513** [logspace-ai/langflow#1094]
The current concept from Langflow sidebar is too technical and it is difficult to be understand by some customers, it will be great to introduce some more user friendly concept from the sidebar so that end user can drag-drop apps with ease.

**Comment by yamonkjd** [comment]
I think the current UI is at an appropriate level. However, I agree that it is difficult for users to understand. This will likely be improved if the Langflow document linked to each component is properly written and connected.

**Comment by yamonkjd** [comment]
![image](https://github.com/logspace-ai/langflow/assets/141118378/e9082d48-3037-4601-b5b6-de39e4789804)

It's still being sorted out, but since multimodal will be introduced in the future, our company is creating an improved UI for it. Once completed, I plan to propose it publicly.
