### ISSUE TITLE
[Feature Request] Extend API Key Access to All api/v1 Endpoints for Langflow

### ISSUE THREAD

**Issue by mrab72** [logspace-ai/langflow#1100]
**Describe the issue**
In the latest version of Langflow, they have introduced user management, allowing users to sign up and access a private dashboard. Additionally, they provide an API key that can be used to communicate with the `api/v1/process` endpoint for message processing. However, this API key is limited to the `api/v1/process` endpoint, and it doesn't work for other purposes, such as importing and exporting flows using `api/v1/flows` for POST and PATCH requests. These additional operations require a bearer token, which can only be obtained by providing a username and password. This approach is not secure, and it would be beneficial if Langflow could extend the API key's access to cover all `api/v1` endpoints, allowing it to be used for other endpoint calls.

**Steps to Reproduce**
1. Attempt to use the API key for `api/v1/process` endpoint - it works.
2. Try to use the same API key for `api/v1/flows` POST and PATCH requests - it fails.

**Comment by ogabrielluiz** [comment]
Hi, @mrab72 

Could you let me know why this approach is not secure? Only a logged-in user can change their own collection. If the user can change their flows remotely there could be unexpected consequences like a flow being updated while open.

**Comment by ogabrielluiz** [comment]
Oh, I see! 

That is a good use case, indeed.

This might not be too hard to implement. It would involve building another layer for the Dependencies to check if at least one of the credentials has been passed and get the user if the API key was provided. 

Should be pretty straightforward but requires time and effort nonetheless. I'll keep this on my radar but I'd appreciate contributions.
