### ISSUE TITLE
[Feature Request] Support for Google Palm Embeddings

### ISSUE THREAD

**Issue by AhmedBaari** [logspace-ai/langflow#1101]
Currently, we can use google palm embeddings in langchain. Here's an example code.
```python
from langchain.embeddings import GooglePalmEmbeddings
from langchain.llms import GooglePalm

llm = GooglePalm()
llm.temperature = 0.1

prompts = ["Hello there!","Welcome home"] 
llm_result = llm._generate(prompts)

print(llm_result.generations[0][0].text)
print(llm_result.generations[1][0].text)
```
Support for this can be brought in the embeddings of Lang flow to interact with Palm API.

**Comment by Sahil-Bhoite** [comment]
Issue with Google Palm Embeddings in Langchain: "NotFound: 404 Requested entity was not found"
Description:

I'm currently working on a project using Langchain with Google Palm embeddings. However, I'm encountering repeated errors where the embedding process fails with a NotFound: 404 Requested entity was not found error. The error message indicates that it is retrying, increasing the delay between attempts, but it never succeeds.

Here is a snippet of the error log:
Retrying langchain_community.embeddings.google_palm.embed_with_retry.<locals>._embed_with_retry in 2.0 seconds as it raised NotFound: 404 Requested entity was not found..
Retrying langchain_community.embeddings.google_palm.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised NotFound: 404 Requested entity was not found..
Retrying langchain_community.embeddings.google_palm.embed_with_retry.<locals>._embed_with_retry in 8.0 seconds as it raised NotFound: 404 Requested entity was not found..
Retrying langchain_community.embeddings.google_palm.embed_with_retry.<locals>._embed_with_retry in 16.0 seconds as it raised NotFound: 404 Requested entity was not found..
Retrying langchain_community.embeddings.google_palm.embed_with_retry.<locals>._embed_with_retry in 32.0 seconds as it raised NotFound: 404 Requested entity was not found..
