### ISSUE TITLE
Anthropic components don't work

### ISSUE THREAD

**Issue by damhack** [logspace-ai/langflow#1107]
**Describe the bug**
The existing Anthropic and ChatAnthropic components no longer work.

Claude-2 isn't supported and using default settings against the Anthropic API results in a Missing Type error.

**Browser and Version**
 - All browsers, latest main branch release

**To Reproduce**
1. Go to Langflow editor
2. Add ChatMessageTemplate, PromptTemplate, LLMChain and ChatAnthropic (or old Anthropic) component.
3. Wire them up with a user input variable in the prompt
4. Build the flow and run
5. Receive error:

`Error: Error code: 404 - {'error': {'type': 'not_found_error', 'message': 'Not Found'}}`

**Screenshots**

**Additional context**
The original components were implemented before the emergence of Claude-2 and may not be using the correct prompt layout or data structure.

**Comment by damhack** [comment]
I switched to using the litellm PR instead that is still awaiting review.

That is a good workaround.

**Comment by ogabrielluiz** [comment]
We don't have access to Anthropic so we can't make sure it is working. 

I'll see what I can do to update it.

About the Litellm, @ishaan-jaff, could you review the PR?

**Comment by jtoy** [comment]
this is broken for me now as well
