### ISSUE TITLE
Dark mode please

### ISSUE THREAD

**Issue by brylie** [logspace-ai/langflow#1115]
**Describe the bug**
Bright-mode-only websites are somewhat painful to read. Please support dark mode for LangFlow UI and the LangFlow documentation.

**Browser and Version**
 - Browser any
 - Version any

**To Reproduce**
1. Go to LangFlow UI or documentation
2. See excessive brightness

**Screenshots**

![image](https://github.com/logspace-ai/langflow/assets/17307/126cf1a3-b588-4dbf-a9ae-3cdf7fcb851c)

![image](https://github.com/logspace-ai/langflow/assets/17307/15c0ea96-ac99-45eb-a211-0950293742ea)

**Comment by ogabrielluiz** [comment]
Hey @brylie 

Are you referring to docs only, right?

**Comment by brylie** [comment]
I'm referring to both docs and LangFlow UI. I was able to open a pull request to enable the Docusaurus dark mode toggle for the LangFlow docs. However, I couldn't easily determine how to enable a dark mode toggle for the tailwind theme of LangFlow UI.

**Comment by rpcoelho23** [comment]
Has this been enabled in the cloud version?
