### ISSUE TITLE
Enable Langfuse integration when calling /api/v1/process

### ISSUE THREAD

**Issue by yassineselmi** [logspace-ai/langflow#1121]
Hello Team,

I noticed that the Langfuse callback is not enabled when I run the flow via the API (`/api/v1/process/<flow id>`).

Under the hood, the function [get_result_and_thought](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/processing/process.py#L64) is being called without any callback.

The fix consists of defining Langfuse callback when calling the `langchain_object` [here](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/processing/process.py#L75). It should be similar to the definition of the [get_result_and_steps](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/processing/base.py#L59-L108) function.

Before submitting a PR, I'm wondering why we have two different functions to run the flow? 
- `get_result_and_thought` used when we call the `/api/v1/process/<flow_id>` endpoint
- `get_result_and_steps` used in the chat window (via a Websocket connection)

**Comment by ogabrielluiz** [comment]
Hey @yassineselmi 

Indeed this is something we need to update.

The main reason is the callbacks as they were not needed without a WebSocket connection. With the Langfuse integration this changed.

Maybe we should find a way to faze out the `get_result_and_thought`. 

I had a PluginService in a branch to have better support for plugins like Langfuse but I don't think I merged it yet.

Anyway, feel free to open PR with this fix and later I can add the plugin service to your solution.

Thanks for the help!

**Comment by damhack** [comment]
This is problematic for people who use the Chat Widget if it doesn't get implemented.
Is there a different way of tracing to Langfuse within Components?
