### ISSUE TITLE
I want actual code after creating the flow. How can I get it ?

### ISSUE THREAD

**Issue by nileshchilka1** [logspace-ai/langflow#1124]
I want actual code after creating the flow. How can I get it ?

**Comment by yamonkjd** [comment]
Langflow does not provide full source for flow itself. However, export (Json) of the configuration is possible.

**Comment by nileshchilka1** [comment]
> Langflow does not provide full source for flow itself. However, export (Json) of the configuration is possible.

If not full source at what level I can get it if I want other than this export (Json) file.

**Comment by nileshchilka1** [comment]
If not full source at what level I can get it if I want other than this export (Json) file.
