### ISSUE TITLE
How to create an upload file field in custom components

### ISSUE THREAD

**Issue by juliussin** [logspace-ai/langflow#1129]
I would like to have an upload option as an input for my custom component. I have defined the `build_config` as follow:
```
    def build_config(self):
        return { "csv": { "file_type": "file", "file_types":["csv"], "required": True, "name": "file_path", "show": True, "suffixes": [".csv"]} }
```

but I couldn't make the upload button appear. I guess it has something to do with the `build` function parameters, but I can't find the right object for uploaded file. And what is the format of the uploaded file? Is it a path or a stringio?

```
    def build(self, csv: ???) -> Documents:
      ...
```
Thank you!

**Comment by lookoutking** [comment]
The code provided below has been tested and is functioning correctly.

```python
from langflow import CustomComponent

class FileUploadComponent(CustomComponent):
    def build(self, uploaded_file: bytes):
        with open(uploaded_file, 'r') as file:
            file_contents = file.read()
        self.repr_value = file_contents
        return file_contents

    def build_config(self):
        return {
            'uploaded_file': {
                "suffixes": ['.json'],
                'field_type': 'file',  # Specifying that this field is for file uploads
                'file_types': ['json'],  # Specifying acceptable file types
                'required': True  # Making file upload mandatory
            }
        }

```

**Comment by yamonkjd** [comment]
> The code provided below has been tested and is functioning correctly.
> 
> ```python
> from langflow import CustomComponent
> 
> class FileUploadComponent(CustomComponent):
>     def build(self, uploaded_file: bytes):
>         with open(uploaded_file, 'r') as file:
>             file_contents = file.read()
>         self.repr_value = file_contents
>         return file_contents
> 
>     def build_config(self):
>         return {
>             'uploaded_file': {
>                 "suffixes": ['.json'],
>                 'field_type': 'file', 
>                 'file_types': ['json'],
>                 'required': True
>             }
>         }
> 
> ```

you are a genius I'm surprised it's applied like this

**Comment by yamonkjd** [comment]
I use the decoration “field_type”: “file” in the buildconfig to load Langflow’s default upload widget.

**Comment by juliussin** [comment]
> The code provided below has been tested and is functioning correctly.
> 
> ```python
> from langflow import CustomComponent
> 
> class FileUploadComponent(CustomComponent):
>     def build(self, uploaded_file: bytes):
>         with open(uploaded_file, 'r') as file:
>             file_contents = file.read()
>         self.repr_value = file_contents
>         return file_contents
> 
>     def build_config(self):
>         return {
>             'uploaded_file': {
>                 "suffixes": ['.json'],
>                 'field_type': 'file', 
>                 'file_types': ['json'],
>                 'required': True
>             }
>         }
> ```

thank you! it works great! I hope in the future, it can be included in the documentation too so the others could know what kind of field types the custom components could support. Thanks!
