### ISSUE TITLE
Unable to connect to Mongo DB similar to PostgreSQL by adding the connection string in the .env file.

### ISSUE THREAD

**Issue by bhaks12** [logspace-ai/langflow#1148]
Hi,

I am able to connect to PostgreSQL database by adding the database URL in the .env file as mentioned in the **.env.example**. Langflow is not running if I try to connect to the mongo DB using the connection string. How to connect to Mongo DB similar to PostgreSQL DB?

Thanks in advance.

**Comment by prithvirajv06** [comment]
Got any workaround for this ?
