### ISSUE TITLE
langflow Insert as dependency failed

### ISSUE THREAD

**Issue by bopresslte** [logspace-ai/langflow#1168]
**Describe the bug**
Because langflow (0.5.8) depends on jina (3.15.2)
 and jina (3.15.2) depends on opentelemetry-exporter-prometheus (>=1.12.0rc1), langflow (0.5.8) requires opentelemetry-exporter-prometheus (>=1.12.0rc1).   
So, because no versions of opentelemetry-exporter-prometheus match >=1.12.0rc1
 and torchdb depends on langflow (0.5.8), version solving failed.

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
langflow = { version = "0.5.8", extras = ["local"] }

**Browser and Version**
 - Version [0.5.8]

**Comment by ogabrielluiz** [comment]
Hey, I just released version 0.5.9, could you check if this is fixed?

**Comment by bopresslte** [comment]
> Hey, I just released version 0.5.9, could you check if this is fixed?

Fixed.
