### ISSUE TITLE
Unable to call the API locally

### ISSUE THREAD

**Issue by yosse95ai** [logspace-ai/langflow#1171]
**Describe the bug**
I can now use docker-compose to launch langflow locally.
Currently, I can configure the following flow to do the build.
<img width="1440" alt="image" src="https://github.com/logspace-ai/langflow/assets/51770462/d2e0cc16-c683-4351-aeec-e459e8c0315f">

Also, we were able to absorb conversations with AI.
<img width="1440" alt="image-1" src="https://github.com/logspace-ai/langflow/assets/51770462/7d48819b-5892-4093-969a-65b5bb3692b2">

We are currently considering using this from an API rather than a GUI.
Referring to the commands shown in [the documentation](https://docs.langflow.org/guidelines/api) and GUI, I executed the following command.

```bash
curl -X POST \
  http://localhost:3000/api/v1/process/32f1077c-70dc-49c0-8006-0c64ef8b02e6 \
  -H 'Content-Type: application/json'\
  -H 'x-api-key: sk-elo0IAfBfiMQkdpOZrw_6Hgxd1Pdo2zg22mD4BhCqIk'\
  -d '{"inputs": {"input":""}, "tweaks": {
  "AmazonBedrock-1rYBo": {},
  "ConversationChain-FFwTG": {}
}}'
```

The response is as follows.

```
{"detail":"Error: One input key expected got ['repr', 'input']"}
```

**Browser and Version**
 - Browser chrome
 - Version v0.5.5

**To Reproduce**
1. Build a flow
2. Generate an API key
3. Invoke curl command

**Comment by ogabrielluiz** [comment]
Hey @yosse95ai 

Thanks for reporting this. Could I just ask you to update to the latest version? 

I'll look into it and report soon.

**Comment by yosse95ai** [comment]
Hi @ogabrielluiz 
Thank you for your answers and development.
This issue was addressed by updating to the latest version.

**Comment by ogabrielluiz** [comment]
Awesome!
