### ISSUE TITLE
[Bug] (trapped) error reading bcrypt version

### ISSUE THREAD

**Issue by Gamekiller48** [logspace-ai/langflow#1173]
**Describe the bug**
Trying to start langflow using the "python -m langflow" command after installing it in a conda environment on Windows 10 x64 results in the following error message:
![langflow](https://github.com/logspace-ai/langflow/assets/8791838/7e9e0849-77b4-4be5-9484-3b430e8c3fa6)

```
[12/04/23 17:49:31] INFO     2023-12-04 17:49:31 - INFO     - manager - Alembic not initialized           manager.py:140
INFO     2023-12-04 17:49:31 - INFO     - manager - Initializing alembic              manager.py:121
INFO     2023-12-04 17:49:31 - INFO     - manager - Alembic initialized               manager.py:126
INFO     2023-12-04 17:49:31 - INFO     - manager - Running DB migrations in          manager.py:149
C:\Users\[username]\.conda\envs\textgen\lib\site-packages\langflow\alembic
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\[username]\AppData\Roaming\Python\Python310\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
[12/04/23 17:49:32] INFO     2023-12-04 17:49:32 - INFO     - utils - No LLM cache set.                      utils.py:92
```

**Comment by ogabrielluiz** [comment]
Hey. This is a bug on passlib. I'll try to push an update on that ASAP. 

The issue is bcrypt's version has to be pinned at 4.0.1 until they fix it in passlib.

**Comment by ogabrielluiz** [comment]
Could you try version 0.5.11 to see if this is resolved?

**Comment by dharmik-anghan** [comment]
![image](https://github.com/logspace-ai/langflow/assets/108571957/c22cf2bd-4d3f-48bb-b1d2-68d964ac8946)

found error:- 
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "E:\Coding\flask-project\venv\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'

**Comment by thomasberge** [comment]
For now I forced bcrypt to 4.0.1 in my requirements.txt and pip installed it. Fixed it. Thanks @ogabrielluiz 👍 

```
bcrypt==4.0.1
passlib[bcrypt]
```

**Comment by jsimonlane** [comment]
Any updates on when this will be fixed?

**Comment by itayB** [comment]
still happens with:
```
bcrypt==4.1.2
passlib[bcrypt]==1.7.4
```

**Comment by A2Data** [comment]
是的 ，在 4.1.2 中还是会出现这个错误，回退到4.0.1 解决

**Comment by akhilesh-m-t** [comment]
Faced the same issue with 
bcrypt==4.1.3
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/user/Documents/TriLIMS/api/venv/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^

**Comment by miguelmallquidiaz** [comment]
passlib==1.7.4
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\HP\Documents\fastapi\venv\Lib\site-packages\passlib\handlers\bcrypt.py", line 620, 
in _load_backend_mixin
    version = _bcrypt.__about__.__version__       
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'

**Comment by storenth** [comment]
same using 
```
bcrypt==4.1.2
passlib[bcrypt]==1.7.4

**Comment by miguelmallquidiaz** [comment]
> mismo uso
> 
> ```
> bcrypt==4.2.0
> passlib[bcrypt]==1.7.4
> ```

use bcrypt==4.0.1 
my requirements.txt 
annotated-types==0.7.0
anyio==4.4.0
bcrypt==4.0.1
certifi==2024.7.4
click==8.1.7
colorama==0.4.6
dnspython==2.6.1
email_validator==2.2.0
fastapi==0.112.1
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
iniconfig==2.0.0
packaging==24.1
passlib==1.7.4
pluggy==1.5.0
psycopg2-binary==2.9.9
pydantic==2.8.2
pydantic_core==2.20.1
PyJWT==2.9.0
pytest==8.3.2
pytest-httpx==0.30.0
python-dotenv==1.0.1
python-multipart==0.0.9
sniffio==1.3.1
SQLAlchemy==2.0.32
starlette==0.38.2
typing_extensions==4.12.2
uvicorn==0.30.6

**Comment by ihoyosX** [comment]
Still experiencing this bug with

``
passlib = "==1.7.4"
bcrypt = "==4.2.0"
``

**Comment by Guilhermwn** [comment]
Still experiencing this bug with
```
passlib = "==1.7.4"
bcrypt = "==4.2.0"
```

**Comment by griffinbaker12** [comment]
experiencing issue as well...

**Comment by miguelmallquidiaz** [comment]
This works well for me: 
bcrypt==4.0.1
passlib==1.7.4

**Comment by Guilhermwn** [comment]
I believe the issue is that passlib is out of maintenance, and they're checking the version of bcrypt, probably something that they changed

**Comment by griffinbaker12** [comment]
> I believe the issue is that passlib is out of maintenance, and they're checking the version of bcrypt, probably something that they changed

yeah you're right. i just ended up using bare bcrypt.

**Comment by Guilhermwn** [comment]
Could you show how?

**Comment by griffinbaker12** [comment]
> Could you show how?

These helper methods cover all the functionality I need to hash and verify passwords. I then import them into my AuthService:

```python
import bcrypt

def to_bits(s):
  return s.encode('utf-8')

def to_str(b):
  return b.decode('utf-8')

def hash_pwd(pwd: str) -> str:
  salt = bcrypt.gensalt()
  return to_str(bcrypt.hashpw(to_bits(pwd), salt))

def verify_pwd(plain_pwd: str, hashed_pwd: str) -> bool:
  return bcrypt.checkpw(to_bits(plain_pwd), to_bits(hashed_pwd))
```

**Comment by kumarshivesh** [comment]
> This works well for me: bcrypt==4.0.1 passlib==1.7.4

Thanks @miguelmallquidiaz. I tried it. It is working.

**Comment by pedroboussiengui** [comment]
I'm stuck in this issue too

```bash
> pip freeze | grep -Ei 'bcrypt|passlib'
bcrypt==4.0.1
passlib==1.7.4
```

**Comment by itayB** [comment]
I found [this](https://github.com/fastapi/fastapi/discussions/11773#discussioncomment-10640267) solution from [fastapi discussion](https://github.com/fastapi/fastapi/discussions/11773):
```
import bcrypt

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

app = FastAPI()


def verify_password(plain_password, hashed_password):
    return bcrypt.checkpw(
        bytes(plain_password, encoding="utf-8"),
        bytes(hashed_password, encoding="utf-8"),
    )


def get_password_hash(password):
    return bcrypt.hashpw(
        bytes(password, encoding="utf-8"),
        bcrypt.gensalt(),
    )
```
credit to https://github.com/sinisaos for the solution
