### ISSUE TITLE
Both search tools have lost their key input setting

### ISSUE THREAD

**Issue by bent-verbiage** [logspace-ai/langflow#120]
Version 0.0.53 - both version have lost their key setting, leading to: 

> Error sending message
> Oops! Looks like you missed some required information. Please fill in all the required fields before continuing

**Comment by blackge** [comment]
I'm not sure if this is related, but using Serper search, I've put my API key in and when I run requests I don't see any requests coming through on the dashboard. Instead, I get this error:
`Error: 429 Client Error: Too Many Requests for url: ...`

**Comment by ibiscp** [comment]
Yes, there was a bug in one of the last versions, but it is fixed in [v0.0.56](https://github.com/logspace-ai/langflow/releases/tag/v0.0.56)
