### ISSUE TITLE
Is it possible to use local LLM? Can user define a custom LLM or add LLM type

### ISSUE THREAD

**Issue by LronDC** [logspace-ai/langflow#1215]
Want to ask for some practical usage examples.

**Comment by ogabrielluiz** [comment]
Hey @LronDC 

Absolutely. 
#888  has a CustomComponent example on how to approach that.

**Comment by LronDC** [comment]
> Hey @LronDC
> 
> Absolutely. #888 has a CustomComponent example on how to approach that.

Thanks a lotl.
