### ISSUE TITLE
Unable to see export JSON option

### ISSUE THREAD

**Issue by shimizust** [logspace-ai/langflow#1227]
**Describe the bug**
In the docs (https://docs.langflow.org/guidelines/features), I see there should be a button to export the current flow as a JSON file.

However, I do not see this button. I do see a 'Share' button, but it is disabled with the hover text: "Please review your API key."

Not sure what I need to do. I am able to run the flow fine, so my API key is working correctly.

**Browser and Version**
 - Browser: chrome
 - Langflow version: 0.6.2

**To Reproduce**
1. `langflow run`
2. Go to a flow
3. Don't see Export button

**Screenshots**
<img width="216" alt="image" src="https://github.com/logspace-ai/langflow/assets/119249469/0c0e0093-e0c7-4651-b779-ec59593c4e2e">
<img width="987" alt="image" src="https://github.com/logspace-ai/langflow/assets/119249469/cfd4e127-7ece-4287-823c-e01c634f91c1">

**Comment by Cristhianzl** [comment]
Hello @shimizust,

Thank you for bringing up this issue, and we appreciate your collaboration.
I've addressed the problem in hotfix #1237, and it will be available for you shortly. If you encounter any further issues or have additional feedback, please feel free to let me know.

Thank you once again for your contribution and patience.
Best regards,

**Comment by qdaoming** [comment]
@ogabrielluiz  This issue was not fixed by your commit, and the "Export" button is still not shown in latest v.0.6.3.
The button should show without any condition, as "Import" button.

**Comment by Cristhianzl** [comment]
> @ogabrielluiz This issue was not fixed by your commit, and the "Export" button is still not shown in latest v.0.6.3. The button should show without any condition, as "Import" button.

Hi @qdaoming,

Did you checked in the correct branch? This fix was introduced on "main".
Thank you.

**Comment by shimizust** [comment]
Thanks @Cristhianzl !

**Comment by qdaoming** [comment]
> > @ogabrielluiz This issue was not fixed by your commit, and the "Export" button is still not shown in latest v.0.6.3. The button should show without any condition, as "Import" button.
> 
> Hi @qdaoming,
> 
> Have you ensured that you checked out the correct branch? The fix was implemented on the "main" branch. Thank you.

Hi @Cristhianzl 
Thanks!
But this fix is integrated into v0.6.3 from its release notes at: https://github.com/logspace-ai/langflow/releases/tag/v0.6.3
So its release note is incorrect?

**Comment by ogabrielluiz** [comment]
Hey! 
The main branch is the last released version. I think that is what he was referring to.
