### ISSUE TITLE
Failed to build AgentInitializerComponent 

### ISSUE THREAD

**Issue by yassineselmi** [logspace-ai/langflow#1228]
**Describe the bug**
I'm trying to migrate an existing flow to 0.6.x  and I noticed that the new custom component `AgentInitializerComponent` fails to build, with the error:

```
AgentInitializer(ID:AgentInitializer-EoA7i): InitializeAgent.initialize() got an unexpected keyword argument 'code'
```

After a quick troubleshooting, it looks like Langflow is still trying to initialize the component in the old way as it still appear in the `CUSTOM_AGENTS` constant, [here](https://github.com/logspace-ai/langflow/blob/dev/src/backend/langflow/interface/agents/custom.py#L305).

BTW, commenting that line solved the issue, but I guess this requires more cleanup by removing all occurrences of the `AgentInitializer` (as `FrontendNode`).

**Browser and Version**
 - Browser edge
 - Version:  v0.6.0

**To Reproduce**
1. Create a flow with the component `Agent Initializer`
2. Click on 'Build'
3. See error

**Comment by DoubleLazyZ** [comment]
@yassineselmi Sorry,yassineselmi can I ask a question, if i deploy by Dockerfile, is there a temporarily way to solve this problem?

**Comment by yassineselmi** [comment]
> @yassineselmi Sorry,yassineselmi can I ask a question, if i deploy by Dockerfile, is there a temporarily way to solve this problem?

If your Dockerfile installs `langflow>=0.6.0`, this is not possible. But if you clone this repo, make the changes that I did in the PR #1229, then you can run the `deploy/docker-compose.yml` file and it should work.

**Comment by DoubleLazyZ** [comment]
@yassineselmi thank you, I waiting next version realese, Dockerfile installs langflow>=0.6.0 also has the same question.
