### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CONNECTION_STRING' from 'langchain.memory.chat_message_histories.postgres'

### ISSUE THREAD

**Issue by jxstanford** [logspace-ai/langflow#1231]
**Describe the bug**
Since release of langchain 0.0.351, langflow generates an exception on run. 

**To Reproduce**
1. Install langflow in a clean venv without langchain already installed. Will install langchain 0.0.351
2. `langflow run`
3. See error

**Additional context**
Seems like they did quite a bit of cleanup between 0.0.350 and 0.0.351. Short-term fix was to install langchain 0.0.350 manually

**Comment by DoubleLazyZ** [comment]
Temporary, I add `RUN pip install langchain==0.0.345` after `RUN pip install langflow==0.5.12 -U --user` to solve error.

**Comment by ogabrielluiz** [comment]
Hi! I think I fixed this in a pre-release version. I'll push that fix to a normal release asap. Version 0.0.350 of langchain fixes this, btw.
