### ISSUE TITLE
Can't set username for store - permission issue

### ISSUE THREAD

**Issue by jxstanford** [logspace-ai/langflow#1244]
**Describe the bug**
When registering for the store using Discord credentials (Github and Google didn't work), I see a dialogue to set my store username. When submitting, I see a permission error. 

**Browser and Version**
 - Chrome
 - 120.0.6099.109 (Official Build) (arm64)

**To Reproduce**
1. Go to lanflow.store
2. register a user
3. fill in username
4. select confirm
5. see error message (see screenshot)

**Screenshots**
<img width="905" alt="Screenshot 2023-12-22 at 1 39 58 PM" src="https://github.com/logspace-ai/langflow/assets/787382/cb7ce5c1-0ab6-4dd3-8999-1580256244a8">

**Additional context**
User was created using Discord oauth. Tried Github and Google, but neither succeeded.

**Comment by jxstanford** [comment]
Specific error: "You do not have permission to access this."
Context: I can log into the store, but am prompted to create an initial username. The error occurs when attempting to submit the username.

**Comment by ogabrielluiz** [comment]
Hi @jxstanford 

This is due to you having created an account through other means already (other than SSO).
