### ISSUE TITLE
Vector Store Toolkit Issue - not recognizing custom llm component

### ISSUE THREAD

**Issue by sampratha28** [logspace-ai/langflow#1264]
I am using a Custom LLM Component which makes a API call to my model loaded using Llama-cpp

The Vector Store Agent is working fine, but when i am trying to use Agent Intializer and passing Vector Store Toolkit and Custom LLM Component as input, I am getting the below error

Error building node VectorStoreToolkit(ID:VectorStoreToolkit-VYE95): 1 validation error for OpenAI
__root__
Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)

note:- i am not using openai model here

**Comment by ogabrielluiz** [comment]
Hi @sampratha28
What type of agent are you selecting? The openai-functions requires the openai models.

**Comment by sampratha28** [comment]
hi @ogabrielluiz , i tried zero-shot-react-description, conversational-react-desription. 
Both are giving the same error
langflow version i am using is 0.6.3
