### ISSUE TITLE
There are no components available (local)

### ISSUE THREAD

**Issue by skeletonwarrior** [logspace-ai/langflow#1346]
**Describe the bug**
I installed pip install langchain in the local environment, installed it with pip install langflow, and ran it in the local browser with langflow run. However, I don't see any componenets to choose from. Can you tell me why?

<img width="1453" alt="스크린샷 2024-01-17 오전 10 42 08" src="https://github.com/logspace-ai/langflow/assets/25784138/857c3e1a-a04f-49e7-ac1b-a7809b06868d">

**Browser and Version**
 - Browser [safari], Macbook M2 (Ventura 13.6)

**Comment by jeffhaskin** [comment]
I did the same thing and I'm having the exact same error. I was using Python version 3.9.6 to install it. I've noticed that the Python version you're on has a huge impact on how the install goes.

<img width="1485" alt="image" src="https://github.com/logspace-ai/langflow/assets/60890286/8ff70d9f-2f38-43fd-9526-fd36bc7a3d15">

**Comment by WeLoTech** [comment]
@jeffhaskin where you able to resolve the empty components error?

**Comment by tommix626** [comment]
exactly the same @jeffhaskin, have you found any solution yet?

**Comment by tommix626** [comment]
> exactly the same @jeffhaskin, have you found any solution yet?

Just an update, I tried to run the main.py in my locally cloned repository directly, instead of using the cmd line command `langflow run`, the components displayed normally. I would guess there's some conflict in the DB?
