### ISSUE TITLE
How to setting value of BACKEND_URL in langflow frontend?

### ISSUE THREAD

**Issue by nhha1602** [logspace-ai/langflow#1355]
Dear All,

I found then env variable BACKEND_URL in langflow frontend. Is it the URL for langflow frontend connec to langflow backend ? or for the GUI browser connect to langflow backend ?
One more thing, in start-nginx.sh below, I see that we will replace __BACKEND_URL__ by env variable BACKEND_URL in /etc/nginx/conf.d/default.conf file, but there is no __BACKEND_URL__ in /etc/nginx/conf.d/default.conf.

start-nginx.sh:

```
#!/bin/sh

# Replace the placeholder with the actual value
sed -i "s|__BACKEND_URL__|$BACKEND_URL|g" /etc/nginx/conf.d/default.conf


# Start nginx
exec nginx -g 'daemon off;'

```
File /etc/nginx/conf.d/default.conf:

```
server {
    gzip on;
    gzip_comp_level  2;
    gzip_min_length  1000;
    gzip_types  text/xml text/css;
    gzip_http_version 1.1;
    gzip_vary  on;
    gzip_disable "MSIE [4-6] \.";

    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }


    include /etc/nginx/extra-conf.d/*.conf;
}

```

Please advise this.
Thank you

**Comment by nhha1602** [comment]
Hi,

As the Dockerfile in langflow/src/frontend/ directory as below:

`COPY /nginx.conf /etc/nginx/conf.d/default.conf`

It means that it copy nginx.conf to the docker image and rename it to default.conf.
So, could you, please show me the example of nginx.conf, more detail please, with __BACKEND_URL__ variable ?

Thanks

**Comment by liyangwd** [comment]
@nhha1602  how do you solve at last?
