### ISSUE TITLE
Question: How to define the order of a CustomComponent input in list?

### ISSUE THREAD

**Issue by crazybullet28** [logspace-ai/langflow#1373]
I have defined a "SimpleSequentialChain" like:
<img width="1046" alt="image" src="https://github.com/logspace-ai/langflow/assets/22133749/3fb9227d-1e39-4a00-920e-6f54fd4fbae3">
which takes multiple chains as input. My question is that can I let the input list of chains have explicitly defined order, just like if you set "is_list" as True as a string field? (like the example below)
<img width="584" alt="image" src="https://github.com/logspace-ai/langflow/assets/22133749/d04959c5-6d63-425d-b961-5e1f23c1370b">

**Comment by ogabrielluiz** [comment]
Hey @crazybullet28 

How are you?

Currently, they are sorted in alphabetical order but I just pushed a commit in the dev branch to deactivate that. 

You still have to abide to Python's rules around required and optional parameters, though.
