### ISSUE TITLE
HuggingFaceHub?

### ISSUE THREAD

**Issue by knoopx** [logspace-ai/langflow#139]
Just installed and dropped HuggingFaceHub into the canvas, it asks for HF token but no way to set the model name. Is this implemented at all?

**Comment by ogabrielluiz** [comment]
Hey! I got it to "work" to have but it seemed like I was getting one word generations so I'm not sure it is working as intended. We should test it a bit more.

**Comment by ogabrielluiz** [comment]
Hey, @knoopx 
Just a heads up that we'll launch a fix to this node very soon (probably today).
