### ISSUE TITLE
Documentation: Add simple "getting started" examples

### ISSUE THREAD

**Issue by clstaudt** [logspace-ai/langflow#141]
It would be great if the documentation included a few minimal working examples to get started with.

For example, it wasn't intuitive to me how to recreate something similar to the ChatGPT web interface.

<img width="1552" alt="Screenshot 2023-04-09 at 12 40 33" src="https://user-images.githubusercontent.com/875194/230768048-78dedbec-abd6-4d25-a3c2-319ea490e0d8.png">

**Comment by notpushkin** [comment]
You can use a ConversationChain, but you won't be able to customize the prompt or use tools it seems.

With LLMChain, I've almost managed to do a simple ChatGPT-style bot. You have to add a ConversationBufferMemory, and the following PromptTemplate:

```
The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:

{history}
Human: {text}
AI:
```

This has a few flaws: you still cannot use tools, and does fairly often dream up the rest of the conversation:

<img src="https://user-images.githubusercontent.com/1298948/230779971-12b9d880-7a21-4b05-afaf-82e6a84445a9.png" width="338" />

but it might be a good starting point.

**Comment by clstaudt** [comment]
@notpushkin  Thanks for the hint. This seems to behave like ChatGPT:

<img width="1202" alt="Screenshot 2023-04-09 at 17 08 10" src="https://user-images.githubusercontent.com/875194/230780780-41070826-2647-47fc-849e-48b1457d3f17.png">

I think something like this should be included as a "Hello World" example in the documentation.

**Comment by ogabrielluiz** [comment]
This is definitely something we are lacking at the moment. We improved a lot of the code and added many simpler options to experiment with so now might be a good time for us to add these examples. 

@notpushkin the ConversationChain is essentially a LLMChain with a preconfigured prompt. 
We are looking into improving the prompt experience(mainly by adding more control to `input_variables` and such). 

In the case of the ConversationChain some improvements could be made. Keep an eye on #146.

**Comment by notpushkin** [comment]
Tangential: I was able to get tools working if I drop conversation memory:
 
<img width="985" alt="image" src="https://user-images.githubusercontent.com/1298948/231238839-0ba02c40-33d5-426f-b014-804e04f6eb57.png">

[langflow-tools-without-memory.json](https://gist.githubusercontent.com/notpushkin/e35abba5b60ef4de34082d9950cf6753/raw/ce4fec3a925d52a64a96053800f1e8e2ce2336d9/langflow-tools-without-memory.json)

Bad news: when I add any kind of memory to the mix, I get the following error:

    Error: One input key expected got ['input', 'agent_scratchpad']

My best guess is, `memory.save_context` gets both `input` and `agent_scratchpad` and doesn't know which one of these it should save as the user message. Is there a way to get it working? (perhaps this could be a good cue for me to start a separate issue haha)

**Comment by ChasLui** [comment]
I hope that a template market can be realized, and everyone can contribute to the directory, just like the marketplaces of https://github.com/FlowiseAI/Flowise

**Comment by frankjoshua** [comment]
I think a simple method to add tutorials would just create an examples folder. Then export some working code.

**Comment by notpushkin** [comment]
@frankjoshua I think that's what's going on in https://github.com/logspace-ai/langflow_examples? (e. g. [see PR](https://github.com/logspace-ai/langflow_examples/pull/2) directly above your comment)

I think this examples repo needs some more visibility though.

**Comment by ogabrielluiz** [comment]
We plan on publishing something about them really soon. We are just working on the docs first.
