### ISSUE TITLE
Github Pages Build action

### ISSUE THREAD

**Issue by chris-bateman** [logspace-ai/langflow#1426]
There appear to be two actions in use for Github pages - 

https://github.com/logspace-ai/langflow/blob/dev/.github/workflows/deploy_gh-pages.yml

Which is broken and will be fixed by #1425 

But then the built-in Github Pages function is also used - https://github.com/logspace-ai/langflow/actions/workflows/pages/pages-build-deployment

With a branch here - https://github.com/logspace-ai/langflow/tree/gh-pages

Do you know if the first action is still required?
And how did you want to handle the docs?  
I can help by updating https://github.com/logspace-ai/langflow/blob/dev/CONTRIBUTING.md with some info once the above is cleared up. :)

**Comment by ogabrielluiz** [comment]
HEy @chris-bateman ! 

[dev/.github/workflows/deploy_gh-pages.yml](https://github.com/logspace-ai/langflow/blob/dev/.github/workflows/deploy_gh-pages.yml?rgh-link-date=2024-02-11T22%3A32%3A05Z) is the one that should be working but is not. 

Can you tell why is that?

I haven't had the time to look into it yet. 

Thanks for the work you are putting out. It helps a lot!

**Comment by ogabrielluiz** [comment]
https://github.com/logspace-ai/langflow/actions/runs/7959040340

We had to do a merge on a small fix today and it failed. 

Let me know if there's anything you need from my side.

**Comment by chris-bateman** [comment]
@ogabrielluiz I take it you noticed that you didn't merge dev into main :) So yeah if dev isn't ready to go into main you can cherry pick my commits into the workflows folder.

**Comment by chris-bateman** [comment]
And that looks good now.
![image](https://github.com/logspace-ai/langflow/assets/12206103/828fc258-da34-44ae-8db5-bc7a2cd305f2)
and
![image](https://github.com/logspace-ai/langflow/assets/12206103/c1514074-8ee1-4c4c-9b11-1483f300ca7d)
