### ISSUE TITLE
Add support for llama.cpp

### ISSUE THREAD

**Issue by SumDevv** [logspace-ai/langflow#144]
add support for llama.ccp for local Ai inferencing

**Comment by ogabrielluiz** [comment]
#134 added that but we haven't released it yet because I was not able to test it yet. 
Do you think you could test it using the dev branch?

**Comment by nsvrana** [comment]
Mine behaves the same way, but it is not stuck, it just takes that long for it to execute for me.

**Comment by TaoAthe** [comment]
Which model do I use for the llamaCPP LLM?  I have tried several. Where is the documentation for using langflow?

**Comment by TaoAthe** [comment]
Sorry I have been off trying to locate a GPU that is better.  I will try the latest thank you for responding.

**Comment by berradakamal** [comment]
Does someone figured out how to run llama with langflow? I tried many approaches and I still am struggling, I have a model of llama-2-13b that I converted, build and quantized with llama.cpp. It's running well in llama (ggml-model-q4_0.gguf).
I created a models directory in root project and tried LlamaCpp and Ctransformers but I never got an response from the LLM.. 
Can someone please help me ?
