### ISSUE TITLE
Dynamic Fields.

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#1490]
Please write an example that implements a custom component using Dynamic Fields.

**Comment by yamonkjd** [comment]
@dosu-bot

The dynamic field feature is officially available for use after version 0.6.9. This feature must be used.

**Comment by yamonkjd** [comment]
@dous-bot
This is the content about dynamic fields in the patch notes for version 0.6.7.

**Comment by yamonkjd** [comment]
@dosu-bot

This is the content about dynamic fields in the patch notes for version 0.6.7.

**Comment by yamonkjd** [comment]
Hey @ogabrielluiz 

Can you explain the purpose of the newly added dynamic fields and provide an example of how to use them?

**Comment by ogabrielluiz** [comment]
Hey! 

The Dynamic Field has become something far more interesting in our next pre-release. 

For now, it serves the purpose to have automatically generated values or to ret
 Then inside the CustomComponent, you define a method:

```python
def get_new_id(self):
    return str(uuid.uuid4())

def build_config(self):
    return {"unique_id":{"value":self.get_new_id}}

```

This will create a button close to the field that when clicked, runs the method `get_new_id`.

In our next release you'll be able to do a lot more.
