### ISSUE TITLE
Error trying to install LangFlow on Win10

### ISSUE THREAD

**Issue by hgoona** [logspace-ai/langflow#164]
**Describe the bug**
Im trying to install LangFlow with pip but i get an error. Not sure what I'm missing here.. I'm a bit new to some aspects of Python.

**Browser and Version**
 - Win 10
 - VS Code - most recent version
 - pip 23.1 from C:\Python310\lib\site-packages\pip (python 3.10)
 - Python 3.10
 

**To Reproduce**
1. `pip install langflow`
2. installation fails

**Additional context**
I see a very long log in my terminal, ending with the following error info:
` [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      creating build
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\python_bindings
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Hiranga\AppData\Local\Temp\pip-build-env-zmj5gu4o\overlay\Lib\site-packages\pybind11\include -IC:\Users\Hiranga\AppData\Local\Temp\pip-build-env-zmj5gu4o\overlay\Lib\site-packages\numpy\core\include -I./hnswlib/ -IC:\Python310\include -IC:\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tp./python_bindings/bindings.cpp 
/Fobuild\temp.win-amd64-cpython-310\Release\./python_bindings/bindings.obj /EHsc /openmp /O2 /DVERSION_INFO=\\\"0.7.0\\\"
      bindings.cpp
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Failed to build llama-cpp-python hnswlib
ERROR: Could not build wheels for llama-cpp-python, hnswlib, which is required to install pyproject.toml-based projects`

**Comment by hgoona** [comment]
Update: I had to install Visual Studio Build Tools for C++ . This seems to have done the trick!

**Comment by nicolascalev** [comment]
✅ Hey everyone, I tried what you all tried and here's [the solution ](https://github.com/oobabooga/text-generation-webui/issues/1534#issuecomment-1547025834)

I tried WSL and windows, I installed the build tools and searched everywhere and nothing worked but the information in that comment did the trick.

It's tedious so react to this comment so other people can see it.
