### ISSUE TITLE
psycopg2 breaks installation because it requires the binaries

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#167]
**Describe the bug**
`psycopg2`dependency requires binaries and breaks installation or upgrades to version 0.0.56

**To Reproduce**
1. run `pip install langflow==0.0.56`

**Additional context**
stdout:
```bash
pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
```

**Comment by oliver-li** [comment]
> **Describe the bug** `psycopg2`dependency requires binaries and breaks installation or upgrades to version 0.0.56
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. run `pip install langflow==0.0.56`
> 
> **Additional context** stdout:
> 
> ```shell
> pg_config is required to build psycopg2 from source.  Please add the directory
>   containing pg_config to the $PATH or specify the full executable path with the
>   option:
> 
>       python setup.py build_ext --pg-config /path/to/pg_config build ...
> 
>   or with the pg_config option in 'setup.cfg'.
> 
>   If you prefer to avoid building psycopg2 from source, please install the PyPI
>   'psycopg2-binary' package instead.
> 
>   For further information please check the 'doc/src/install.rst' file (also at
>   <https://www.psycopg.org/docs/install.html>).
> ```

I submitted a PR last night regarding the update of psycopg2 error. I noticed that the new version changed from psycopg2 to psycopg2-binary. I resolved the installation error caused by installing psycopg2. For local deployment on Mac, you need to install 'brew install postgresql'; for Linux, you need 'pip3 install python3-psycopg2'.
