### ISSUE TITLE
ConversationChain Error One input key expected

### ISSUE THREAD

**Issue by GianfrancoCorrea** [logspace-ai/langflow#178]
`One input key expected got ['agent_scratchpad', 'input']`
**Describe the bug**
Default config for conversation chain, if I add a memory or prompts still get an error with the input key

**To Reproduce**
use: 
Chain: ConversationChain
LLM: ChatOpenIA
Agents: ZeroShotAgent

**Screenshots**
![image](https://user-images.githubusercontent.com/46355516/233693072-cfc2923b-56fd-4942-ad3d-f2894c161812.png)

**Comment by ogabrielluiz** [comment]
Hey, @GianfrancoCorrea. 

The ConversationChain does not require an Agent. You can add a LLM and a Memory and you should be good to go.

**Comment by GianfrancoCorrea** [comment]
thanks, @ogabrielluiz, maybe this needs some documentation 😅

**Comment by ogabrielluiz** [comment]
We are working on that :)

**Comment by GianfrancoCorrea** [comment]
@ogabrielluiz and how can I use tools now? like the search 
![image](https://user-images.githubusercontent.com/46355516/233794700-c4da8f85-a9ec-4ba2-9ac9-a42d53173c57.png)

**Comment by ogabrielluiz** [comment]
To use Tools you need an agent. You can use the initialize_agent node and that will give you options like the react-conversation agent then you can add tools.
