### ISSUE TITLE
Error: 'latin-1' codec can't encode characters

### ISSUE THREAD

**Issue by pleelapr** [logspace-ai/langflow#179]
**Describe the bug**
I set up a flow where I load the document and store it in Chroma Vectorstore and try to have a chat to ask for information.
However, I got this error below.
```
ValueError: Error: 'latin-1' codec can't encode characters in
position 7-57: ordinal not in range(256)
```

**Browser and Version**
 - Browser: Edge
 - Version 112.0.1722.48 (Official build) (64-bit)

**To Reproduce**
Here is my json for the flow I set up. Please change the extension to .json to import it on langflow.
[Document_vector.txt](https://github.com/logspace-ai/langflow/files/11299785/Document_vector.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/43277180/233749355-2ac67314-a5af-4536-931f-73b44e46273e.png)

**Comment by Captain-Bacon** [comment]
Came here to make the same kind of post. 

Little screenshot:
<img width="1118" alt="Screenshot 2023-04-22 at 13 22 25" src="https://user-images.githubusercontent.com/123217107/233784637-afe95c64-2384-43ec-aa0a-6a9a21601176.png">

I can't see how it's possible to add any Tool functions that would allow me to write a python code to format the html between the html grabber and the text splitter.  Tools are red, docs are green, and ne'er shall they meet.

**Comment by ogabrielluiz** [comment]
@pleelapr The issue is probably you are copying one API key from one OpenAI API key field to another field. When you copy the values you are copying the dots and not the API key itself. Could you make sure you are pasting the actual API key (maybe paste it somewhere else first to check).

**Comment by ogabrielluiz** [comment]
@Captain-Bacon could you create another issue or discussion for us to discuss that? A python function between them is not possible right now, but maybe we can think of something to solve your case.
