### ISSUE TITLE
how to config azure openai in langflow

### ISSUE THREAD

**Issue by romagedn** [logspace-ai/langflow#180]
**Describe the bug**
I am new to this. But I can't find a way to config azure open ai.

can someone tell me how to do it?

**Comment by ogabrielluiz** [comment]
According to the [Azure OpenAI docs in LangChain](https://python.langchain.com/en/latest/modules/models/llms/integrations/azure_openai_example.html?highlight=azure)

All you have to do is change a few parameters:
```shell
# Set this to `azure`
export OPENAI_API_TYPE=azure
# The API version you want to use: set this to `2022-12-01` for the released version.
export OPENAI_API_VERSION=2022-12-01
# The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource.
export OPENAI_API_BASE=https://your-resource-name.openai.azure.com
# The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource.
export OPENAI_API_KEY=<your Azure OpenAI API key>
```

**Comment by qixiaobo** [comment]
> Yes. OpenAI and Azure are the same APIs just coming from different endpoints, I think.

With some azure config. Like Azure Deployment

**Comment by qixiaobo** [comment]
I think this is the choice

**Comment by profplum700** [comment]
> According to the [Azure OpenAI docs in LangChain](https://python.langchain.com/en/latest/modules/models/llms/integrations/azure_openai_example.html?highlight=azure)
> 
> All you have to do is change a few parameters:
> 
> ```shell
> # Set this to `azure`
> export OPENAI_API_TYPE=azure
> # The API version you want to use: set this to `2022-12-01` for the released version.
> export OPENAI_API_VERSION=2022-12-01
> # The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource.
> export OPENAI_API_BASE=https://your-resource-name.openai.azure.com
> # The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource.
> export OPENAI_API_KEY=<your Azure OpenAI API key>
> ```

I tried doing this using a .env file and also using the `set` command in Windows but it didn't work. When I send a message, this message shows:

_Error: Must provide an 'engine' or deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.Ch_... (but the rest of the message is cut off.

![image](https://github.com/logspace-ai/langflow/assets/13546520/98eeb211-257a-4f37-b5a4-1740ac1f6b3c)
