### ISSUE TITLE
Unable to parse the beautiful soup output...

### ISSUE THREAD

**Issue by Captain-Bacon** [logspace-ai/langflow#181]
<img width="1118" alt="Screenshot 2023-04-22 at 13 22 25" src="https://user-images.githubusercontent.com/123217107/233794011-ca4a4f08-ba22-4021-9b97-f3b1ba8a2413.png">

In the above scenario i get the following error:
Request failed with status code 500
Error building node Chroma: 'latin-1' codec can't encode characters in position 7-57: ordinal not in range(256)

At the moment i'm simply trying to get the langchain documentation website (https://python.langchain.com/en/latest/) into the vector store and then be able to ask questions of an AI agent.

Going through it, it might be because the website is being loaded in a different way - it's a readthedocs website when i look at the pagesource.  but the Readthedocs plugini doesn't work and puts an index out of range error...

**Comment by carlorscoelho** [comment]
Hey @Captain-Bacon based on your flow, it seems that happened when a character that is not supported by the codec is encountered. Without your file, I couldn't replicate it.

However, I built my own and worked. Try like this:
![image](https://user-images.githubusercontent.com/80289056/233870452-f64fef0e-827e-4485-9714-cb43b803319f.png)

**Comment by ogabrielluiz** [comment]
I'm not sure I follow but have you tried connecting it to a Tool node? 

Generally, agents can be agents or tools so if you want the agent to be used by another agent, you should use it as a tool.
