### ISSUE TITLE
Edges being deleted incorrectly (High priority)

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#183]
**Describe the bug**
If you erase a node with backspace all edges are erased too.

**Browser and Version**
 - Browser Safari
 - Version: dev

**To Reproduce**
1. Load a complex flow
2. Erase one edge

**Comment by seshubonam** [comment]
+1 such a basic ui thing failing and wasnt fixed for a month, not complaining but that kills the hype

**Comment by ogabrielluiz** [comment]
Hey, @seshubonam. Were you using Safari when you encountered this issue?

**Comment by seshubonam** [comment]
yes safari. may be specific to safari

**Comment by ogabrielluiz** [comment]
It seems so. I'm using Arc which is Chromium and I can't reproduce the error but for some reason it does not happen in Safari either. Still testing though. 
Any more info is appreciated. 

Thanks for the feedback!

**Comment by ogabrielluiz** [comment]
We managed to reproduce it on both Arc and Safari. We'll have it fixed by the end of the day.

**Comment by seshubonam** [comment]
awesomeee

**Comment by anovazzi1** [comment]
#244
