### ISSUE TITLE
Dark Mode - "Model name" dropdown does not show the selected value

### ISSUE THREAD

**Issue by king-of-the-grackles** [logspace-ai/langflow#184]
**Describe the bug**
When running in dark mode, the "Model name" dropdown does not show the selected value when running langflow in dark mode. When the user switches to light mode, the selected value can then be seen.

**Browser and Version**
Chrome 
Version 108.0.5359.98 (Official Build) (arm64)

**To Reproduce**
1. Drag an LLM component into the workspace.
2. Select a Model Name value.
3. Switch the dark mode.
4. observe model name field.

**Screenshots**
![Screenshot 2023-04-23 at 10 25 03 PM](https://user-images.githubusercontent.com/127002642/233894000-216f692f-05e5-46d5-888f-57ad3811336b.png)

**Additional context**

**Comment by dhavall13** [comment]
Can you assign this issue to me ? I'm interested

**Comment by ogabrielluiz** [comment]
Go for it. Thanks!
