### ISSUE TITLE
Docker failing to build

### ISSUE THREAD

**Issue by RobertHH-IS** [logspace-ai/langflow#188]
**Describe the bug**
docker-compose build fails to build docker container.

**Browser and Version**

**To Reproduce**
1. In root directory type docker-compose build in terminal
2.  Get error 
 => CANCELED [3/7] RUN apt-get update && apt-get install gcc g++ curl build-essential postgresql-server-dev-all -y                                                                      
failed to solve: executor failed running [/bin/sh -c chmod +x set_proxy.sh && ./set_proxy.sh]: exit code: 127

**Additional context**

**Comment by aqueiroz** [comment]
Same issue here error:  => CANCELED [3/7] RUN apt-get update && apt-get install gcc g++ curl build-essential postgresql-server-dev-all

When trying to build  docker-compose build , also tried --no-cache

**Comment by aqueiroz** [comment]
FYI this version installs ok https://github.com/logspace-ai/langflow/archive/refs/tags/v0.0.56.zip now having other issues

**Comment by ogabrielluiz** [comment]
Could you try running `make dev build=1`?

**Comment by bobsburgers** [comment]
i tried that. i am getting this error either way. 

 > [langflow-frontend builder-client 5/6] RUN chmod +x set_proxy.sh && ./set_proxy.sh:
#0 0.527 /bin/sh: 1: ./set_proxy.sh: not found

i commented out those lines in the dockerfile. No issues yet.

**Comment by ogabrielluiz** [comment]
This `set_proxy.sh` script was created to make docker-compose change the proxy to what is needed by docker to connect both containers. Right now, we are changing manually in [package.json](https://github.com/logspace-ai/langflow/blob/dev/src/frontend/package.json), which is not ideal but seems to work better because of docker's caching. 

We could implement something better if you have any suggestions.

**Comment by bobsburgers** [comment]
if you merge my fix we can close this. The line endings were windows. 

https://github.com/logspace-ai/langflow/pull/254

far as the changing in package.json thing. i can help with that probably using checkpoints in docker and pushing it to be later? or a script you run post install to change if you need? Probably the same script. If you can outline the problem more I can probably solve it.

**Comment by oerlock** [comment]
Yes, I applied your modifications and successfully built the docker image

**Comment by ogabrielluiz** [comment]
Hey @bobsburgers, I'd love help with that, actually. That script was just a hacky way of doing it and a better solution is definitely appreciated.
