### ISSUE TITLE
CSVLoader is missing File path.

### ISSUE THREAD

**Issue by jasona7** [logspace-ai/langflow#191]
**Describe the bug**
I am wiring a solution mimicking the YouTube [video](https://www.youtube.com/watch?v=GoNJiQxKDK0)

When I submit the question, I get an error about the CSVLoader even though the workflow does not include one.

Oops! Looks like you missed some required information:
CSVLoader is missing File path.

**Browser and Version**
Microsoft Edge
Version 112.0.1722.58 (Official build) (64-bit)

**To Reproduce**
1. Wired the widgets to reproduce the Math fortified Chain in the Youtube [video](https://www.youtube.com/watch?v=GoNJiQxKDK0)
2. Submit a question and get the error even though CSVLoader tool is not included in the solution.
![langchain_issue1](https://user-images.githubusercontent.com/7661341/234246705-f3dccc33-c735-4dae-9039-47d174f4c052.jpg)

**Expected Behavior**
Render the answer in the in-line chat dialog

**Comment by ogabrielluiz** [comment]
Could you export your flow for us to import it and take a closer look?

**Comment by jasona7** [comment]
Thanks.  Closing the ticket.
