### ISSUE TITLE
Bug: LLM UI components for temperatute should be adjusted

### ISSUE THREAD

**Issue by MarkusSagen** [logspace-ai/langflow#192]
**Describe the bug**
When creating a LLM from OpenAI, the field for temperature can be increased or decreased by clicking the arrows next to the field. These currently increase/decrement by 1 each time. This should instead be 0.1 steps at a time and be restricted to the range [0.0, 1.0]

**Browser and Version**
 - Firefox, Chrome

**Screenshots**
![Screenshot 2023-04-25 at 15 34 42](https://user-images.githubusercontent.com/20767068/234294006-659177b0-1329-4bd8-9f93-e163438026b4.png)

**Comment by ogabrielluiz** [comment]
Hey, @MarkusSagen 

Sorry for the delayed response and thanks for pointing this out.

This does not apply to that field anymore so I'll close this issue.
