### ISSUE TITLE
Tutorial/demo using Codespaces

### ISSUE THREAD

**Issue by aaronsteers** [logspace-ai/langflow#196]
I am walking through the GCP-based tutorial/demo right now and I wanted to ask if you've considered a demo built on top of the Dev Container definition in this repo, which could then be opened via GitHub Codespaces (see a Meltano example [here](https://codespaces.new/meltano/meltano-codespace-ready)). If this is interesting, I may have some time to create a PR...

**Comment by ogabrielluiz** [comment]
Hey, @aaronsteers. It would run LangFlow out of the box? 

How would that work? 

I think it is a pretty good idea.

**Comment by aaronsteers** [comment]
@ogabrielluiz - yeah! That would be the idea. It might require someone larger than the default 2CPU Codespace, and maybe some adjustment if the default implementation expected GPU acceleration, but in theory, it should be workable. 

Codepaces does support docker-in-docker - which is helpful if running everything in the same container is not yet supported.

**Comment by aaronsteers** [comment]
Draft in #201:

- #201
