### ISSUE TITLE
Support Weights and Biases Prompts observability framework

### ISSUE THREAD

**Issue by damhack** [logspace-ai/langflow#197]
Add support for Weights and Biases Prompts observability framework.

I’m finding it useful for troubleshooting Langchain jobs.

Ability to specify the API KEY and some of the init dictionary items such as Project, User, Entity, Notes, etc. would be good.

**Comment by ogabrielluiz** [comment]
Hey, @damhack 

Would that require some environment setup or is it a node (langchain object) ?
