### ISSUE TITLE
Support Nvidia NeMo Guardrails

### ISSUE THREAD

**Issue by damhack** [logspace-ai/langflow#198]
Irrespective of whether LLMs can truly be aligned (as they may be running deceptive internal agents etc.), NeMo Guardrails looks like a good solution for everyday alignment.

Our current alternative is constructing case-specific Langchains and that is not sustainable in the long term.

Support for NeMo Guardrails would reduce the number of LLM requests and therefore computational and financial cost.  It would also provide a consistent language via its config to describe and maintain use case specific alignment without having to alter the Langchain structure for each instance.

A Langflow node with a setting to specify the Guardrails config file to load, plus input from an LLM output would be good.

More details at: https://github.com/NVIDIA/NeMo-Guardrails

**Comment by ogabrielluiz** [comment]
The project looks amazing and I instantly saw its potential.

Technically you could use it by importing the flow into a LangChain object and then applying the rails. 

We will keep an eye on it and once we finish the current priorities we will evaluate a way to implement it.

For now, how do you see it being implemented in LangFlow?
