### ISSUE TITLE
Llama.cpp running twice when it is run alone

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [logspace-ai/langflow#207]
siddhesh@desktop:~/Desktop$ langflow
[18:57:38] INFO     [18:57:38] - INFO - Logger set up with log      logger.py:28
                    level: 20(info)                                             
           INFO     [18:57:38] - INFO - Log file: logs/langflow.log logger.py:30
[2023-04-26 18:57:38 +0530] [38894] [INFO] Starting gunicorn 20.1.0
[2023-04-26 18:57:38 +0530] [38894] [INFO] Listening at: http://127.0.0.1:7860 (38894)
[2023-04-26 18:57:38 +0530] [38894] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-04-26 18:57:38 +0530] [38906] [INFO] Booting worker with pid: 38906
[2023-04-26 18:57:38 +0530] [38906] [INFO] Started server process [38906]
[2023-04-26 18:57:38 +0530] [38906] [INFO] Waiting for application startup.
[2023-04-26 18:57:38 +0530] [38906] [INFO] Application startup complete.
llama_model_load: loading model from '/home/siddhesh/Desktop/vicuna.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from '/home/siddhesh/Desktop/vicuna.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
llama_model_load: loading model from '/home/siddhesh/Desktop/vicuna.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 4096
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 32
llama_model_load: n_layer = 32
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 11008
llama_model_load: n_parts = 1
llama_model_load: type    = 1
llama_model_load: ggml map size = 4017.70 MB
llama_model_load: ggml ctx size =  81.25 KB
llama_model_load: mem required  = 5809.78 MB (+ 2052.00 MB per state)
llama_model_load: loading tensors from '/home/siddhesh/Desktop/vicuna.bin'
llama_model_load: model size =  4017.27 MB / num tensors = 291
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
[2023-04-26 18:59:20 +0530] [38894] [INFO] Handling signal: winch

llama_print_timings:        load time =  1667.92 ms
llama_print_timings:      sample time =    48.17 ms /   128 runs   (    0.38 ms per run)
llama_print_timings: prompt eval time =  1667.88 ms /     8 tokens (  208.48 ms per token)
llama_print_timings:        eval time = 16544.15 ms /   127 runs   (  130.27 ms per run)
llama_print_timings:       total time = 18273.72 ms

It looks like it tries to load the first time and is unsuccessful but runs the second time. This happens everytime.

**Comment by ogabrielluiz** [comment]
Interesting. I haven't been able to test it thoroughly yet. Could you elaborate? When does that happen?

**Comment by ogabrielluiz** [comment]
Interesting. I haven't been able to test it thoroughly yet. Could you elaborate? When does that happen?

**Comment by alexfilothodoros** [comment]
Hi,

I have this problem as well, just by running llama.cpp. I don't think it's a langflow issue.
