### ISSUE TITLE
Fix dockerfile

### ISSUE THREAD

**Issue by yantxs** [logspace-ai/langflow#21]
Facing error when building image.

![image](https://user-images.githubusercontent.com/34348523/225198929-31389830-3c5d-4c4e-a641-2237718a96ac.png)

Logspace repo on Docker Hub is not accessible.

**Comment by ogabrielluiz** [comment]
Yeah. I'll look into that now. 

Those Dockerfiles were being used mainly for development but things changed a bit in the last few days. 

Thanks for the heads up.

**Comment by ogabrielluiz** [comment]
With `docker compose up` in the root folder you should be able to run the development containers. 
Running it in the docker_example folder should run langflow with the latest version.

**Comment by vid** [comment]
I see this post `docker-compse up`: `frontend_1  | sh: react-scripts: not found`

**Comment by ogabrielluiz** [comment]
Hey. I made some changes on a feature branch to test this and I think I got it working.

Would you be willing to test it on your side too? The branch is called fix_frontend_dockerfile.

You should delete the node_modules folder to make sure you have a clean slate to test. 
This is an issue with npm binary and the commit I made fixes that I think.

**Comment by ogabrielluiz** [comment]
I'v added a `dev` command to the makefile which runs `make install_frontend` then builds and runs the containers.
This should create a reliable way to run a dev environment.

**Comment by ogabrielluiz** [comment]
The containers are working pretty well now with the dev command. We can open a new issue if other bugs arise. 

Thanks for the heads up, @yantxs!
