### ISSUE TITLE
export chat to external app

### ISSUE THREAD

**Issue by seshubonam** [logspace-ai/langflow#210]
currently the chatbot is enabled on the workflow within langflow 

How can interface the input output of messages with an external app? 

how can i change something in the code where the output is fed to an api instead of the chatbot on langflow. 

a feature request or im asking for a workaround

**Comment by anovazzi1** [comment]
you can export the flow, then use the export flow to run in Python see the #206

**Comment by seshubonam** [comment]
awesommmee
