### ISSUE TITLE
Can't query SQL db, can't pickle 'module' object

### ISSUE THREAD

**Issue by ATL64** [logspace-ai/langflow#212]
**Describe the bug**
Can't connect to redshift database

**Browser and Version**
 - Chrome 112

**To Reproduce**
Make the flow as in the screenshot using the SQL Database utility, and ask a question about the DB.
I get a "cannot pickle 'module' object" error.

**Screenshots**

<img width="1025" alt="Screen Shot 2023-04-27 at 7 55 05 PM" src="https://user-images.githubusercontent.com/24615574/234964665-eed8aecc-b50f-4e2d-8e9a-9c5b16ef8566.png">

**Additional context**
Found this issue in Langchain, which was fixed on their side already: https://github.com/hwchase17/langchain/issues/1721
Maybe this will be fixed if we use a more recent Langchain version in Langflow build.

**Comment by gruckion** [comment]
Can you upload your flow document so we can reproduce the error
