### ISSUE TITLE
fix deprecated imports

### ISSUE THREAD

**Issue by ngmisl** [logspace-ai/langflow#213]
/home/python/ai/langfl/.venv/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py:183: UserWarning: `VectorDBQA` is deprecated - please use `from langchain.chains import RetrievalQA`
  warnings.warn(
/home/python/ai/langfl/.venv/lib/python3.11/site-packages/langchain/chains/qa_with_sources/vector_db.py:60: UserWarning: `VectorDBQAWithSourcesChain` is deprecated - please use `from langchain.chains import RetrievalQAWithSourcesChain`
  warnings.warn(

**Comment by ogabrielluiz** [comment]
We get these straight from the `__all__` in the `__init__` file so these warnings happen just because we imported them, not because we are using them. I'm not sure how we should approach this in this case.
