### ISSUE TITLE
very silly quesiton

### ISSUE THREAD

**Issue by text2sql** [logspace-ai/langflow#221]
sorry, this is coming from a very non-technical person: when i export the model in json, how do i turn it into python notebook or script? thank you

**Comment by nsvrana** [comment]
From the docs:

```
from langflow import load_flow_from_json

flow = load_flow_from_json("path/to/flow.json")
# Now you can use it like any chain
flow("Hey, have you heard of LangFlow?")
```

**Comment by text2sql** [comment]
Thank you Nicholas :-)  On Apr 29, 2023, at 10:24 AM, Nicholas Vrana ***@***.***> wrote:﻿
From the docs:
from langflow import load_flow_from_json

flow = load_flow_from_json("path/to/flow.json")
# Now you can use it like any chain
flow("Hey, have you heard of LangFlow?")
