### ISSUE TITLE
0.63 release seems broken, can't give input to agent/tools

### ISSUE THREAD

**Issue by ATL64** [logspace-ai/langflow#225]
**Describe the bug**
Some agents and tools are missing inputs i.e. can't connect any input to them

**Browser and Version**
Chrome

**To Reproduce**
1. Both locally and the GCP deployment exhibit this problem for me
2. Drag and drop zero shot agent or any of the ones in the screenshot (I did not thoroughly check all components on the left pane, but probably more are broken too)
3.  See there is no input connection available for those boxes at all

**Screenshots**

<img width="1056" alt="Screen Shot 2023-04-30 at 11 52 56 AM" src="https://user-images.githubusercontent.com/24615574/235349372-e41999ef-6a43-4c70-8917-c0fd2ab6aef9.png">

**Comment by ngmisl** [comment]
yeah and lots of errors in terminal

**Comment by DmitryKorzhov** [comment]
Yeah, the same:(

**Comment by jellederijke** [comment]
I have the same issue running 0.0.63 on huggingface. But I did also notice this same issue on the default langflow template on huggingface, which seems to be on version 0.0.43...

**Comment by ogabrielluiz** [comment]
Please, let me know if these are still a problem.

**Comment by ATL64** [comment]
@ogabrielluiz The other issue shows up now, the one with langchain.base_language due to 0.154 langchain version. Can't start the app

**Comment by ogabrielluiz** [comment]
@ATL64 Could you check if you have version 0.0.65? It worked here.

**Comment by ATL64** [comment]
I uninstalled langchain and langflow and reinstalled and now the issue with the nodes as in the screenshot is resolved (simply doing pip upgrade was giving me troubles now for some reason).  However, the chat doesn't work, and I'm getting other stuff in terminal like "WARNING:  Invalid HTTP request received.".  Don't have time to do the bug report now, but if nobody does I will open new issue tomorrow. This one we can close I think. Thanks :)

**Comment by ogabrielluiz** [comment]
Thanks, @ATL64. I'll test it some more here.
