### ISSUE TITLE
Cannot import name 'BaseLanguageModel' from 'langchain.schema'

### ISSUE THREAD

**Issue by ernestp** [logspace-ai/langflow#226]
**Describe the bug**

**Browser and Version**
 - N/A
 - macOS 13.3.1 (22E261)

**To Reproduce**
1. Install miniconda with Python 3.10.10
2. Install langflow
3. Run langflow
4. See error:
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (/Users/user/miniconda3/lib/python3.10/site-packages/langchain/schema.py)

**Comment by ernestp** [comment]
% langflow             
Traceback (most recent call last):
  File "/Users/user/miniconda3/bin/langflow", line 5, in <module>
    from langflow.__main__ import main
  File "/Users/user/miniconda3/lib/python3.10/site-packages/langflow/__init__.py", line 1, in <module>
    from langflow.interface.loading import load_flow_from_json
  File "/Users/user/miniconda3/lib/python3.10/site-packages/langflow/interface/loading.py", line 21, in <module>
    from langflow.interface.agents.custom import CUSTOM_AGENTS
  File "/Users/user/miniconda3/lib/python3.10/site-packages/langflow/interface/agents/__init__.py", line 1, in <module>
    from langflow.interface.agents.base import AgentCreator
  File "/Users/user/miniconda3/lib/python3.10/site-packages/langflow/interface/agents/base.py", line 6, in <module>
    from langflow.interface.agents.custom import CUSTOM_AGENTS
  File "/Users/user/miniconda3/lib/python3.10/site-packages/langflow/interface/agents/custom.py", line 31, in <module>
    from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (/Users/user/miniconda3/lib/python3.10/site-packages/langchain/schema.py)

**Comment by LiangGou** [comment]
Same error here. 
Checked the latest langchain API, and it does not have this "BaseLanguageModel" class. https://github.com/hwchase17/langchain/blob/master/langchain/schema.py

**Comment by pixelkaiser** [comment]
langchain-0.0.154 broke this. Run

`pip install langchain==0.0.153`

to pin the old version.

**Comment by nivasbasker** [comment]
faced the same issue, downgrading to `0.0.153` helped
`install langchain==0.0.153`

**Comment by ogabrielluiz** [comment]
I'll push a hotfix very soon

**Comment by ernestp** [comment]
confirming fix

**Comment by charanhu** [comment]
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
colorama==0.4.6
dataclasses-json==0.5.7
frozenlist==1.3.3
gpt-index==0.6.0
greenlet==2.0.2
idna==3.4
langchain==0.0.165
llama-index==0.6.5
marshmallow==3.19.0
marshmallow-enum==1.5.1
multidict==6.0.4
mypy-extensions==1.0.0
numexpr==2.8.4
numpy==1.24.3
openai==0.27.6
openapi-schema-pydantic==1.2.4
packaging==23.1
pandas==2.0.1
pydantic==1.10.7
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.29.0
six==1.16.0
SQLAlchemy==2.0.13
tenacity==8.2.2
tiktoken==0.4.0
tqdm==4.65.0
typing-inspect==0.8.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==1.26.15
yarl==1.9.2
