### ISSUE TITLE
How can i add SupabaseVectorStore in LangFlow

### ISSUE THREAD

**Issue by YoungGoofy** [logspace-ai/langflow#227]
I'm currently reading LangFlow code, but I still can't figure out where the implementation of chains, agents, llms, and so on takes place. 
So I want to know here how you can add your components (in this case SupabaseVectorStore). Thanks in advance.

**Comment by ogabrielluiz** [comment]
Hey, @YoungGoofy.

You can add it to the [config.yml](https://github.com/logspace-ai/langflow/blob/5ebf71116d70e796820bde5233a47974cd975223/src/backend/langflow/config.yaml) and then test it in a flow.

If it does not work, then you should find the code for that in src/backend/langflow/interface/vector_store.

The most important part of adding new components is to test them.
