### ISSUE TITLE
Tool nodes are not loaded correctly.

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#228]
**Describe the bug**
When importing a flow the Tool node's fields name and description are not loaded correctly.

**Browser and Version**
 - Arc

**To Reproduce**
1. Import a flow that has tool nodes.

**Additional context**
The flow I used:
https://github.com/logspace-ai/langflow_examples/pull/4/commits/61ee9126df8b5562ab646a5b7ad65e87b59671b4

**Comment by ogabrielluiz** [comment]
Not just nodes.
If I import a flow and reload the page all the text fields are erased. You can test that using the vectorstore agent example.

This happens to any field that has text, it seems (e.g name, description, file_path)

**Comment by ATL64** [comment]
Database URI, passwords for LLMs are also not loading for me.  Just installed 0.68 and issue still there.
