### ISSUE TITLE
No module named langflow

### ISSUE THREAD

**Issue by anishthite** [logspace-ai/langflow#23]
Hi!

I can install via pip, but cannot run `python -m langflow`

Pip output: 
```
Requirement already satisfied: langflow in /Users/anishthite/miniconda3/lib/python3.9/site-packages (0.0.32)
```

python -m langflow output:
```
/Users/anishthite/miniconda3/bin/python: No module named langflow
```

**Comment by rodrigosnader** [comment]
After installing, have you tried just `langflow`?

**Comment by rodrigosnader** [comment]
Confirmed that `python -m langflow` should not work anymore. We modified it to work with just: `langflow`.

**Comment by ibiscp** [comment]
Closing this issue for now, if necessary, please reopen it.

**Comment by ibiscp** [comment]
Try the following steps and let me know the output:

```
deactivate
python -m venv .langflow
source .langflow/bin/activate
pip install langflow
langflow
```

**Comment by anishthite** [comment]
Same issue

**Comment by rodrigosnader** [comment]
Maybe create a new conda env?

```
conda create -n langflow python=3.9
conda deactivate
conda activate langflow
pip install langflow
langflow
```
