### ISSUE TITLE
pip install: incompatible architecture for hnswlib (x86_64 instead of arm64)

### ISSUE THREAD

**Issue by clstaudt** [logspace-ai/langflow#242]
**Describe the bug**

Installation with pip on an ARM macOS system results in an error:

```
Error building node Chroma: dlopen(/Users/cls/miniforge3/envs/trIAge/lib/python3.10/site-packages/hnswlib.cpython-310-darwin.so, 0x0002): tried: '/Users/cls/miniforge3/envs/trIAge/lib/python3.10/site-packages/hnswlib.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/cls/miniforge3/envs/trIAge/lib/python3.10/site-packages/hnswlib.cpython-310-darwin.so' (no such file), '/Users/cls/miniforge3/envs/trIAge/lib/python3.10/site-packages/hnswlib.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Browser and Version**
 - Browser: Safari

**To Reproduce**

1. Install on ARM-based macOS
2. Click on "Import"
3. Load example "Vectorstore-agent"
4. Try sending a chat message to the agent

**Comment by ogabrielluiz** [comment]
This is strange. I use an M1 Pro for development and I haven't found this problem in quite a while.

Did you run `pip install langflow -U`?

**Comment by ogabrielluiz** [comment]
This works on my laptop (M1 Pro). Do you still encounter this issue?

**Comment by clstaudt** [comment]
I can't reproduce the issue anymore. There have been some UI changes. Trying to run the Vector Store Agent example project, I see a progress indicator but no log messages anywhere.
