### ISSUE TITLE
pip install langfow in local error

### ISSUE THREAD

**Issue by yayawawo** [logspace-ai/langflow#249]
**Describe the bug**
Looks like incompatible in pip install langflow, dependency to networkx have a confict between gruut2.2.3 and langflow 0.068

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langflow 0.0.68 requires networkx<4.0,>=3.1, but you have networkx 2.8.8 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gruut 2.2.3 requires networkx<3.0.0,>=2.5.0, but you have networkx 3.1 which is incompatible.

**Browser and Version**
Windows 11
Python 3.10.9/miniconda3

**Comment by ogabrielluiz** [comment]
Hey, @yayawawo.

networkx is a dependency of the ConversationKGMemory so we might be able to change the version if it doesn't conflict with LangChain's. We'll look into it. 

Thanks for the heads up.
