### ISSUE TITLE
Is it possible to run langflow on windows platform?

### ISSUE THREAD

**Issue by shadowlinyf** [logspace-ai/langflow#25]
I got this error ModuleNotFoundError: No module named 'fcntl'

**Comment by ogabrielluiz** [comment]
It should be. I'll run some tests over here.

**Comment by ogabrielluiz** [comment]
This might be related to Gunicorn. I think I tested it mostly on WSL. I’ll run some more tests today.


Gabriel Luiz Freitas Almeida

**Comment by Sameedahmad** [comment]
It's not working for me too on windows, Got the following error:
`File "c: backend \
run ( )
typer.
File "c: backend \
from server import Langf10WAppIication
maxn_ • line 51,
main line 45, •
File "c: backend Xserver.py", line I, •
from gunicorn.app.base import BaseApp1ication type: ignore
Pile "c: line 11, in
from gunicorn import util
pile "c: line 8, in
import fcntl
uleNot FoundError :
No module named`

**Comment by ogabrielluiz** [comment]
Our release should have the fix for this.

**Comment by Sameedahmad** [comment]
So it would be fixed now.

**Comment by shadowlinyf** [comment]
> 

Great,will try again.Thank you

**Comment by largeorbitalobject** [comment]
I am having the same issue ModuleNotFoundError: No module named 'fcntl' with langflow 0.33

**Comment by shadowlinyf** [comment]
Afte test It seems 0.33 still has the same problem.

**Comment by ogabrielluiz** [comment]
Our next release will have this fix. It should happen in the next hours.

**Comment by ogabrielluiz** [comment]
Our next release will have this fix. It should happen in the next hours.

**Comment by xhiroga** [comment]
FYI: I use langflow on Windows, through Anaconda.

**Comment by ogabrielluiz** [comment]
Version 0.0.40 should work on Windows
