### ISSUE TITLE
Local docker dev env wont connect "Could not proxy request /all from"

### ISSUE THREAD

**Issue by bobsburgers** [logspace-ai/langflow#256]
**Describe the bug**
If you can point me in the right direction or some trouble shooting steps I am happy to keep working on the issue. I am reaching out cause I feel like I am missing something dumb. 

I understand it might have something to do with set_proxy.sh. so maybe idk what I should change package.json to?

I have tried changing the backend url in the package.json to localhost, backend and 127.0.0.1 as well as the one in the log which is its local docker network ip. 

Proxy error: Could not proxy request /all from localhost:3000 to http://172.24.0.3:7860.
2023-05-06T01:30:01.133840400Z See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
2023-05-06T01:30:01.133854900Z 
2023-05-06T01:33:15.013844800Z Proxy error: Could not proxy request /all from 127.0.0.1:3000 to http://172.24.0.3:7860.
2023-05-06T01:33:15.013930700Z See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Browser and Version**
 - Browser Firefox
 - Version 112.0.2

**To Reproduce**
download the pack. 
run the docker compose or make dev build=1

**Comment by ogabrielluiz** [comment]
Hey, @bobsburgers
This is due to the proxy in package.json file. Change it to `http://backend:7860` and it should work.

**Comment by developerisnow** [comment]
> Hey, @bobsburgers This is due to the proxy in package.json file. Change it to `http://backend:7860` and it should work.

doesn't work and gives another problem https://github.com/logspace-ai/langflow/issues/275#issuecomment-1543329427

**Comment by CodeNameJacks** [comment]
@developerisnow did you find a working solution? I am facing a similar problem.
