### ISSUE TITLE
Error building node Chroma

### ISSUE THREAD

**Issue by BeatArnet** [logspace-ai/langflow#260]
**Error building Chroma**
Using the example py-pdf-loader I get the error:

_Error building node Chroma: 'latin-l' codec can't encode characters in position 7-36: ordinal not in range(256)_

It does not change if I use a TextLoader instead of a PY PDF loader.
I work with a swiss german keyboard and I use Umlaute (does not know if this is relevant...)

Browser Chrome, Version 112.0.5615.138

![image](https://user-images.githubusercontent.com/3456797/236683843-0b9cd414-a559-424e-9505-36db33038149.png)

**Comment by BeatArnet** [comment]
Some more details to the error:

╭──────────────────────── Traceback (most recent call last) ────────────────────────╮
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \api\validate.py:48 in post_validate_node                                         │
                    │                                                                                   │
                    │   45 │   │   # validate node                                                      │
                    │   46 │   │   node = graph.get_node(node_id)                                       │
                    │   47 │   │   if node is not None:                                                 │
                    │ ❱ 48 │   │   │   _ = node.build()                                                 │
                    │   49 │   │   │   return str(node.params)                                          │
                    │   50 │   │   raise Exception(f"Node {node_id} not found")                         │
                    │   51 │   except Exception as e:                                                   │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\nodes.py:34 in build                                                       │
                    │                                                                                   │
                    │    31 │   │   │   for chain_node in self.chains:                                  │
                    │    32 │   │   │   │   chain_node.build(tools=self.tools)                          │
                    │    33 │   │   │                                                                   │
                    │ ❱  34 │   │   │   self._build()                                                   │
                    │    35 │   │                                                                       │
                    │    36 │   │   #! Cannot deepcopy VectorStore, VectorStoreRouter, or SQL agents    │
                    │    37 │   │   if self.node_type in ["VectorStoreAgent", "VectorStoreRouterAgent", │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:161 in _build                                                      │
                    │                                                                                   │
                    │   158 │   │   │   │   if value == self:                                           │
                    │   159 │   │   │   │   │   del self.params[key]                                    │
                    │   160 │   │   │   │   │   continue                                                │
                    │ ❱ 161 │   │   │   │   result = value.build()                                      │
                    │   162 │   │   │   │   # If the key is "func", then we need to use the run method  │
                    │   163 │   │   │   │   if key == "func":                                           │
                    │   164 │   │   │   │   │   if not isinstance(result, types.FunctionType):          │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:207 in build                                                       │
                    │                                                                                   │
                    │   204 │                                                                           │
                    │   205 │   def build(self, force: bool = False) -> Any:                            │
                    │   206 │   │   if not self._built or force:                                        │
                    │ ❱ 207 │   │   │   self._build()                                                   │
                    │   208 │   │                                                                       │
                    │   209 │   │   #! Deepcopy is breaking for vectorstores                            │
                    │   210 │   │   if self.base_type in [                                              │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:161 in _build                                                      │
                    │                                                                                   │
                    │   158 │   │   │   │   if value == self:                                           │
                    │   159 │   │   │   │   │   del self.params[key]                                    │
                    │   160 │   │   │   │   │   continue                                                │
                    │ ❱ 161 │   │   │   │   result = value.build()                                      │
                    │   162 │   │   │   │   # If the key is "func", then we need to use the run method  │
                    │   163 │   │   │   │   if key == "func":                                           │
                    │   164 │   │   │   │   │   if not isinstance(result, types.FunctionType):          │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:207 in build                                                       │
                    │                                                                                   │
                    │   204 │                                                                           │
                    │   205 │   def build(self, force: bool = False) -> Any:                            │
                    │   206 │   │   if not self._built or force:                                        │
                    │ ❱ 207 │   │   │   self._build()                                                   │
                    │   208 │   │                                                                       │
                    │   209 │   │   #! Deepcopy is breaking for vectorstores                            │
                    │   210 │   │   if self.base_type in [                                              │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:196 in _build                                                      │
                    │                                                                                   │
                    │   193 │   │   │   │   params=self.params,                                         │
                    │   194 │   │   │   )                                                               │
                    │   195 │   │   except Exception as exc:                                            │
                    │ ❱ 196 │   │   │   raise ValueError(                                               │
                    │   197 │   │   │   │   f"Error building node {self.node_type}: {str(exc)}"         │
                    │   198 │   │   │   ) from exc                                                      │
                    │   199                                                                             │
                    
                    ValueError: Error building node Chroma: 'latin-1' codec can't encode characters in
                    position 7-36: ordinal not in range(256)
'''

**Comment by rodrigosnader** [comment]
@BeatArnet can you export and send the flow?

**Comment by BeatArnet** [comment]
[Text-loader without API-Key.json.txt](https://github.com/logspace-ai/langflow/files/11431768/Text-loader.without.API-Key.json.txt)

This is my JSON-File without OPENAI-API-KEYs.

**Comment by rodrigosnader** [comment]
@BeatArnet Can you retry with the newest version? And have you tested w/ multiple PDF files?

**Comment by BeatArnet** [comment]
After installing the latest version 0.70 with "pip install langflow --upgrade", no more error messages in the browser, but the following errors in the command shell:

[17:04:22] INFO     [17:04:22] - INFO - error_code=invalid_api_key error_message= error_param=None            util.py:67
                    error_type=invalid_request_error message='OpenAI API error received' stream_error=False
           ERROR    [17:04:22] - ERROR - Error building node Chroma: <empty message>                      validate.py:56
                    ╭──────────────────────── Traceback (most recent call last) ────────────────────────╮
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:190 in _build                                                      │
                    │                                                                                   │
                    │   187 │   │   # and return the instance                                           │
                    │   188 │   │                                                                       │
                    │   189 │   │   try:                                                                │
                    │ ❱ 190 │   │   │   self._built_object = loading.instantiate_class(                 │
                    │   191 │   │   │   │   node_type=self.node_type,                                   │
                    │   192 │   │   │   │   base_type=self.base_type,                                   │
                    │   193 │   │   │   │   params=self.params,                                         │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \interface\loading.py:41 in instantiate_class                                     │
                    │                                                                                   │
                    │    38 │   │   │   return custom_agent.initialize(**params)                        │
                    │    39 │                                                                           │
                    │    40 │   class_object = import_by_type(_type=base_type, name=node_type)          │
                    │ ❱  41 │   return instantiate_based_on_type(class_object, base_type, node_type, pa │
                    │    42                                                                             │
                    │    43                                                                             │
                    │    44 def convert_params_to_sets(params):                                         │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \interface\loading.py:65 in instantiate_based_on_type                             │
                    │                                                                                   │
                    │    62 │   elif base_type == "embeddings":                                         │
                    │    63 │   │   return instantiate_embedding(class_object, params)                  │
                    │    64 │   elif base_type == "vectorstores":                                       │
                    │ ❱  65 │   │   return instantiate_vectorstore(class_object, params)                │
                    │    66 │   elif base_type == "documentloaders":                                    │
                    │    67 │   │   return instantiate_documentloader(class_object, params)             │
                    │    68 │   elif base_type == "textsplitters":                                      │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \interface\loading.py:128 in instantiate_vectorstore                              │
                    │                                                                                   │
                    │   125 │   │   │   "The source you provided did not load correctly or was empty."  │
                    │   126 │   │   │   "This may cause an error in the vectorstore."                   │
                    │   127 │   │   )                                                                   │
                    │ ❱ 128 │   return class_object.from_documents(**params)                            │
                    │   129                                                                             │
                    │   130                                                                             │
                    │   131 def instantiate_documentloader(class_object, params):                       │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\vectorstores\chroma.py:413 in from_documents                                    │
                    │                                                                                   │
                    │   410 │   │   """                                                                 │
                    │   411 │   │   texts = [doc.page_content for doc in documents]                     │
                    │   412 │   │   metadatas = [doc.metadata for doc in documents]                     │
                    │ ❱ 413 │   │   return cls.from_texts(                                              │
                    │   414 │   │   │   texts=texts,                                                    │
                    │   415 │   │   │   embedding=embedding,                                            │
                    │   416 │   │   │   metadatas=metadatas,                                            │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\vectorstores\chroma.py:381 in from_texts                                        │
                    │                                                                                   │
                    │   378 │   │   │   client_settings=client_settings,                                │
                    │   379 │   │   │   client=client,                                                  │
                    │   380 │   │   )                                                                   │
                    │ ❱ 381 │   │   chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=i │
                    │   382 │   │   return chroma_collection                                            │
                    │   383 │                                                                           │
                    │   384 │   @classmethod                                                            │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\vectorstores\chroma.py:158 in add_texts                                         │
                    │                                                                                   │
                    │   155 │   │   │   ids = [str(uuid.uuid1()) for _ in texts]                        │
                    │   156 │   │   embeddings = None                                                   │
                    │   157 │   │   if self._embedding_function is not None:                            │
                    │ ❱ 158 │   │   │   embeddings = self._embedding_function.embed_documents(list(text │
                    │   159 │   │   self._collection.add(                                               │
                    │   160 │   │   │   metadatas=metadatas, embeddings=embeddings, documents=texts, id │
                    │   161 │   │   )                                                                   │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\embeddings\openai.py:275 in embed_documents                                     │
                    │                                                                                   │
                    │   272 │   │   """                                                                 │
                    │   273 │   │   # NOTE: to keep things simple, we assume the list may contain texts │
                    │   274 │   │   #       than the maximum context and use length-safe embedding func │
                    │ ❱ 275 │   │   return self._get_len_safe_embeddings(texts, engine=self.deployment) │
                    │   276 │                                                                           │
                    │   277 │   def embed_query(self, text: str) -> List[float]:                        │
                    │   278 │   │   """Call out to OpenAI's embedding endpoint for embedding query text │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\embeddings\openai.py:208 in _get_len_safe_embeddings                            │
                    │                                                                                   │
                    │   205 │   │   │   batched_embeddings = []                                         │
                    │   206 │   │   │   _chunk_size = chunk_size or self.chunk_size                     │
                    │   207 │   │   │   for i in range(0, len(tokens), _chunk_size):                    │
                    │ ❱ 208 │   │   │   │   response = embed_with_retry(                                │
                    │   209 │   │   │   │   │   self,                                                   │
                    │   210 │   │   │   │   │   input=tokens[i : i + _chunk_size],                      │
                    │   211 │   │   │   │   │   engine=self.deployment,                                 │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\embeddings\openai.py:63 in embed_with_retry                                     │
                    │                                                                                   │
                    │    60 │   def _embed_with_retry(**kwargs: Any) -> Any:                            │
                    │    61 │   │   return embeddings.client.create(**kwargs)                           │
                    │    62 │                                                                           │
                    │ ❱  63 │   return _embed_with_retry(**kwargs)                                      │
                    │    64                                                                             │
                    │    65                                                                             │
                    │    66 class OpenAIEmbeddings(BaseModel, Embeddings):                              │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity │
                    │ \__init__.py:289 in wrapped_f                                                     │
                    │                                                                                   │
                    │   286 │   │                                                                       │
                    │   287 │   │   @functools.wraps(f)                                                 │
                    │   288 │   │   def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:                  │
                    │ ❱ 289 │   │   │   return self(f, *args, **kw)                                     │
                    │   290 │   │                                                                       │
                    │   291 │   │   def retry_with(*args: t.Any, **kwargs: t.Any) -> WrappedFn:         │
                    │   292 │   │   │   return self.copy(*args, **kwargs).wraps(f)                      │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity │
                    │ \__init__.py:379 in __call__                                                      │
                    │                                                                                   │
                    │   376 │   │                                                                       │
                    │   377 │   │   retry_state = RetryCallState(retry_object=self, fn=fn, args=args, k │
                    │   378 │   │   while True:                                                         │
                    │ ❱ 379 │   │   │   do = self.iter(retry_state=retry_state)                         │
                    │   380 │   │   │   if isinstance(do, DoAttempt):                                   │
                    │   381 │   │   │   │   try:                                                        │
                    │   382 │   │   │   │   │   result = fn(*args, **kwargs)                            │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity │
                    │ \__init__.py:314 in iter                                                          │
                    │                                                                                   │
                    │   311 │   │                                                                       │
                    │   312 │   │   is_explicit_retry = fut.failed and isinstance(fut.exception(), TryA │
                    │   313 │   │   if not (is_explicit_retry or self.retry(retry_state)):              │
                    │ ❱ 314 │   │   │   return fut.result()                                             │
                    │   315 │   │                                                                       │
                    │   316 │   │   if self.after is not None:                                          │
                    │   317 │   │   │   self.after(retry_state)                                         │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_ba │
                    │ se.py:451 in result                                                               │
                    │                                                                                   │
                    │   448 │   │   │   │   if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:      │
                    │   449 │   │   │   │   │   raise CancelledError()                                  │
                    │   450 │   │   │   │   elif self._state == FINISHED:                               │
                    │ ❱ 451 │   │   │   │   │   return self.__get_result()                              │
                    │   452 │   │   │   │                                                               │
                    │   453 │   │   │   │   self._condition.wait(timeout)                               │
                    │   454                                                                             │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_ba │
                    │ se.py:403 in __get_result                                                         │
                    │                                                                                   │
                    │   400 │   def __get_result(self):                                                 │
                    │   401 │   │   if self._exception:                                                 │
                    │   402 │   │   │   try:                                                            │
                    │ ❱ 403 │   │   │   │   raise self._exception                                       │
                    │   404 │   │   │   finally:                                                        │
                    │   405 │   │   │   │   # Break a reference cycle with the exception in self._excep │
                    │   406 │   │   │   │   self = None                                                 │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity │
                    │ \__init__.py:382 in __call__                                                      │
                    │                                                                                   │
                    │   379 │   │   │   do = self.iter(retry_state=retry_state)                         │
                    │   380 │   │   │   if isinstance(do, DoAttempt):                                   │
                    │   381 │   │   │   │   try:                                                        │
                    │ ❱ 382 │   │   │   │   │   result = fn(*args, **kwargs)                            │
                    │   383 │   │   │   │   except BaseException:  # noqa: B902                         │
                    │   384 │   │   │   │   │   retry_state.set_exception(sys.exc_info())  # type: igno │
                    │   385 │   │   │   │   else:                                                       │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langchai │
                    │ n\embeddings\openai.py:61 in _embed_with_retry                                    │
                    │                                                                                   │
                    │    58 │                                                                           │
                    │    59 │   @retry_decorator                                                        │
                    │    60 │   def _embed_with_retry(**kwargs: Any) -> Any:                            │
                    │ ❱  61 │   │   return embeddings.client.create(**kwargs)                           │
                    │    62 │                                                                           │
                    │    63 │   return _embed_with_retry(**kwargs)                                      │
                    │    64                                                                             │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\a │
                    │ pi_resources\embedding.py:33 in create                                            │
                    │                                                                                   │
                    │   30 │   │                                                                        │
                    │   31 │   │   while True:                                                          │
                    │   32 │   │   │   try:                                                             │
                    │ ❱ 33 │   │   │   │   response = super().create(*args, **kwargs)                   │
                    │   34 │   │   │   │                                                                │
                    │   35 │   │   │   │   # If a user specifies base64, we'll just return the encoded  │
                    │   36 │   │   │   │   # This is only for the default case.                         │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\a │
                    │ pi_resources\abstract\engine_api_resource.py:153 in create                        │
                    │                                                                                   │
                    │   150 │   │   │   api_key, api_base, api_type, api_version, organization, **param │
                    │   151 │   │   )                                                                   │
                    │   152 │   │                                                                       │
                    │ ❱ 153 │   │   response, _, api_key = requestor.request(                           │
                    │   154 │   │   │   "post",                                                         │
                    │   155 │   │   │   url,                                                            │
                    │   156 │   │   │   params=params,                                                  │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\a │
                    │ pi_requestor.py:226 in request                                                    │
                    │                                                                                   │
                    │   223 │   │   │   request_id=request_id,                                          │
                    │   224 │   │   │   request_timeout=request_timeout,                                │
                    │   225 │   │   )                                                                   │
                    │ ❱ 226 │   │   resp, got_stream = self._interpret_response(result, stream)         │
                    │   227 │   │   return resp, got_stream, self.api_key                               │
                    │   228 │                                                                           │
                    │   229 │   @overload                                                               │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\a │
                    │ pi_requestor.py:619 in _interpret_response                                        │
                    │                                                                                   │
                    │   616 │   │   │   ), True                                                         │
                    │   617 │   │   else:                                                               │
                    │   618 │   │   │   return (                                                        │
                    │ ❱ 619 │   │   │   │   self._interpret_response_line(                              │
                    │   620 │   │   │   │   │   result.content.decode("utf-8"),                         │
                    │   621 │   │   │   │   │   result.status_code,                                     │
                    │   622 │   │   │   │   │   result.headers,                                         │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\a │
                    │ pi_requestor.py:682 in _interpret_response_line                                   │
                    │                                                                                   │
                    │   679 │   │   # to better handle the "error while streaming" case.                │
                    │   680 │   │   stream_error = stream and "error" in resp.data                      │
                    │   681 │   │   if stream_error or not 200 <= rcode < 300:                          │
                    │ ❱ 682 │   │   │   raise self.handle_error_response(                               │
                    │   683 │   │   │   │   rbody, rcode, resp.data, rheaders, stream_error=stream_erro │
                    │   684 │   │   │   )                                                               │
                    │   685 │   │   return resp                                                         │
                    ╰───────────────────────────────────────────────────────────────────────────────────╯
                    AuthenticationError: <empty message>

                    The above exception was the direct cause of the following exception:

                    ╭──────────────────────── Traceback (most recent call last) ────────────────────────╮
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \api\validate.py:53 in post_validate_node                                         │
                    │                                                                                   │
                    │   50 │   │   if node is None:                                                     │
                    │   51 │   │   │   raise ValueError(f"Node {node_id} not found")                    │
                    │   52 │   │   if not isinstance(node, VectorStoreNode):                            │
                    │ ❱ 53 │   │   │   node.build()                                                     │
                    │   54 │   │   return json.dumps({"valid": True, "params": str(node._built_object_r │
                    │   55 │   except Exception as e:                                                   │
                    │   56 │   │   logger.exception(e)                                                  │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:207 in build                                                       │
                    │                                                                                   │
                    │   204 │                                                                           │
                    │   205 │   def build(self, force: bool = False) -> Any:                            │
                    │   206 │   │   if not self._built or force:                                        │
                    │ ❱ 207 │   │   │   self._build()                                                   │
                    │   208 │   │                                                                       │
                    │   209 │   │   #! Deepcopy is breaking for vectorstores                            │
                    │   210 │   │   if self.base_type in [                                              │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:161 in _build                                                      │
                    │                                                                                   │
                    │   158 │   │   │   │   if value == self:                                           │
                    │   159 │   │   │   │   │   del self.params[key]                                    │
                    │   160 │   │   │   │   │   continue                                                │
                    │ ❱ 161 │   │   │   │   result = value.build()                                      │
                    │   162 │   │   │   │   # If the key is "func", then we need to use the run method  │
                    │   163 │   │   │   │   if key == "func":                                           │
                    │   164 │   │   │   │   │   if not isinstance(result, types.FunctionType):          │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:207 in build                                                       │
                    │                                                                                   │
                    │   204 │                                                                           │
                    │   205 │   def build(self, force: bool = False) -> Any:                            │
                    │   206 │   │   if not self._built or force:                                        │
                    │ ❱ 207 │   │   │   self._build()                                                   │
                    │   208 │   │                                                                       │
                    │   209 │   │   #! Deepcopy is breaking for vectorstores                            │
                    │   210 │   │   if self.base_type in [                                              │
                    │                                                                                   │
                    │ C:\Users\beata\AppData\Local\Programs\Python\Python310\lib\site-packages\langflow │
                    │ \graph\base.py:196 in _build                                                      │
                    │                                                                                   │
                    │   193 │   │   │   │   params=self.params,                                         │
                    │   194 │   │   │   )                                                               │
                    │   195 │   │   except Exception as exc:                                            │
                    │ ❱ 196 │   │   │   raise ValueError(                                               │
                    │   197 │   │   │   │   f"Error building node {self.node_type}: {str(exc)}"         │
                    │   198 │   │   │   ) from exc                                                      │
                    │   199                                                                             │
                    ╰───────────────────────────────────────────────────────────────────────────────────╯
                    ValueError: Error building node Chroma: <empty message>
INFO:     127.0.0.1:54791 - "POST /validate/node/dndnode_105 HTTP/1.1" 200 OK
[17:05:01] WARNING  [17:05:01] - WARNING - Retrying                                                   before_sleep.py:65
                    langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0
                    seconds as it raised APIConnectionError: Error communicating with OpenAI:
                    ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung
                    wurde vom Remotehost geschlossen', None, 10054, None)).

**Comment by rodrigosnader** [comment]
@BeatArnet, it looks like you passed an incorrect API key. Can you please check if (in both components where there's an API key input) the values are valid? We previously saw an issue where we'd copy and paste API keys from one component to another they'd break.

**Comment by BeatArnet** [comment]
In the meantime, I deleted the repository and all associated files, installed the latest version and it works. Thanks for support.
