### ISSUE TITLE
Allow selecting custom model names in openai LLM

### ISSUE THREAD

**Issue by Nintorac** [logspace-ai/langflow#262]
I am using SimpleAI to host some models and would like to use langflow to chat with them. It would be good to be allowed to enter custom model names in the text box.

![image](https://user-images.githubusercontent.com/24326299/237042617-73cefbc2-3c11-4a45-b43d-cd70784890c2.png)

**Comment by rodrigosnader** [comment]
Hi @Nintorac, can you share their website or repo?

**Comment by Nintorac** [comment]
Oh yes, can be quite hard to find. It's here https://github.com/lhenault/simpleAI
