### ISSUE TITLE
CRA to Vite?

### ISSUE THREAD

**Issue by gsaivinay** [logspace-ai/langflow#264]
With the notorious fame of CRA and its Webpack server, should we consider the route migrate from react-scripts to Vite? which is the most loved way to create and develop SPA by the frontend community.

I'm happy to test and raise a PR for this.

**Comment by ogabrielluiz** [comment]
Hi, @gsaivinay. I'd like to know more about the main advantages of making this change and also how big of a refactor this would require. Could you elaborate a bit, please?

**Comment by gsaivinay** [comment]
Hello @ogabrielluiz,

- There will very minimal effort to refactor as per my experience.
- Vite is very fast to start development server, build and hot reload.
- for static file serving i.e., SPA nothing will change by migrating to vite.
- Over the time, when project is growing and more code is added to frontend app, it'll be more painful to work with CRA and react-scripts with its webpack server. We can find many articles online about this -> https://muzammilbilwani.medium.com/why-you-should-prefer-vite-over-create-react-app-cra-5adf3e71771f

Overall, I'd say it'll be worth to migrate to Vite and should be quick enough without changing the existing SPA.

**Comment by anovazzi1** [comment]
Hey there, @gsaivinay!

Firstly, I want to say that your idea is great, and I agree with you that CRA could become a problem in the future. After taking a look at Vite, I agree that the core project would not require significant refactoring, only some changes to the build process for production and running in dev mode.

At this time, our front-end team has other pressing priorities, but we would be thrilled if you could implement these changes and create a pull request. If you do so, please ensure that you outline the changes required for building and running the project live in the description, in terms of commands and not technical or performance aspects.

We would love to test your implementation and potentially migrate to Vite, so we appreciate any work you can put in!

Thank you for your contribution, and let us know if you have any questions.

**Comment by gsaivinay** [comment]
Sure, I can make these changes. I'd say there'll be basically no difference in build process, but there might be few changes in development process especially API proxy calls but not too different. I'd add more details while I migrate to Vite.

Would you be able to suggest any test cases I must perform after making changes to frontend so that we can make sure everything is working as expected.

**Comment by anovazzi1** [comment]
you have to run 'make build' and then install the file in the 'dist' folder that appears using 'pip install,' and then test the 'langflow' command or 'python -m langflow.
this will test the build, to test for dev, just run locally and try some examples.
