### ISSUE TITLE
Error building node OpenAl: 2 validation errors

### ISSUE THREAD

**Issue by MateiG** [logspace-ai/langflow#268]
Hi I'm getting this error when trying to build the example shown on the ReadME. No parameters except the OpenAI API key have been modified. Not sure what OpenAI base key refers too but that's my guess as to what is causing this runtime issue.
See screenshots below:
<img width="393" alt="Screenshot 2023-05-09 at 10 53 54 AM" src="https://github.com/logspace-ai/langflow/assets/28810322/a952ecf9-b14a-472c-8a05-2f487840bc5d">
<img width="931" alt="Screenshot 2023-05-09 at 10 54 37 AM" src="https://github.com/logspace-ai/langflow/assets/28810322/ef0f26af-4290-4f12-b073-a4eded2eb397">
CCing @mikayelh

**Comment by ogabrielluiz** [comment]
This was a recent change in LangFlow. We'll release a fix for it this week, we are just wrapping the release.

**Comment by rui-hai** [comment]
the same error

**Comment by ogabrielluiz** [comment]
Hi! We've just released a new version. Could y'all try it out?
