### ISSUE TITLE
Why the UI in hugging face for 'OpenAI' LLM is different than the one in the 'tool PAL math' example???

### ISSUE THREAD

**Issue by cosmosanalytics** [logspace-ai/langflow#270]
![image](https://github.com/logspace-ai/langflow/assets/100080151/1070f49c-f91a-442b-9f48-e3449ed30732)

**Comment by carlosrcoelho** [comment]
Hey, @cosmosanalytics! Thanks for the heads up.

This is happening because the tool-pal-math comes from the older version of LangFlow.  We'll check it out on Hugging Face Spaces ASAP.
