### ISSUE TITLE
How to add system prompt with openAI conversational API? 

### ISSUE THREAD

**Issue by sam1am** [logspace-ai/langflow#272]
How can you set the system prompt for the conversational API? Is it possible?

**Comment by ogabrielluiz** [comment]
The prompting experience at the moment is limited to the PromptTemplate interface. We'd have to create a particular node for the ChatPromptTemplate which is definitely in the roadmap. 

Ideally, we would build the HumanMessage, AIMessage, and SystemMessage but I'm not sure that would be a good experience. We'll think this through and add it ASAP.
