### ISSUE TITLE
Please provide 2 examples such that the 2 python agent examples in "langchain" can be reproduced in "langflow" 

### ISSUE THREAD

**Issue by cosmosanalytics** [logspace-ai/langflow#273]
Please provide 2 examples such that the 2 python agent examples in "langchain" can be reproduced in "langflow" 
https://python.langchain.com/en/latest/modules/agents/toolkits/examples/python.html

**Comment by cosmosanalytics** [comment]
![image](https://github.com/logspace-ai/langflow/assets/100080151/58727e5d-1270-46f2-b13e-f171efba5a4e)

**Comment by cosmosanalytics** [comment]
![image](https://github.com/logspace-ai/langflow/assets/100080151/c192571f-1c2d-4ebc-b0a4-79ca61c76ee0)

**Comment by cosmosanalytics** [comment]
![image](https://github.com/logspace-ai/langflow/assets/100080151/36e98eb5-302f-4fc6-b03f-f4f55120d57f)

**Comment by ogabrielluiz** [comment]
In this second case, you probably need to install torch and try again.

**Comment by cosmosanalytics** [comment]
![image](https://github.com/logspace-ai/langflow/assets/100080151/4e63b068-6a9a-406b-878e-a465109fe1fe)
