### ISSUE TITLE
Langflow started using docker but connection refused error.

### ISSUE THREAD

**Issue by vanshsehgal2001** [logspace-ai/langflow#275]
I started langflow by cloning the repo and starting it using Docker. It started but its showing connection refused, proxy error and so UI is not rendering properly. I am attaching the screenshots too. Please help me out.
<img width="1440" alt="Screenshot 2023-05-10 at 4 30 59 PM" src="https://github.com/logspace-ai/langflow/assets/62723522/65174c58-fd8c-48b4-83ac-0dbd215acd2b">

<img width="1439" alt="Screenshot 2023-05-10 at 4 28 55 PM" src="https://github.com/logspace-ai/langflow/assets/62723522/9995c111-23a0-41d4-bbc6-fbb54d5e6ac6">

Are there any changes that need to be made in docker-compose.yaml or in package.json file?

**Comment by ogabrielluiz** [comment]
Hey @vanshsehgal2001. Change the proxy in package.json file to `http://backend:7860` and it should work.

**Comment by vanshsehgal2001** [comment]
It worked. Thanks a lot. Continuing to this conversation, how can I add let's say a new loader maybe GCSLoader(present in langchain). I added the template in backend with all the fields and entry in config.yaml . Is anything apart from this needs to be done? I am a bit curious how do all the loaders get which loader needs to be referenced from langchain.

**Comment by developerisnow** [comment]
> Hey @vanshsehgal2001. Change the proxy in package.json file to `http://backend:7860` and it should work.

I did `http://backend:7860`  || `http://<server_ip>:7860`  || `http://127.0.0.1:7860`  and it help with error confused but still error with https://github.com/logspace-ai/langflow/issues/283

**Comment by vanshsehgal2001** [comment]
> > Hey @vanshsehgal2001. Change the proxy in package.json file to `http://backend:7860` and it should work.
> 
> I put in package.json: `http://backend:7860` || `http://<server_ip>:7860` || `http://127.0.0.1:7860` and it help with error confused but still error with FRONTEND
> 
> ...langflow$ docker-compose logs backend -f
> 
> ```
> langflow-backend-1  | INFO:     Waiting for application shutdown.
> langflow-backend-1  | INFO:     Application shutdown complete.
> langflow-backend-1  | INFO:     Finished server process [8]
> langflow-backend-1  | INFO:     Stopping reloader process [1]
> langflow-backend-1  | INFO:     Will watch for changes in these directories: ['/app']
> langflow-backend-1  | INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
> langflow-backend-1  | INFO:     Started reloader process [1] using WatchFiles
> langflow-backend-1  | INFO:     Started server process [8]
> langflow-backend-1  | INFO:     Waiting for application startup.
> langflow-backend-1  | INFO:     Application startup complete.
> langflow-backend-1  | INFO:     172.20.0.3:56436 - "GET /all HTTP/1.1" 200 OK
> langflow-backend-1  | INFO:     172.20.0.3:56202 - "GET /all HTTP/1.1" 200 OK
> langflow-backend-1  | INFO:     172.20.0.3:59422 - "GET /all HTTP/1.1" 200 OK
> langflow-backend-1  | INFO:     172.20.0.3:48278 - "GET /all HTTP/1.1" 200 OK
> ```
> 
> it makes my frontend http://:3000 white ERROR screen, but backend works 200.
> 
> So if BACKEND fix, FRONTEND FAIL.

I was also facing the same issue. It was showng white screen with http://localhost:3000 but it worked fine when I changed the url to http://127.0.0.1:3000 . It worked for me. You can try this.
