### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by AdamAdamAdam** [logspace-ai/langflow#288]
Building wheels for collected packages: llama-cpp-python, hnswlib
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [308 lines of output]

**Comment by ogabrielluiz** [comment]
Hi, @AdamAdamAdam. Please use the bug template to report bugs.

This is probably a problem in your environment. Some dependencies use the local binaries to build themselves so you might try installing gcc and g++, maybe that helps.
