### ISSUE TITLE
LangChain LLMs support

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#290]
This issue is to track the support for LLMs and issues related to adding support for them. I'll add to this list as we see the need for more.

- [x] OpenAI
- [x] #332
- [x] HuggingFace Hub
- [ ] #263
- [x] CohereAI
- [x] #347
- [x] Implement Anthropic
- [x] #416 
This list will be updated as needed or as suggestions appear in the comments.

**Comment by hellangleZ** [comment]
Need support AzureOpenAI

**Comment by lihanghang** [comment]
> Need support AzureOpenAI

+1

**Comment by qixiaobo** [comment]
Now I use this https://github.com/stulzq/azure-openai-proxy

**Comment by ogabrielluiz** [comment]
I think the OpenAI class has a parameter to define if you want to use openai or azure. From what I found out when logging into Azure, the access to the AzureOpenAI API needs to be authorized by them through a tedious process that I haven't had the time to go through. 

Maybe we can create a branch for someone here to test it. #332
