### ISSUE TITLE
Vector Stores support

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#291]
This is a list to track all the supported Vector Stores. This list will be updated as needed.

- [x] ChromaDB
- [x] #296
- [x] #297
- [x] #335
- [x] #336
- [x] #361
- [x] #415

If there are any other suggestions they will be added to the list.

**Comment by AeonSunLVX** [comment]
Supabase please

**Comment by shivaraj65** [comment]
add milvus to the list. it would be a lot helpful.

**Comment by morgango** [comment]
Elasticsearch would be a great addition.  It is `langchain.vectorstores.ElasticVectorSearch` in langchain.

**Comment by sam1am** [comment]
Pinecone seems to be very widely used.

**Comment by sekhar-hari** [comment]
Is there a support available for Milvus? Much needed. Thanks.

**Comment by dylan-tong-aws** [comment]
Would love to see OpenSearch support: https://js.langchain.com/docs/api/vectorstores_opensearch/.

**Comment by akshat-io** [comment]
Milvus support is much needed.

**Comment by phiresearch-github** [comment]
Zep vector store would be fantastic!
