### ISSUE TITLE
frontend ws port, The parameter is hard coded?

### ISSUE THREAD

**Issue by av8dtop** [logspace-ai/langflow#298]
use docker-compser.yml
frontend > port > 5999:3000

error : 192.168.1.103:3000/ws' failed: 
WebSocketClient @ bundle.js:12

websocket  port, The parameter is hard coded?

**Comment by anovazzi1** [comment]
websocket port is selected like this
```
        process.env.NODE_ENV === "development"
          ? `ws://localhost:7860/chat/${id.current}`
          : `${window.location.protocol === "https:" ? "wss" : "ws"}://${window.location.host
          }/chat/${id.current}`;
          ```

**Comment by av8dtop** [comment]
#308

**Comment by ogabrielluiz** [comment]
Hey, @av8dtop. 
The issue you mentioned seems to be fixed in dev. Could you try it out by running `make dev build=1`?

In development, we start frontend and backend separately so we need to point the frontend app to a specific URL. When serving the static files we can get the window.location.host.

**Comment by ogabrielluiz** [comment]
Could you try removing the tab and adding a new one? 

Also, how are you running the application?

**Comment by av8dtop** [comment]
@ogabrielluiz 
YES
vmware -> ubuntu -> docker

**Comment by av8dtop** [comment]
I currently use docker-compose.yml simply, can you help me or are there any other ways that will not cause WS errors?

**Comment by anovazzi1** [comment]
probably there is an error related to the docker network system and the VMware, can you try running it not inside a VMware or outside the docker?

**Comment by qq1499412503** [comment]
hi， I'v done the debug on this issues, the location of it to fix follow
Frontend/src/models/chatmodel/index.tsx
Line 115

Busy on every, may someone do it and merge LOL

**Comment by av8dtop** [comment]
> 

Thank u

**Comment by av8dtop** [comment]
@ogabrielluiz merge thank u
