### ISSUE TITLE
send message in the chatbox will give a error : 'latin-1' codec can't encode characters in position 0-63: ordinal not in range(256)

### ISSUE THREAD

**Issue by 8Avalon8** [logspace-ai/langflow#30]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1633203/225727537-e362c829-c53a-40d6-b1c2-698101095ab0.png">

**Comment by ibiscp** [comment]
I believe you are using only an LLM, you need to insert it with an LLMChain with a Prompt. I already added an Error Handling when only an LLM is added.

**Comment by 8Avalon8** [comment]
> I believe you are using only an LLM, you need to insert it with an LLMChain with a Prompt. I already added an Error Handling when only an LLM is added.

thanks for your reply! I actually using llmchain with a promt like this graph,but still give this error
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1633203/225981059-a0982d31-647a-46a3-acb7-6cf3661e395d.png">

**Comment by ibiscp** [comment]
That's odd, could you please add the API keys again? Or export the flow to check the values for that in the json file.

**Comment by 8Avalon8** [comment]
> That's odd, could you please add the API keys again? Or export the flow to check the values for that in the json file.

Alright, I found that after re-entering the Search API Key, everything is working normally now. I also created a new image, and everything seems to be fine. Perhaps I accidentally inputted the wrong key earlier. Thank you for your help!
