### ISSUE TITLE
GPC Shell Script - Websocket Connection Failure

### ISSUE THREAD

**Issue by cckalen** [logspace-ai/langflow#300]
I recently attempted a deployment on Google Cloud Platform (GCP) using the provided Google Cloud Shell script by @genome21. While the instance was successfully created and is accessible via a browser, I'm experiencing issues with the functionality of the tool.

Specifically, the chatbox feature is non-operational to test anything. When attempting to open the chatbox after creating or importing any kind of flow, I'm met with a persistent websocket error in the console.  
 

```
WebSocket connection to 'ws://34.31.61.111:8080/chat/9d2d13fa-5fe6-4d1d-ae96-bb3922ee7c33' failed
``` 

This issue is consistently reproducible by simply creating or importing a flow and then trying to access the chatbox feature.

**Comment by genome21** [comment]
Pull Request #301 addresses this

**Comment by ogabrielluiz** [comment]
It seems you are using a Vector Store. They require embeddings to function which use the OpenAIEmbeddings endpoint.

**Comment by qq1499412503** [comment]
See #298 
This thread might close
