### ISSUE TITLE
Langchain Dataframe Agents?

### ISSUE THREAD

**Issue by ekolawole** [logspace-ai/langflow#312]
Why are the langchain dataframe agents missing from langflow? Those are the best agents for data scientist? Every other agent does not apply to data science. 

Also, we need a Polars Dataframe Agent. Polars is much better and faster than Pandas and Spark. Please can you create an agent for Polars Dataframe for csv input, with Local LLM CPP support. Thank You!

**Comment by ogabrielluiz** [comment]
Hi, @ekolawole! 
To use a dataframe agent LangFlow requires a way to pass a dataframe to the Agent which is not supported atm. 

We have some things cooking up that would likely make that possible but is still in development.

**Comment by igorpereirabr1** [comment]
any progress?
