### ISSUE TITLE
Can't access by a public ip, I install it on a linux server

### ISSUE THREAD

**Issue by hellangleZ** [logspace-ai/langflow#314]
**Describe the bug**
 
**Browser and Version**  
 - Browser edge
  - Version the newest one

**To Reproduce**
1. Go to 'linux'
2. Click on ' run langflow'

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/15274284/8e0b740a-3b57-4836-b701-2a65499ceda4)

![image](https://github.com/logspace-ai/langflow/assets/15274284/91ad01a7-8cff-489e-b953-813d0f88bcc5)

**Additional context**

I can curl by the linux server but couldn't use UI to access even on a local network windows

**Comment by ogabrielluiz** [comment]
Hey.

If you are using WSL maybe you haven't forwarded the port?

**Comment by hellangleZ** [comment]
> Hey.
> 
> If you are using WSL maybe you haven't forwarded the port?

Just a common Ubuntu server on Azure Cloud, I can access public port such as jupyter and so on, but for langflow, it can't , even using private IP to access on another windows which is in the same subnet, I want to check if there is some setting for openning public access authorization ?

**Comment by hellangleZ** [comment]
After I change to another server, the problem is still there

![image](https://github.com/logspace-ai/langflow/assets/15274284/e7686c85-4493-48ae-a9c6-57c2d3a1e5ba)

![image](https://github.com/logspace-ai/langflow/assets/15274284/31978444-c629-42b5-b934-a980bdb28e06)

**Comment by wangzuohao** [comment]
same issue here running on amazon linux

[2023-05-18 13:49:54 +0000] [2549] [INFO] Starting gunicorn 20.1.0
[2023-05-18 13:49:54 +0000] [2549] [INFO] Listening at: http://127.0.0.1:7860 (2549)
[2023-05-18 13:49:54 +0000] [2549] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-05-18 13:49:54 +0000] [2566] [INFO] Booting worker with pid: 2566
[2023-05-18 13:49:54 +0000] [2566] [INFO] Started server process [2566]
[2023-05-18 13:49:54 +0000] [2566] [INFO] Waiting for application startup.
[2023-05-18 13:49:54 +0000] [2566] [INFO] Application startup complete.

**Comment by hellangleZ** [comment]
> langflow --host --port 7860 this can solve my problem

How to fill the host, I try 172.16.0.5(private ip) still not could access in public internet

**Comment by limumua** [comment]
> 

hi,How did you do it? Can you take a look at examples，thanks

**Comment by sanmoh** [comment]
Start Langflow like this:
_langflow --host 10.101.1.213_
_langflow --help_ for details
![image](https://github.com/logspace-ai/langflow/assets/30400273/7178a3e1-fef7-4f49-9fd5-c1373c8c7b02)

**Comment by YadongM** [comment]
The problem might be due to port listening configuration. Try changing the host and port using this command: 

`langflow --host 0.0.0.0 --port 7860`.
