### ISSUE TITLE
Text area is broken

### ISSUE THREAD

**Issue by levidehaan** [logspace-ai/langflow#328]
**Describe the bug**

The text area is a single line for some reason

can't resize input area
can't move input or see what your chain is
can't format input area data

**Browser and Version**
 - all browsers

**To Reproduce**
1. use app

**Screenshots**

**Additional context**

why does a tool for text have a single line text input area?

**Comment by levidehaan** [comment]
It's the text input area for chat, the imo most important part, you can't see but a single line of text, why can't it be a resizable and have formatting functions on it?

It seems like the most important part, the chat input.

**Comment by rodrigosnader** [comment]
Saw it. Thanks for the feedback, that's a bug. We're working on it right now!
