### ISSUE TITLE
Test AzureOpenAI (requires access)

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#332]
Test and find out why and what isn't working.

**Comment by artdent** [comment]
I have Azure OpenAI access and tested this out. With a few tweaks, the nodes basically work - see #443 for details.

**Comment by lascqy** [comment]
> I have Azure OpenAI access and tested this out. With a few tweaks, the nodes basically work - see #443 for details.
hi，I also have the  Azure OpenAI access and want to test，but I can't see the Azure OpenAI node on the page
could you please tell me some tips about how to test this new feature?

**Comment by artdent** [comment]
@lascqy The nodes are still disabled by default; to test them out, you need to uncomment them in your config.yaml.
