### ISSUE TITLE
Multiple loading of the model resulted out of GPU memory 

### ISSUE THREAD

**Issue by pandab0y** [logspace-ai/langflow#338]
@root_validator()
    def validate_environment(cls, values: Dict) -> Dict:
        """Validate that llama-cpp-python library is installed."""
        model_path = values["model_path"]
        if values["client"] is None:
            try:
                from transformers import AutoTokenizer, AutoModel
                values["client"] = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
                values["tokenizer"] = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

            except ImportError:
==============
the reqeust execute the code every time cause  out of memory;

i know the code  validate  the operation of the   browser  webpage

**Comment by pandab0y** [comment]
but  the  request   http://localhost:3000/validate/node/dndnode_42    build_object  every_time

**Comment by ogabrielluiz** [comment]
That's a good catch. The node validation should be cached. I'll creating an issue and start working on that ASAP
