### ISSUE TITLE
it's really hard to start with win11.i try hours, but not success now. please help!!!

### ISSUE THREAD

**Issue by scs001** [logspace-ai/langflow#364]
**Describe the bug**
Windows can't start langflow.

**Browser and Version**
 -win11

**To Reproduce**
1. pip install langflow
2. wrong:
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [233 lines of output]
      running bdist_wheel
      running build
3. so, i think i should download visual studio c, than i did it
4. pip install langflow
5. wrong again:
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [233 lines of output]
      running bdist_wheel
      running build

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/56543689/7fd62278-1192-4cfa-976d-143990929ad7)

**Additional context**
it's really hard to start with win11.i try hours, but not success now. please help!!!

**Comment by gmacev** [comment]
Make sure to install these:

![image](https://github.com/logspace-ai/langflow/assets/21122921/af76d036-3bf3-4299-9d76-8d4dc1fd29a7)
