### ISSUE TITLE
Try the "Vector Store" example but hit error

### ISSUE THREAD

**Issue by vincent-pli** [logspace-ai/langflow#367]
**Describe the bug**
I took try of the "Vector Store" example by the `import/examples/Vector Store` icon.
I just fill in the `api key` of `OpenAIEnbeddings` and `OpenAI`, then upload a docx file and do the export.

when I try to run it, it raise exception of :
```
  File "/Users/lipeng/workspaces/github.com/logspace-ai/langflow/.langflow/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 45374 tokens (45118 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
Exception ignored in: <function DuckDB.__del__ at 0x1553bf6d0>
Traceback (most recent call last):
  File "/Users/lipeng/workspaces/github.com/logspace-ai/langflow/.langflow/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 387, in __del__
AttributeError: 'NoneType' object has no attribute 'info'
```

**Browser and Version**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by tnsai** [comment]
On the OpenAI component in the flow, try increasing your Max Token from 256.

**Comment by ogabrielluiz** [comment]
The CharacterTextSplitter should have a chunk_size around 1000 to reduce the size of the docs returned by the vector store.

**Comment by Starlord33** [comment]
Where can I get the code of vector store example in python?
