### ISSUE TITLE
Support HuggingFaceInstructEmbeddings

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#376]

**Comment by mindwellsolutions** [comment]
This is a very important and needed update. Flowise already has this feature, there are some great open source embedding system that work nearly as well as open-ai embedding with no cost. It will be great to test them out in langflow. Much thanks!

**Comment by uzumakinaruto19** [comment]
> This is a very important and needed update. Flowise already has this feature, there are some great open source embedding system that work nearly as well as open-ai embedding with no cost. It will be great to test them out in langflow. Much thanks!

can u tell what all are those embedding models works seamlessly ?- I have been using 'sentence-transformers/all-MiniLM-L6-v2'
