### ISSUE TITLE
Critical worker time out

### ISSUE THREAD

**Issue by Kevin-McIsaac** [logspace-ai/langflow#381]
I modified the VectorStore example to use Unstructured Doc loader on this  [Docx](https://www.legislation.wa.gov.au/legislation/statutes.nsf/RedirectURL?OpenAgent&query=mrdoc_29088.docx) . 

When I gave the chat the prompt "What is this legislation I get 

```
[2023-05-28 12:45:03 +0800] [8907] [CRITICAL] WORKER TIMEOUT (pid:11556)
[2023-05-28 12:45:03 +0800] [8907] [WARNING] Worker with pid 11556 was terminated due to signal 6
```

**Comment by Timman6866** [comment]
Still happening to me... 1.5 MB text file embed of about 37k lines

**Comment by icaroryan** [comment]
Increase the timeout for your worker by modifying the `LANGFLOW_WORKER_TIMEOUT` env variable to a higher value. By default, langflow uses 300 seconds, you can just make a big value like 60000 and the problem will be hopefully solved

**Comment by qscwdv65** [comment]
@icaroryan 
Hi, I’m encountering the same issue, but I’m not sure how to increase the timeout duration. I used the command langflow run --timeout 1200, but it doesn’t seem to have any effect. It’s possible that this command is related to a different timeout setting than the Worker Timeout I’m experiencing.

Currently, I’m running LangFlow in an Anaconda environment using the command python -m langflow run. Could you please guide me on how to adjust the timeout? Thank you.

**Comment by icaroryan** [comment]
@qscwdv65 You can set `LANGFLOW_WORKER_TIMEOUT` environmental variable by running `export LANGFLOW_WORKER_TIMEOUT=60000`.
It's worth mentioning that if you're using docker, this needs to be run from inside your container, or set in the env vars in dockerfile
Let me know if this helps
