### ISSUE TITLE
Please support the quantized LLM

### ISSUE THREAD

**Issue by kaleavess** [logspace-ai/langflow#385]

**Comment by ogabrielluiz** [comment]
What does that mean?
[ggml-vic7b-q4_0.bin](https://huggingface.co/vicuna/ggml-vicuna-7b-1.1/blob/main/ggml-vic7b-q4_0.bin)

This is a quantized LLM, correct? I just tested it and it works.

**Comment by kaleavess** [comment]
Langflow only work with ggml form of original LLaMA but not quantized LLaMA
