### ISSUE TITLE
GC Crashes When Try to Add Google Serper API Wrapper

### ISSUE THREAD

**Issue by Josephrp** [logspace-ai/langflow#386]
![image](https://github.com/logspace-ai/langflow/assets/18212928/26bd16c9-e10c-4a13-8e0f-7d6f644dee10)
happens every (two) time

**Comment by ogabrielluiz** [comment]
This is fixed on dev. A release should be going out by the end of the day.

**Comment by Josephrp** [comment]
nice work folks
