### ISSUE TITLE
running on windows still throws the same error > No module named 'fcntl'

### ISSUE THREAD

**Issue by echohive42** [logspace-ai/langflow#39]
I know the other issue was closed thinking this was fixed but the same error still is happening. 
Or is there a different way to run it other than just "langflow" in cli?

**Comment by scott------** [comment]
when I try to run it on windows I get 
C:\Users\Scott>langflow
'langflow' is not recognized as an internal or external command,
operable program or batch file.

When I go to C:\Users\Scott>cd C:\Users\Scott\AppData\Roaming\Python\Python310\site-packages\langflow_backend

C:\Users\Scott\AppData\Roaming\Python\Python310\site-packages\langflow_backend>python main.py
INFO: Started server process [13420]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://127.0.0.1:5003 (Press CTRL+C to quit)

I click on the link and the page displays:
{"detail":"Not Found"}

**Comment by scott------** [comment]
switched to WSL and get 
import aiohttp
      ModuleNotFoundError: No module named 'aiohttp'

**Comment by whit3rabbit** [comment]
```
python -m langflow
```
works for me on windows

**Comment by scott------** [comment]
It works!!!!!

**Comment by rodrigosnader** [comment]
Can I close this issue @echohive42 ?

**Comment by echohive42** [comment]
Yes it works. Thank you very much!

**Comment by Sameedahmad** [comment]
Still getting the same error:

 import fcntl

ModuleNotFoundError: No module named 'fcntl'

**Comment by scott------** [comment]
I'm running on windows with no issues.
I launch with:
python -m langflow

**Comment by ogabrielluiz** [comment]
@Sameedahmad, have you upgraded it to version 0.0.40?

**Comment by scott------** [comment]
This is working for me on Windows with python 3.11.x

C:\Users\Scott>pip show langflow
Name: langflow
Version: 0.0.40
Summary: A Python package with a built-in web application
Home-page:
Author: Logspace
Author-email: contact@logspace.ai
License: MIT
Location: C:\Users\Scott\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: beautifulsoup4, fastapi, google-api-python-client, google-search-results, gunicorn, langchain, openai, typer, uvicorn
Required-by:

C:\Users\Scott>
