### ISSUE TITLE
Random refresh that causes loss of all flows/tabs

### ISSUE THREAD

**Issue by tnsai** [logspace-ai/langflow#398]
**The following error randomly occurs while working on the example PDF flow. The flow works with no errors and can carry out a chat but randomly refreshes and all data is lost in the flows.**  

_Edit: Same error reoccured at 2023-05-29 21:36:23.372 BST_

Edit 2: Same issue after pulling latest changes

> textPayload: "Traceback (most recent call last):
>   File "/app/src/backend/langflow/api/chat_manager.py", line 165, in handle_websocket
>     json_payload = await websocket.receive_json()
>   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 133, in receive_json
>     self._raise_on_disconnect(message)
>   File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
>     raise WebSocketDisconnect(message["code"])
> starlette.websockets.WebSocketDisconnect: 1001"
> timestamp: "2023-05-29T20:26:16.282996Z"
> 
> During handling of the above exception, another exception occurred:
> 2023-05-29 21:26:16.283 BST
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 238, in run_asgi result = await self.app(self.scope, self.asgi_receive, self.asgi_send) File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__ return await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__ await super().__call__(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__ await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__ raise exc File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__ raise e File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app await func(session) File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app await dependant.call(**values) File "/app/src/backend/langflow/api/chat.py", line 20, in websocket_endpoint await chat_manager.handle_websocket(client_id, websocket) File "/app/src/backend/langflow/api/chat_manager.py", line 181, in handle_websocket await self.active_connections[client_id].close( File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 180, in close await self.send( File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 85, in send await self._send(message) File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in sender await send(message) File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 329, in asgi_send raise RuntimeError(msg % message_type) RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
> 
> 

Tested in Chrome latest version as of today.

**Comment by tnsai** [comment]
So I am unsure if it is directly related but even commenting out the hardRefresh function everywhere it still occurs - i.e its not caused by an error in the frontend?

**Comment by tnsai** [comment]
This went away when updating to commit 66e0950 but since that commit the issue has returned.

**Comment by ogabrielluiz** [comment]
Hey, @tnsai 

Could you update to the latest version? 

This seems to be an issue with backward compatibility for the examples. We'll update them ASAP but please try the latest version to see if this was fixed.

**Comment by tnsai** [comment]
Hey @ogabrielluiz Thanks for your reply! 

It's still happening with examples on the tabs, but do you think if I created a flow manually without using the examples the issue will stop occurring? 

I'm just checking if it occurs with a blank tab.

**Comment by ogabrielluiz** [comment]
It shouldn't happen. I'll try it out here to see how it goes.

**Comment by tnsai** [comment]
Hi, so the issue is only occurring on Google Cloud Run now, on the Frontend part of the project. After moving the frontend to Firebase the issue no longer occurs and does not occur locally.
