### ISSUE TITLE
Error: This model's maximum context length is 4097 tokens, however you requested 6735 tokens (6479 in your prompt; 256 for the completion).

### ISSUE THREAD

**Issue by ashmgdesign** [logspace-ai/langflow#399]
`  ERROR    [21:34:37] - ERROR - Error building node PyPDFLoader: Cannot read an empty file      validate.py:56
                    ┌─────────────────────── Traceback (most recent call last) ────────────────────────┐
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\graph\b │
                    │ ase.py:190 in _build                                                             │
                    │                                                                                  │
                    │   187 │   │   # and return the instance                                          │
                    │   188 │   │                                                                      │
                    │   189 │   │   try:                                                               │
                    │ > 190 │   │   │   self._built_object = loading.instantiate_class(                │
                    │   191 │   │   │   │   node_type=self.node_type,                                  │
                    │   192 │   │   │   │   base_type=self.base_type,                                  │
                    │   193 │   │   │   │   params=self.params,                                        │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\interfa │
                    │ ce\loading.py:41 in instantiate_class                                            │
                    │                                                                                  │
                    │    38 │   │   │   return custom_agent.initialize(**params)                       │
                    │    39 │                                                                          │
                    │    40 │   class_object = import_by_type(_type=base_type, name=node_type)         │
                    │ >  41 │   return instantiate_based_on_type(class_object, base_type, node_type, p │
                    │    42                                                                            │
                    │    43                                                                            │
                    │    44 def convert_params_to_sets(params):                                        │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\interfa │
                    │ ce\loading.py:67 in instantiate_based_on_type                                    │
                    │                                                                                  │
                    │    64 │   elif base_type == "vectorstores":                                      │
                    │    65 │   │   return instantiate_vectorstore(class_object, params)               │
                    │    66 │   elif base_type == "documentloaders":                                   │
                    │ >  67 │   │   return instantiate_documentloader(class_object, params)            │
                    │    68 │   elif base_type == "textsplitters":                                     │
                    │    69 │   │   return instantiate_textsplitter(class_object, params)              │
                    │    70 │   elif base_type == "utilities":                                         │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\interfa │
                    │ ce\loading.py:133 in instantiate_documentloader                                  │
                    │                                                                                  │
                    │   130                                                                            │
                    │   131                                                                            │
                    │   132 def instantiate_documentloader(class_object, params):                      │
                    │ > 133 │   return class_object(**params).load()                                   │
                    │   134                                                                            │
                    │   135                                                                            │
                    │   136 def instantiate_textsplitter(class_object, params):                        │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langchain\docume │
                    │ nt_loaders\pdf.py:114 in load                                                    │
                    │                                                                                  │
                    │   111 │                                                                          │
                    │   112 │   def load(self) -> List[Document]:                                      │
                    │   113 │   │   """Load given path as pages."""                                    │
                    │ > 114 │   │   return list(self.lazy_load())                                      │
                    │   115 │                                                                          │
                    │   116 │   def lazy_load(                                                         │
                    │   117 │   │   self,                                                              │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langchain\docume │
                    │ nt_loaders\pdf.py:121 in lazy_load                                               │
                    │                                                                                  │
                    │   118 │   ) -> Iterator[Document]:                                               │
                    │   119 │   │   """Lazy load given path as pages."""                               │
                    │   120 │   │   blob = Blob.from_path(self.file_path)                              │
                    │ > 121 │   │   yield from self.parser.parse(blob)                                 │
                    │   122                                                                            │
                    │   123                                                                            │
                    │   124 class PyPDFium2Loader(BasePDFLoader):                                      │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langchain\docume │
                    │ nt_loaders\base.py:87 in parse                                                   │
                    │                                                                                  │
                    │   84 │   │   Returns:                                                            │
                    │   85 │   │   │   List of documents                                               │
                    │   86 │   │   """                                                                 │
                    │ > 87 │   │   return list(self.lazy_parse(blob))                                  │
                    │   88                                                                             │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langchain\docume │
                    │ nt_loaders\parsers\pdf.py:17 in lazy_parse                                       │
                    │                                                                                  │
                    │    14 │   │   import pypdf                                                       │
                    │    15 │   │                                                                      │
                    │    16 │   │   with blob.as_bytes_io() as pdf_file_obj:                           │
                    │ >  17 │   │   │   pdf_reader = pypdf.PdfReader(pdf_file_obj)                     │
                    │    18 │   │   │   yield from [                                                   │
                    │    19 │   │   │   │   Document(                                                  │
                    │    20 │   │   │   │   │   page_content=page.extract_text(),                      │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\pypdf\_reader.py │
                    │ :322 in __init__                                                                 │
                    │                                                                                  │
                    │    319 │   │   if isinstance(stream, (str, Path)):                               │
                    │    320 │   │   │   with open(stream, "rb") as fh:                                │
                    │    321 │   │   │   │   stream = BytesIO(fh.read())                               │
                    │ >  322 │   │   self.read(stream)                                                 │
                    │    323 │   │   self.stream = stream                                              │
                    │    324 │   │                                                                     │
                    │    325 │   │   self._override_encryption = False                                 │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\pypdf\_reader.py │
                    │ :1509 in read                                                                    │
                    │                                                                                  │
                    │   1506 │   │   return self.cache_indirect_object(generation, idnum, obj)         │
                    │   1507 │                                                                         │
                    │   1508 │   def read(self, stream: StreamType) -> None:                           │
                    │ > 1509 │   │   self._basic_validation(stream)                                    │
                    │   1510 │   │   self._find_eof_marker(stream)                                     │
                    │   1511 │   │   startxref = self._find_startxref_pos(stream)                      │
                    │   1512                                                                           │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\pypdf\_reader.py │
                    │ :1554 in _basic_validation                                                       │
                    │                                                                                  │
                    │   1551 │   │   except UnicodeDecodeError:                                        │
                    │   1552 │   │   │   raise UnsupportedOperation("cannot read header")              │
                    │   1553 │   │   if header_byte == b"":                                            │
                    │ > 1554 │   │   │   raise EmptyFileError("Cannot read an empty file")             │
                    │   1555 │   │   elif header_byte != b"%PDF-":                                     │
                    │   1556 │   │   │   if self.strict:                                               │
                    │   1557 │   │   │   │   raise PdfReadError(                                       │
                    └──────────────────────────────────────────────────────────────────────────────────┘
                    EmptyFileError: Cannot read an empty file

                    The above exception was the direct cause of the following exception:

                    ┌─────────────────────── Traceback (most recent call last) ────────────────────────┐
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\api\val │
                    │ idate.py:53 in post_validate_node                                                │
                    │                                                                                  │
                    │   50 │   │   if node is None:                                                    │
                    │   51 │   │   │   raise ValueError(f"Node {node_id} not found")                   │
                    │   52 │   │   if not isinstance(node, VectorStoreNode):                           │
                    │ > 53 │   │   │   node.build()                                                    │
                    │   54 │   │   return json.dumps({"valid": True, "params": str(node._built_object_ │
                    │   55 │   except Exception as e:                                                  │
                    │   56 │   │   logger.exception(e)                                                 │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\graph\b │
                    │ ase.py:207 in build                                                              │
                    │                                                                                  │
                    │   204 │                                                                          │
                    │   205 │   def build(self, force: bool = False) -> Any:                           │
                    │   206 │   │   if not self._built or force:                                       │
                    │ > 207 │   │   │   self._build()                                                  │
                    │   208 │   │                                                                      │
                    │   209 │   │   #! Deepcopy is breaking for vectorstores                           │
                    │   210 │   │   if self.base_type in [                                             │
                    │                                                                                  │
                    │ C:\Users\ashbu\miniconda3\envs\langflowcvenv7\Lib\site-packages\langflow\graph\b │
                    │ ase.py:196 in _build                                                             │
                    │                                                                                  │
                    │   193 │   │   │   │   params=self.params,                                        │
                    │   194 │   │   │   )                                                              │
                    │   195 │   │   except Exception as exc:                                           │
                    │ > 196 │   │   │   raise ValueError(                                              │
                    │   197 │   │   │   │   f"Error building node {self.node_type}: {str(exc)}"        │
                    │   198 │   │   │   ) from exc                                                     │
                    │   199                                                                            │
                    └──────────────────────────────────────────────────────────────────────────────────┘
                    ValueError: Error building node PyPDFLoader: Cannot read an empty file`
                 
   `   ValueError: Error: This model's maximum context length is 4097 tokens, however
                    you requested 6735 tokens (6479 in your prompt; 256 for the completion). Please
                    reduce your prompt; or completion length.`

**Comment by tnsai** [comment]
EmptyFileError: Cannot read an empty file 

The loader is detecting an empty file, try using a different file.

**Comment by rodrigosnader** [comment]
If you're using a character text splitter, try to reduce the chunk size.
