### ISSUE TITLE
Langflow installation failed

### ISSUE THREAD

**Issue by SandeepPasula898** [logspace-ai/langflow#406]
Hello,
I am trying to install langflow with pip command in my windows 11. getting below error 

ImportError: cannot import name 'formatargspec' from 'inspect' 
[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Any solution for this?

**Comment by anovazzi1** [comment]
Did you check your Python version? try python 3.10 or Python 3.11

**Comment by SandeepPasula898** [comment]
@anovazzi1 Yeah I did with 3.11

**Comment by Cristhianzl** [comment]
Hi there! I hope you're doing well. I noticed you were facing some difficulties with the installation process on Windows. No worries! I encountered a similar issue before, but I managed to resolve it by following these steps:

- First, I installed Anaconda Prompt on my system.
- Then, I created a virtual environment by running the command "conda create --name NAME_OF_ENV" in the Anaconda Prompt.
- To activate the virtual environment, I used the command "conda activate NAME_OF_ENV".
- Once the virtual environment was active, I installed the latest version of Python within it.
- Next, I installed the "langflow" package on the environment.
- It's essential to ensure that you have the latest version of Node installed on your Windows system. In my case, I'm using version 18.14.2.

If you have any other versions of Node installed on your computer, I recommend using NVM (Node Version Manager) for effective version management.

I hope these steps help you overcome the installation issue you encountered. If you have any further questions or need additional assistance, please feel free to ask. Best regards!

**Comment by Battletrance1st** [comment]
can you try conda?, i install previuous version & get that error

**Comment by saiprasadphadke** [comment]
I am having an Issue installing Langflow on the Mac. I have a virtual env working with local Python version 3.10
![Screenshot 2024-05-22 at 4 06 18 PM](https://github.com/langflow-ai/langflow/assets/136454916/76641371-7083-45c2-b4a3-56b1c4e41eeb)
