### ISSUE TITLE
Integrating VertexAI / Google LLMs

### ISSUE THREAD

**Issue by mamigot** [logspace-ai/langflow#416]
Should integrate the VertexAI / Google Cloud Platform LLMs (already on LangChain) such as:

https://github.com/hwchase17/langchain/blob/master/langchain/llms/vertexai.py#L72

**Comment by mamigot** [comment]
https://github.com/logspace-ai/langflow/issues/419 will be relevant as well in order to close this issue

**Comment by ogabrielluiz** [comment]
I'll see if I can get my hands on it. I'm having trouble getting LangChain to recognize the credentials.

**Comment by mamigot** [comment]
Sounds good, and the credentials for which part? Happy to help

**Comment by ogabrielluiz** [comment]
I added the node, but running the `gcloud set project ...` didn't make the langchain class recognize the credentials for some reason.

**Comment by TMRolle** [comment]
> I added the node, but running the `gcloud set project ...` didn't make the langchain class recognize the credentials for some reason.

I have noticed some issues with the langchain integration picking up ADC (specifically the default Project ID) which seem to be resolved by running `aiplatform.init(project=PROJECT_ID_HERE)`. Maybe try that?

**Comment by cachatj** [comment]
wondering if/when we maybe able to expect any progress here in using GCP VertexAI LLM models and services within LangFlow, like we already can in LangChain?

**Comment by TMRolle** [comment]
I'm happy to assist from the Google side. I'm a backend troll and can't typescript to save my life, but I'm very familiar with our API platform/auth/etc and the python client libraries side of things. @ogabrielluiz or anyone else familiar with the frontend/langflow codebase side of the house, let me know if you want to set up a pair troubleshooting session to get that auth issue knocked out real quick (or just direct me to the relevant code, whatever's easiest)

**Comment by ogabrielluiz** [comment]
Hey @TMRolle.
I've created a PR (#555) end added the Component to it. You should be able to drop it in the canvas and (try to) run it. 

Should I set up a function to run google.auth before instantiating it?
