### ISSUE TITLE
getting langflow running on Windows

### ISSUE THREAD

**Issue by scott------** [logspace-ai/langflow#42]
### Discussed in https://github.com/logspace-ai/langflow/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **scott------** March 18, 2023</sup>
after running pip install langflow and watching that complete successfully I try:  
C:\Users\Scott>langflow
'langflow' is not recognized as an internal or external command,
operable program or batch file.

I CD into the site-packages langflow_backend and run:
C:\Users\Scott>cd C:\Users\Scott\AppData\Roaming\Python\Python310\site-packages\langflow_backend

C:\Users\Scott\AppData\Roaming\Python\Python310\site-packages\langflow_backend>python main.py
INFO:     Started server process [13420]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5003 (Press CTRL+C to quit)

I click on the link and the page displays:
{"detail":"Not Found"}

What am I missing here :-)</div>

**Comment by whit3rabbit** [comment]
```
python -m langflow
```

**Comment by scott------** [comment]
Works!   :-)
