### ISSUE TITLE
Support for LocalAI

### ISSUE THREAD

**Issue by mudler** [logspace-ai/langflow#429]
[LocalAI](https://github.com/go-skynet/LocalAI) is a OpenAI drop-in API replacement with support for multiple model families to run LLMs on consumer-grade hardware, locally. As it is compatible with OpenAI, it just requires to set the base path as parameter in the OpenAI client, there is also an example with langchain-js and langchain-python in the LocalAI repository here: https://github.com/go-skynet/LocalAI/blob/577d36b5964ba0873b945f2ea00404ed52556408/examples/langchain/langchainjs-localai-example/src/index.mts#L7

**Comment by ogabrielluiz** [comment]
Hey, @mudler

We were discussing adding them this week but couldn't decide the approach because it seems the OpenAI node would suffice.

What do you think would be a good approach?

**Comment by aasmundkamphaug** [comment]
+1 on localAI, it would also make it posible to user local embeddings

**Comment by ogabrielluiz** [comment]
LocalAI is just a matter of changing the OpenAI API base. 
I'll add that option on the OpenAI embeddings too asap

**Comment by aasmundkamphaug** [comment]
thx. Can you also make so  that the model name field in OpenAI accepts free text also

**Comment by NewtonTrendy** [comment]
> thx. Can you also make so that the model name field in OpenAI accepts free text also

i've just posted this as an issue before researching this thread. +1 
(im new to posting issues)

**Comment by juliandreas** [comment]
If you don't think a proper integration is necessary (which would make things a lot clearer for users), can you at least add some documentation in the Lanchain.js docs on how to integrate LocalAI?
