### ISSUE TITLE
How does the NotionDirectoryLoader work?

### ISSUE THREAD

**Issue by yourgeekguy** [logspace-ai/langflow#436]
I've been trying to find details on how to use the NotionDirectoryLoader, but can't seem to figure it out. I've attached my flow i'm using so you can see what i've setup. In short, I'm using it like a Document type and passing that into a Text Splitter then into FAISS...etc.

[NotionLoader.json.zip](https://github.com/logspace-ai/langflow/files/11640468/NotionLoader.json.zip)

The specific error i'm receiving is:
Error building node FAISS: The source you provided did not load correctly or was empty.This may cause an error in the vectorstore.

I tried using ChromaDB instead and it got a similar error saying that the value was blank basically.

What am I missing? How can I use this to connect to my Notion. This could be incredibly valuable integration I think.

**Comment by queenvictoria** [comment]
Hey I've been doing the same thing though with Chroma and I notice a few things:
1. Using `docker-compose` I've been unsucessful. I use `poetry` and install `langflow` with `poetry add langflow && poetry install && langflow`
2. I use `langflow 0.0.87` not `0.0.88`. If I don't then `path` is missing from the UI. I did try switching `docker`s version to `0.0.87` but that still didn't show the path.
3. Sometimes the `VectorStoreInfo` panel shows the same message as you have above. Closing out and opening up again causes it to rethink it's life choices and starts co-operating.
4. If I load your one (after closing out) FAISS waits in `validating` in orange for about 10x longer (5 minutes?) whereas Chroma takes a little while and then goes green. This is with `0.0.87` and the `path` field in Notion available.
5. And of course you need your Notion database dump unzipped in the root folder and the directory name entered in the `path` field.
