### ISSUE TITLE
Blank page appears when accessing Langflow website

### ISSUE THREAD

**Issue by liximi** [logspace-ai/langflow#441]
**Describe the bug**
Whenever I try to access the Langflow website, the page appears completely blank without any content.

**Browser and Version**
 - Browser [edge]
 - Version [113.0.1774.57]

**To Reproduce**
1. Use commond 'langflow'
2. Open the website http://127.0.0.1:7860/

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/37933467/4f4767e1-546a-48a9-a378-68698b57861f)

**Comment by liximi** [comment]
![image](https://github.com/logspace-ai/langflow/assets/37933467/fbf1b60f-614d-4afc-8ae2-449bedbac296)

**Comment by Godplayer** [comment]
Is there any solution for this ? This should not be closed

**Comment by froggomad** [comment]
Same issue on Chrome as stated by others:

>Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

When I look at the script tag, it does call out the type as module

**Comment by aselims** [comment]
Use python10 for installing and running. this would fix it all.
