### ISSUE TITLE
Add AutoGPT BabyAGI agents as well as TokenTextSplitter

### ISSUE THREAD

**Issue by anbangxu** [logspace-ai/langflow#445]
Could we add AutoGPT and BabyAGI agent to LangFlow? I notice these are available in Flowise
https://github.com/hwchase17/langchain/tree/master/langchain/experimental/autonomous_agents

Also, could we have other text splitter like TokenTextSplitter? I noticed that different splitters can impact search results a lot.

**Comment by queenvictoria** [comment]
If you read the [DEV article](https://blog.langchain.dev/agents-round/) you will see that LangChain can do a fairly good job of replicating those two functionalities while staying on campus. It is also a good round up of the differences and approaches and also points to langchain implementing novel approaches in some of these agents. 

I've not tried to implement them myself in LangFlow but I intend to try. 
The article
https://blog.langchain.dev/agents-round/

The workbook
https://python.langchain.com/en/latest/use_cases/autonomous_agents/autogpt.html
