### ISSUE TITLE
why is it always thinking?  failed with status code 500

### ISSUE THREAD

**Issue by Coerchan** [logspace-ai/langflow#446]
Request failed with status code 500
Error: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C02EBFB7F0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应
here is my simple structure
![image](https://github.com/logspace-ai/langflow/assets/37653747/09f6ee6a-b65a-40e6-b5de-be8f71758879)

**Comment by ogabrielluiz** [comment]
This seems related to OpenAI's API.
