### ISSUE TITLE
Semantic search of PDF with visual results

### ISSUE THREAD

**Issue by sandorkonya** [logspace-ai/langflow#453]
Hi there, i really like the concept of langflow!

I would really love to see the original pages of the pdf/pdfs where the vector search results are coming from.

The PDF loader in Langchain [stores the page as metadata](https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/pdf.py#LL98C14-L98C14), so i was thinking on having a tool that could use this metadata - that is also incuded in the results of a vector store search - to load the original pdfs from a local path with the corresponding page and put them on a canvas/iframe so one could inspec them. 
Like a semantic search functionality within the vector store. 

What do you think, is it feasable?
(can't label this as a feature request)

**Comment by ogabrielluiz** [comment]
Hey @sandorkonya 
It is definitely feasible and it is in our backlog. 
We have set up Images and now we need to define a good approach for any other kind of data. 

I'll keep you posted.

**Comment by rparrapy** [comment]
Hi, I have a similar use case, was this ever built? I am interested in having the chatbot return a reference to the page number.
