### ISSUE TITLE
LangFlow tools side bar is empty

### ISSUE THREAD

**Issue by angel1st** [logspace-ai/langflow#458]
**Describe the bug**
I cannot see Tools on the left side bar

**Browser and Version**
 - Google Chrome
 - Version 114.0.5735.110 (Official Build) (64-bit)

**To Reproduce**
1. Go to langflow main folder
2. type `docker-compose up`
3. Navigate to http://localhost:3000/
4. Home page doesn't have tools left side bar
5. Below is the log

**Screenshots**
LangFlow home page
![langflow-main](https://github.com/logspace-ai/langflow/assets/8547131/8fcf3621-295e-4dd7-87de-4e4b6f7ed780)

**Console log**
`Attaching to langflow-backend-1, langflow-frontend-1
langflow-backend-1   | INFO:     Will watch for changes in these directories: ['/app']
langflow-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
langflow-backend-1   | INFO:     Started reloader process [1] using WatchFiles
langflow-frontend-1  | 
langflow-frontend-1  | > langflow@0.1.2 dev:docker
langflow-frontend-1  | > vite --host 0.0.0.0      
langflow-frontend-1  | 
langflow-frontend-1  | 
langflow-frontend-1  |   VITE v4.3.5  ready in 357 ms       
langflow-frontend-1  | 
langflow-frontend-1  |   ➜  Local:   http://localhost:3000/ 
langflow-frontend-1  |   ➜  Network: http://172.22.0.3:3000/
langflow-backend-1   | INFO:     Started server process [8]
langflow-backend-1   | INFO:     Waiting for application startup.
langflow-backend-1   | INFO:     Application startup complete.   
langflow-backend-1   | INFO:     172.22.0.3:56180 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:56182 - "GET /version HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:56194 - "GET /version HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:56206 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:56210 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:56222 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:48442 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:48448 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:48464 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:43464 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:43470 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:55062 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:60828 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:36806 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:50782 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:48190 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:39098 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:44720 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:44722 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:44738 - "GET /version HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:44748 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:38046 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:38052 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:50942 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:50958 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:37882 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:47540 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:33140 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:54336 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:50818 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:34906 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:59696 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:51890 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:47990 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:45742 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:58574 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:38766 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:47346 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:51676 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:58142 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:58066 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:58082 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:56508 - "GET /all HTTP/1.1" 404 Not Found
langflow-backend-1   | INFO:     172.22.0.3:59432 - "GET /all HTTP/1.1" 404 Not Found`

**Comment by PepperYan** [comment]
It could be the mismatch between proxy config and backend route. check backend route in /docs, and proxy config in vite.config.ts

**Comment by PepperYan** [comment]
it is a mismatch with backend route. It should be /api/v1/all

**Comment by PepperYan** [comment]
> @PepperYan - how should I fix it?

I found the route prefix config not work in branch dev, so i edit the proxy config in vite.config.ts. but I'm not sure if it works in dockercompose. or u can fix the route prefix question

**Comment by ogabrielluiz** [comment]
Hey, I pushed a change to dev to fix this. Sorry for the inconvenience!
