### ISSUE TITLE
UI shows {"detail":"Not Found"}

### ISSUE THREAD

**Issue by bartanderson** [logspace-ai/langflow#466]
Did a clean build of langchain and langflow from source using python 3.10.11
I found this error that I fixed by creating the missing directory
image
![image](https://github.com/logspace-ai/langflow/assets/1667112/5e160197-9c37-4819-aca2-07598bb7ba23)

Then running I get this
image
![image](https://github.com/logspace-ai/langflow/assets/1667112/a18acca0-d580-4dfe-a14b-437e9a8ee2c0)

This is what I found in firefox
![image](https://github.com/logspace-ai/langflow/assets/1667112/79231131-a9bd-427d-90a8-011bd27c0c07)

This is just a guess/question in hopes of pointing better to the issue, since it has not been resolved with a couple of attempts previously
Could it at all be related to this? https://stackoverflow.com/questions/1321878/how-to-prevent-favicon-ico-requests#

**Comment by ogabrielluiz** [comment]
Hi @bartanderson 

Running LangFlow from source is a bit different.

Basically, in the repo root folder run:
`make backend` and on another terminal run `make frontend`, this will have you up and running.

If you want to debug the backend you'll need to run the debug config in vscode.

**Comment by bartanderson** [comment]
I'm not sure what you mean.
I build langchain and lang flow both (in their respective root directories)
with pip install -e .
And that worked for each of them.
Make does nothing for me. Are there some prerequisites I should know about?
Thanks,
Bart

**Comment by bartanderson** [comment]
Oh I figured out what you meant. I looked in the log file and it does cd
frontend and npm install
Did the same for backend
Thanks

**Comment by bartanderson** [comment]
I rebuilt. The missing folder is still not there but the messages are all different.
[langflow console 06092023.txt](https://github.com/logspace-ai/langflow/files/11711262/langflow.console.06092023.txt)
There is some extra stuff at the top but it show what happened after the last build and run

**Comment by bartanderson** [comment]
As I looked closer it seems that the directory not being there is the root problem. Is something wrong with the build script? What should be copied such that it appears in the directory that I didn't find anything in? You can use the first image above to see that issue.

**Comment by siscanu** [comment]
I have the same problem. in /flowise, when run "docker compose up -d" and open myserverip:7860 it shows {"detail":"Not Found"}

**Comment by siscanu** [comment]
> I have the same problem. in /flowise, when run "docker compose up -d" and open myserverip:7860 it shows {"detail":"Not Found"}

Does anyone have a solution?
