### ISSUE TITLE
Failed building wheel for llama-cpp-python

### ISSUE THREAD

**Issue by addy-12** [logspace-ai/langflow#478]
**Describe the bug**
Not able to run langflow properly because , it shows - "Building wheel for hnswlib (pyproject.toml) did not run successfully."

**Browser and Version**
 - Browser - Chrome
 - Version 114.0.5735.110

**To Reproduce**
1. In the command prompt - pip install langflow

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/109429916/1882e4af-a847-40cb-9d4a-844cf278f0a6)

**Comment by pleabargain** [comment]
same 
windows 10
python --version
Python 3.10.11

**Comment by pleabargain** [comment]
I installed the new VS studio build tools and which included a c++ lib. 

langflow installed.

**Comment by Easterlings** [comment]
same problem,you may look the second answer [here](https://stackoverflow.com/questions/73969269/)

**Comment by addy-12** [comment]
I installed the c++ library and i have python version - 3.11 
I think it runs only on Python 3.10 versions 
Any idea how do I install that

**Comment by chizheyu** [comment]
@Easterlings  how linux can install it ？

**Comment by fanfank** [comment]
Hi guys, seems this question is not about llama-python-cpp wheel building error, but I did encounter that problem and finally fix the problem on Mac 2018 Sonoma 14.0 Intel Chip, by:
1. update xcode to 15.0, update os version to Sonoma 14.0
2. restart
3. open xcode and let it download necessary components
4. exec the following command in the terminal `sudo xcode-select -s /Applications/Xcode.app`
5. then exec our `pip install langflow` command to check if the llama-python-cpp installing problem is resolved

By the way, I am using python 3.11 (pip 3.11), clang 15.0(before I exec the xcode-select command it's 11.x) to finish all these procedures.
