### ISSUE TITLE
text_splitter.py:126  Created a chunk of size  8892, which is longer than the specified 1000 causing context length error(?)

### ISSUE THREAD

**Issue by pleabargain** [logspace-ai/langflow#486]
**Describe the bug**
Trying to pass https://python.langchain.com/en/latest/reference.html to the baseURLloader. 
It failed. An error popped up for a second in the WEB UI but no error is found in Chrome browser console
In the python console I see
text_splitter.py:126  Created a chunk of size  8892, which is longer than the specified 1000

The langflow chat was cleared of all content. :(
Here is the error that showed up in the bottom left
```Error: This model's maximum context length is 4097 tokens, however you requested 4266 tokens (3266 in your prompt; 1000``` 
I increased the token size to 4000 and Langchain complained
``` Error: This model's maximum context length is 4097 tokens, however you requested 4329 tokens (329 in your prompt; 4000 f ```

**Browser and Version**
114.0.5735.110 (Official Build) (64-bit) (cohort: Stable) 

**To Reproduce**
load the attached template and try to get langflow to read https://python.langchain.com/en/latest/reference.html
change from txt to json

**Additional context**
I'm trying to get LangFlow to teach me about LangFlow. 

[Vector Store of https___python.langchain.com_en_latest_reference.html.txt](https://github.com/logspace-ai/langflow/files/11732841/Vector.Store.of.https___python.langchain.com_en_latest_reference.html.txt)

**Comment by RominaUQ** [comment]
I am facing similar issue as well.

**Comment by ogabrielluiz** [comment]
The problem here lies in the TextSplitter. Try changing the chunk_size or using different separators to see if you get better results.
