### ISSUE TITLE
Vertex PaLM support as LLM

### ISSUE THREAD

**Issue by kkrishnan90** [logspace-ai/langflow#491]
I would like to know if Google Cloud Vertex PaLM will be added to the LLMs section. Happy to contribute knowing where I should edit apart from Config.yml and create a PR.

**Comment by nacartwright** [comment]
I also am very interested in this and willing to help.

**Comment by cachatj** [comment]
wondering if/when we maybe able to expect any progress here in using GCP VertexAI LLM models and services within LangFlow, like we already can in LangChain?

**Comment by kkrishnan90** [comment]
Implemented this feature in the latest langflow. Thanks to @ogabrielluiz for his consistent support. I've tested this and it works except for chat models. It works both for text and codey models.
