### ISSUE TITLE
Not solved yet : This site can’t be reached. 127.0.0.1 refused to connect.

### ISSUE THREAD

**Issue by Thom-and** [logspace-ai/langflow#492]
**Describe the bug**
I set up Langflow for the first time, made some flows and closed it down. The next day, I tried to reopened the page by clicking the bookmark, but it didn't work and instead I got a message saying "This site can’t be reached. 127.0.0.1 refused to connect."

**Browser and Version**
 - Browser [Chrome]
 - Version [114.0.5735.111 ]

**To Reproduce**
1. Open 'Langflow"
2. Make some flows
3. Close it down
4. Try to reopen it

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/130009192/5e2e64a1-e271-4c6d-9ed3-38f8d8475bde)

**Additional context**
Until I closed it down, everything worked perfect. I loved the UI very much! It's a shame I couldn't reopen it....

**Comment by araujofrancisco** [comment]
How are you running it? executing langflow or using docker? either case you should go to http://127.0.0.1:7860 on browser.

**Comment by lucaseduoli** [comment]
If you turned off your computer, you need to reopen the LangFlow application via command line so that you can use it.

**Comment by Thom-and** [comment]
> How are you running it? executing langflow or using docker? either case you should go to http://127.0.0.1:7860 (when running from langflow, I think the port is 3000 for docker-compose) on browser.

Thank you so much for your advice. Yes. I went to http://127.0.0.1:7860/. As a matter of fact, I reintalled the whole Langflow, but it didn't work. Mmm....very strange....But I appreciate your help!

**Comment by Thom-and** [comment]
> If you turned off your computer, you need to reopen the LangFlow application via command line so that you can use it.

Thank you so much for your advice. I appreciate it. After I reinstalled the whole Langflow package, I did everything again. This time, I got this message, and I've been working on it for two hours but in vain. 

PicklingError: Can't pickle <cyfunction str_validator at 0x000001702AD31560>: it's not the same object as pydantic.validators.str_validator

**Comment by ogabrielluiz** [comment]
Hey, @Thom-and 
Could you try it again in version 0.1.3, please? There was an issue with running LangFlow on Windows.

**Comment by Thom-and** [comment]
> Hey, @Thom-and Could you try it again in version 0.1.3, please? There was an issue with running LangFlow on Windows.

Hi, Gabriel
I really appreciate your advice. I will try that as soon as I'm back to my PC. Thank you again! ❤

**Comment by tonyphoang** [comment]
I'm also getting the error on version 0.3.2. any tip?

**Comment by anovazzi1** [comment]
@tonyphoang did the new version fix it?
