### ISSUE TITLE
No dark mode in v0.2.0

### ISSUE THREAD

**Issue by robertZaufall** [logspace-ai/langflow#499]
Is the dark mode gone since 0.1.0?

![dark](https://github.com/logspace-ai/langflow/assets/18199228/2fe9e836-b17f-4924-9395-076921acc069)

Commit (https://github.com/logspace-ai/langflow/commit/109b071d6c8b66f814471cd5abcc645cc2031299)

![image](https://github.com/logspace-ai/langflow/assets/18199228/193add55-ae3e-43bb-b414-afa171acafbf)

**Comment by ogabrielluiz** [comment]
Hey, @robertZaufall 
We are refactoring the styles in frontend so we deactivated it. It will be added back in next week.

**Comment by Chunyfong** [comment]
@robertZaufall Turn this on to save your eyes at the moment :
https://github.com/darkreader/darkreader

**Comment by robertZaufall** [comment]
dark mode is gone again

![image](https://github.com/logspace-ai/langflow/assets/18199228/011b4fd1-0cc9-4a07-bbd6-5400d8e7fe12)

**Comment by robertZaufall** [comment]
it's working again

**Comment by calebebrim** [comment]
Still Gone?
