### ISSUE TITLE
Set backend URL independently of host and port 

### ISSUE THREAD

**Issue by Immortalin** [logspace-ai/langflow#50]
The backend URL string is [currently inferred from port and host and set dynamically at startup](https://github.com/logspace-ai/langflow/blob/29cfdd3917fe4ed3ae1c495d8303b1bb6e9cef9f/src/backend/langflow/__main__.py#L25). This breaks server deployments in docker containers because the frontend uses a different url than what's exposed to the backend via Docker because of reverse proxies. 

Chrome gives the following error`<your langflow deployment domain> was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://0.0.0.0:8080/all'. This request has been blocked; the content must be served over HTTPS.`

**Comment by ogabrielluiz** [comment]
This is an error we encountered this weekend and we managed to fix it for a certain use case. We'll probably release a version today that tries to remedy that. 

This might fix the issue of deploying LangFlow as it is right now. Deploying frontend and backend separately will still require some more work.

**Comment by Immortalin** [comment]
@ogabrielluiz would you mind sharing your fix?

**Comment by ogabrielluiz** [comment]
> @ogabrielluiz would you mind sharing your fix?

It is released. Try upgrading LangFlow.

Langflow cli now has host and port options. If it doesn't work as intended write back and we'll work on it right away. 

This is what allowed us to deploy LangFlow in HuggingFace Spaces so it should be working.

**Comment by Immortalin** [comment]
@ogabrielluiz tried two variations on fly.io and neither works:
```Docker
FROM python:3.11-slim-buster
RUN pip install langflow
# CMD [ "langflow", "--host", "0.0.0.0", "--port", "8080" ] # this one gives the "<your langflow deployment domain> was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://0.0.0.0:8080/all'. This request has been blocked; the content must be served over HTTPS" error
CMD [ "langflow", "--host", "<langflow-deployment-name>.fly.dev", "--port", "8080" ] # this one gives [521] [ERROR] Invalid address: ('<langflow-deployment-name>.fly.dev', 8080)
```

**Comment by ogabrielluiz** [comment]
I'm not familiar with fly.io but the setup seems close to HuggingFace Spaces. 

The HTTPS error is something I've encountered in Spaces but ever since we made the fronted not send requests to the backend url it stopped happening.
