### ISSUE TITLE
UI wont open due to javascript security error

### ISSUE THREAD

**Issue by erdooom** [logspace-ai/langflow#501]
**Describe the bug**
After installing and running on both local and Docker i get the same behavior of a blank white screen, my browser refuses to run the javascript of the site. I tried changing the permissions in my browser to specifically allow this address but nothing helped.

**Browser and Version**
 - Browser Chrome
 - Version 114.0.5735.134 (Official Build) (64-bit)

**To Reproduce**
1. I run langflow as per the instructions
3. Open the browser to http://127.0.0.1:7860/
4. All I see is a blank white screen
5. Open the dev console and see the following error:
" Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. "

**Screenshots**

**Additional context**

**Comment by alanmun** [comment]
Same problem.

**Comment by Gamekiller48** [comment]
This problem still exists.
https://github.com/logspace-ai/langflow/issues/353 seems related.
https://github.com/logspace-ai/langflow/issues/353#issuecomment-1809473376 and https://github.com/logspace-ai/langflow/issues/353#issuecomment-1775552569 mention possible solutions, however both haven't worked for me.

Fresh install via pip in a conda environment on windows x64, python 3.10.13.
The blank UI appears in Firefox 120.0.1 (various installed extensions), Microsoft Edge Version 112.0.1722.64 (no extensions) and Google Chrome Version 120.0.6099.71(no extensions).
