### ISSUE TITLE
AgentInitializer behave abnormal

### ISSUE THREAD

**Issue by westwind027** [logspace-ai/langflow#545]
**Describe the bug**
AgentInitializer behave abnormal

**Browser and Version**
 - Browser  Microsoft Edge
 - Version 114.0.1823.58

**To Reproduce**
Just reproduc https://logspace-ai.github.io/langflow/python-function 

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/9116046/7ec006a2-ef28-4d0a-a7fd-c43292a23399)
![image](https://github.com/logspace-ai/langflow/assets/9116046/5e98d0d1-cc01-404f-aacc-8069d6d1a79c)

**Comment by ogabrielluiz** [comment]
Hey, @westwind027 

We've just pushed version 0.2.2 that fixes that issue.

**Comment by westwind027** [comment]
Thx!
