### ISSUE TITLE
CSVAgent error - 'df_head' (type=value_error)

### ISSUE THREAD

**Issue by anbangxu** [logspace-ai/langflow#557]
**Describe the bug**
Try out a simple example of CSVAgent with a simple CSV file, but got this error.

Error building node CSVAgent: 1 validation error for PromptTemplate __root__ Invalid prompt schema; check for mismatched or missing input parameters. 'df_head' (type=value_error)

**Browser and Version**
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: v0.2.2

**To Reproduce**
See the CSV file

[csv_example.csv](https://github.com/logspace-ai/langflow/files/11888478/csv_example.csv)

**Screenshots**
<img width="1116" alt="Screen Shot 2023-06-27 at 6 07 45 PM" src="https://github.com/logspace-ai/langflow/assets/6962174/00b7ab37-9330-4066-87b4-00bdde1335a9">

**Additional context**
I also tried a CSV file without header, but still the same error.

**Comment by halil-cosdu-bear** [comment]
getting same error any solution?

**Comment by halil-cosdu-bear** [comment]
@ogabrielluiz Can you help?

**Comment by ogabrielluiz** [comment]
That is almost certainly a bug. I'll have to investigate

**Comment by halil-cosdu-bear** [comment]
> That is almost certainly a bug. I'll have to investigate

Thank you very much for asist. @ogabrielluiz

**Comment by halil-cosdu-bear** [comment]
Any news @ogabrielluiz ? Thanks.

**Comment by EchoSilo** [comment]
I am having this issue/error as well. Works in Flowise but not in Langflow.

**Comment by aikiwi** [comment]
I encountered the same problem.
