### ISSUE TITLE
how to save time of building Vector stores ?

### ISSUE THREAD

**Issue by ZyhHelen** [logspace-ai/langflow#558]
**Describe the bug**
it takes a long time to build vector store，is there any way to save time ？

**Browser and Version**
chrome

**To Reproduce**

**Screenshots**
see the following flow:
![image](https://github.com/logspace-ai/langflow/assets/17507454/e680b802-add9-42bd-a649-17425d406882)

**Additional context**
file info :  40K deck.txt
![image](https://github.com/logspace-ai/langflow/assets/17507454/421b0a7d-2ba9-4b8a-af7b-c10b6dd3d124)

time takes to build vector store
![image](https://github.com/logspace-ai/langflow/assets/17507454/3c7b8298-7ac5-43e3-a71e-d05f2bca9c07)

ps. embedding model has been pre downloaded
![image](https://github.com/logspace-ai/langflow/assets/17507454/253e7252-b668-4a74-aa3d-9534e2731efd)

**Comment by patelmilanun** [comment]
@ZyhHelen have u found any solution to just retrieve data from the store and not actually insert it every time you compile.
