### ISSUE TITLE
Langflow and OpenAI : Not answering questions out of document(pdf file).

### ISSUE THREAD

**Issue by iamashutoshmisra** [logspace-ai/langflow#585]
I am using OpenAI and Langflow and created a sample example where I'm using PDFLoader and a pdf file is provided as document.  

If I ask questions according to this document, it is returning relevant answers, but if I want to ask a question which is out of this document, it responses 'I don't know' or something like that.
How can I implement it in such a way, where it uses the document for every question, but if it cant find relevant answer for it in the document provided, it should take a look in its own knowledge base.

**Comment by ogabrielluiz** [comment]
Hi! 

This happens because, depending on the component you are using, the Prompt used by default tells the model to say it doesn't know if the question is not related. 
We are considering exposing those Prompts so that it is easier to customize and understand them.
