### ISSUE TITLE
Error/Crash running on macOS Apple M1 

### ISSUE THREAD

**Issue by mozg31337** [logspace-ai/langflow#598]
**Describe the bug**
MacOS Ventura 13.4.1. Installed langflow via conda with pip install langflow using python 3.10.9. Also tried with python 3.11.3. Langflow starts, but when using a simple Conversation chat with openai chatgpt 3.5turbo and 4 the langflow crashes with the following error:

objc[89818]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[89818]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

Browsers: Chrome and Safari

**Comment by hrz394943230** [comment]
same problem with Apple M2

**Comment by ZorroII** [comment]
same here

**Comment by smbzhang** [comment]
same here

**Comment by anhelus7** [comment]
same

**Comment by burnz0** [comment]
export DISABLE_SPRING=true should fix it for now

**Comment by philippjbauer** [comment]
Same problem here, with v0.2.7 and v0.3.0

@burnz0 running `export DISABLE_SPRING=true` before `langflow` hasn't helped me unfortunately

**Comment by ogabrielluiz** [comment]
`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` this seems to be another fix for this.

**Comment by philippjbauer** [comment]
@ogabrielluiz This does help running it. I'm not sure if it is also the cause for duplicated output on the command line and seemingly parallel calls to the LocalAI API I'm using ...

**Comment by ogabrielluiz** [comment]
I'll see if I can test this today. I have a M1 Mac too.

**Comment by Yuchen-Cao** [comment]
same error on macOS Intel

**Comment by toanmx0101** [comment]
same here

**Comment by anovazzi1** [comment]
still broken in the current version? @mozg31337  @toanmx0101  @Yuchen-Cao ?

**Comment by toanmx0101** [comment]
I set the value `DISABLE_SPRING=true` and it works well now.
