### ISSUE TITLE
Does this have LangchainJS support?

### ISSUE THREAD

**Issue by linonetwo** [logspace-ai/langflow#61]
I've created a localized https://github.com/linonetwo/langchain-alpaca based on langchain-js

Can I use it inside langflow?

**Comment by ogabrielluiz** [comment]
We have not tested langchain-js.

It might be useful to implement it later on but there are no plans just yet. 

I'll take a look at it to see how hard would it be.

**Comment by linonetwo** [comment]
Can you explain how you load py modules? So I can take a look how to add TS support.

**Comment by anovazzi1** [comment]
we have plans for a doc site, but for now, all our objects reflect langchain objects and the front-end renders it only. Our python modules filter it and adjust for the flow rendering. There is just some documentation in the comments inside the code for now.

**Comment by ogabrielluiz** [comment]
@linonetwo we plan on improving the code that parses the graph but the main thing @anovazzi1 might be able to help, I think, is on the output of the react-flow canvas.

The data structure that goes to the backend is what defines the structure of the code.
In the tests folder you can take a look at one or you could simply Export the flow you've built. That structure is what the backend parses to build each LangChain object. An algorithm for that is in the loading.py module in the backend but it still in development.

**Comment by msikora78** [comment]
Another huge +1 for langchain-js as well!

**Comment by JBX028** [comment]
One more +1 for the integration with langchainjs

**Comment by ogabrielluiz** [comment]
For us to have that implemented we need to finish the algorithm that puts LangFlow a lot closer to what LangChain is. 
I'm planning the steps as I write this to get us to the point where we can more easily integrate langchainjs.

Thanks for the feedback on this matter! This helps us a lot in prioritizing the tasks.

**Comment by linonetwo** [comment]
> We were looking for similar drag&drop UI for LangchainJS support as well, ended up creating one written in JS/TS: https://github.com/FlowiseAI/Flowise with the ability to import and use your localized module

What is the difference with langflow?
