### ISSUE TITLE
Executing Flows

### ISSUE THREAD

**Issue by benman1** [logspace-ai/langflow#625]
Hey,
This is a great tool, it's very enjoyable to drag these blocks around and see what's available and how they fit together. Well done! 

The installation took quite long with pip, I was a bit worried at first, but it's nice to see that the environment in conda is only about 1.7gb, again: that's cool!

There are a few things that are a bit annoying, though, which are related to execution. In the video you can see a chat, where you can run the flows - I couldn't find the chat. The API calls (again: very cool how they show up in the interface, and you only have to copy them to the terminal) give the same errors even after changing the flow or totally removing the element that was causing an error. There seems to be a problem with saving an updated flow.

**Comment by anovazzi1** [comment]
Thank you for the feedback. Could you kindly provide more detailed instructions on how to reproduce the bug you are referring to? Your assistance is greatly appreciated.
