### ISSUE TITLE
CSVLoader Bug

### ISSUE THREAD

**Issue by westwind027** [logspace-ai/langflow#629]
**Describe the bug**
CSVLoader Bug -- raw file which contain metadata, there is no need to input metadata information， and I don't know the format the metadata to input , which loader return a list .

**Browser and Version**
 - Browser Edge
 - Version 114.0.1823.67

**To Reproduce**
1, Fork Community Examples - CSV Loader
2. Use data from https://media.githubusercontent.com/media/datablist/sample-csv-files/main/files/organizations/organizations-100.csv
3. run and report error

**Screenshots**
<img width="1352" alt="image" src="https://github.com/logspace-ai/langflow/assets/9116046/9f6c595d-574e-47b4-aec4-7199717cf8f4">

<img width="1876" alt="image" src="https://github.com/logspace-ai/langflow/assets/9116046/8a5c1b00-13fc-47c0-8cdd-f84c6c6ffee0">

<img width="834" alt="image" src="https://github.com/logspace-ai/langflow/assets/9116046/0ec1dc25-90a0-4fd3-a0fe-2072dc76a4dd">

**Additional context**

**Comment by westwind027** [comment]
I use the version 0.2.2

**Comment by anovazzi1** [comment]
Hey @westwind027, is the error still occurring in the latest version?
