### ISSUE TITLE
APIConnectionError

### ISSUE THREAD

**Issue by nathangary** [logspace-ai/langflow#635]
Hello, my region needs to use a vpn proxy to access openai. I can configure os.environ["http_proxy "] for me to access when I'm running native langchain locally. But this configuration doesn't seem to work in the langflow project. Could you please tell me how to configure it?
Errors are reported below.
Retrying langchain.llms.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
thanks.

**Comment by sunyuantao** [comment]
![image](https://github.com/logspace-ai/langflow/assets/4652371/a917554f-551d-420a-859b-a338be6ae72c)
The same problem, according to the configuration in the picture, it still doesn't work

**Comment by sunyuantao** [comment]
> Hello, my region needs to use a vpn proxy to access openai. I can configure os.environ["http_proxy "] for me to access when I'm running native langchain locally. But this configuration doesn't seem to work in the langflow project. Could you please tell me how to configure it? Errors are reported below. Retrying langchain.llms.openai.acompletion_with_retry.._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI. thanks.

Change OPENAI_API_BASE, and replace the official interface domain name _api.openai.com_ with **api.openai-proxy.com**
