### ISSUE TITLE
How do I fill the memory for an LLMChain?

### ISSUE THREAD

**Issue by classicrob** [logspace-ai/langflow#64]
I get how to connect the LLM and Prompt, but are there components memory?

**Comment by anovazzi1** [comment]
we are currently working on memories, we are just solving some bugs before adding them as a component

**Comment by ibiscp** [comment]
We are also waiting for a PR on LangChain to finish it.
https://github.com/hwchase17/langchain/pull/1905

**Comment by hunter-meloche** [comment]
Do you guys know if memory is supposed to cover every case for embeddings? I'm already using embeddings on LangChain itself.

**Comment by classicrob** [comment]
Okay @anovazzi1 / @ibiscp , thank you for the update! Would you please let me know if this is resolved?

I love what you're doing with the interface, it felt surprisingly intuitive. I love the drag-and-drop sidebar and the typed slots.

**Comment by ogabrielluiz** [comment]
@hunter-meloche each memory have a certain requirement so we'll need to test as many as we can but the goal is to make it as close as possible to langchain.

**Comment by hunter-meloche** [comment]
@ogabrielluiz I'm looking forward to it and I appreciate the work you all are doing. I'll take a look at the code and see if I'm able to to help.

**Comment by classicrob** [comment]
Also, if you're interested in productizing Langflow, I've worked on designs [for similar applications](https://robhaisfield.com/notes/guidedtrack) and would love to talk 😄 I'm very much on the end-user programming train

**Comment by ogabrielluiz** [comment]
Hey, @classicrob 

Hit me up on twitter or LinkedIn. Sorry for the delayed response. Too much going on.

**Comment by Shrutikaaaaa** [comment]
Any idea on Invalid session id i am getting a error when i am creating a simple flow using pypdfloader

**Comment by ogabrielluiz** [comment]
Hey, this might not be related to this issue. Please, open a new one or post your question on our [discord server](https://discord.gg/FrGaYpEf).
