### ISSUE TITLE
i want to put multiple web page in webbased loder in langflow

### ISSUE THREAD

**Issue by kunal923476** [logspace-ai/langflow#649]
can anyknow how to do this 
i want to put multiple web page in webbased lower in langflow

**Comment by ogabrielluiz** [comment]
I just got multiple WebBaseLoaders to connect to a TextSplitter on a dev version. We'll define a good way to implement this but it should be very soon.

**Comment by kunal923476** [comment]
i have already connected  WebBaseLoaders to TextSplitter in langflow mapping need to Load multiple urls concurrently 
 i have checked for one urls it is working fine but i need to implement for 2 or more urls load in WebBaseLoaders

**Comment by kunal923476** [comment]
how to implement in langflow mapping for 2 or more than page of urls , can you please help me

**Comment by ogabrielluiz** [comment]
That functionality is not available yet. We'll implement it in our next minor release
