### ISSUE TITLE
[enhancement] move unnecessary dependencies to extra-deps or optoinal

### ISSUE THREAD

**Issue by liunux4odoo** [logspace-ai/langflow#662]
langflow is an excellent project, it support so many tools as to bring so many dependencies. It will be more effective to keep necessary dependencies only and move other unnecessary libraries to extra-deps or optional, what means user can install libraries as needed. 
below are libraries I think should be optional, skip them if mistake.

- google-search-results
- google-api-python-client
- chromadb
- huggingface-hub
- llama-cpp-python
- pypdf
- wikipedia
- pymongo 
- faiss-cpu
- google-cloud-aiplatform
- psycopg
- psycopg-binary

**Comment by ogabrielluiz** [comment]
I agree completely. We'll push something close to this soon but later we can add to it. #589
