### ISSUE TITLE
Custom Chat Fields and Chat History Storage

### ISSUE THREAD

**Issue by scooter7** [logspace-ai/langflow#667]
Hi,

If I wanted to require the user to provide name and email address before being allowed to ask questions, is that possible?

Also, is there a way to store chat histories by user session?

Thanks!

**Comment by ogabrielluiz** [comment]
Hey! In our latest version, we added the Postgres Chat Message History component that connects to a database and has a session id parameter which could be a hashed username+password+chat_id, for example.

If you use it like that you could potentially manage a user's history.

**Comment by scooter7** [comment]
Hi @ogabrielluiz !

Thanks for letting  me know!

From a user interface perspective, how could I require the user to enter name and email address?

I created this chatbot using streamlit, langchain, and some other tools at https://www.holyfamily.edu/admissions-aid (please click the rectangular blue icon to see the interface) that collects name and email before showing the user the input field to ask questions. 

I'm wondering if/how I could execute that same configuration with langflow.

Thanks again!

**Comment by ogabrielluiz** [comment]
In Langflow when calling from an API you'd set up inputs to set the tweaks for that component.
Something like: 
```python
TWEAKS =  {
    ...
    "PostgresChatMessageHistory-FooB4": {"session_id": HASHED_USER_DATA}
  }
```
Now, in the langflow interface, we don't expose that anywhere besides the component itself.
