### ISSUE TITLE
HTML endpoint

### ISSUE THREAD

**Issue by tonyphoang** [logspace-ai/langflow#671]
Hi all, is there a HTML endpoint (javascript injection) like in FlowiseAI?

**Comment by anovazzi1** [comment]
can you explain it better? i don't see any javascript injection in the FlowiseAI installation guide

**Comment by jjcampis** [comment]
you can copy the cURL path given in the code button </>.
then use that http url to make get / post request via axios, postman, thunder client in vscode or whatever you need :)

**Comment by evolu8** [comment]
I'm struggling to get the curl, chat client and python api to return anything. 

```Flow cbd39a2a-99b3-4b2b-85cb-2c100b89eb94 has no data```

**Comment by ogabrielluiz** [comment]
Have you saved your flow?
