### ISSUE TITLE
"Got a larger chunk overlap (200) than chunk size (1000), should be smaller."

### ISSUE THREAD

**Issue by piotrecode** [logspace-ai/langflow#672]
**Describe the bug**
I am encountering an error while using a text splitter. Despite setting the overlap value to be smaller than the chunk size, an error message is being thrown stating "Got a larger chunk overlap (200) than chunk size (1000), should be smaller."

**Browser and Version**
- Browser: 115.0.5790.102 (Official Build) (64-bit) Chrome
- PopOS

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/121666705/b82fec30-568c-4e47-a67e-cffef731fc75)

**Additional context**
I am using a text splitter to divide text into chunks. I have set the overlap value to be less than the chunk size, but the error still occurs. The error message seems to contradict the actual settings I have provided.

**Comment by DangJin** [comment]
Help, I also encountered this problem, have you solved it?

**Comment by Liuyis** [comment]
same problem, want fix!
