### ISSUE TITLE
Langflow Crashes without any error 

### ISSUE THREAD

**Issue by xavicolomer** [logspace-ai/langflow#678]
Langflow crashed with a simple PDF or Web flow, with no errors on Macbook Pro M1

![Screenshot 2023-07-24 at 11 48 36](https://github.com/logspace-ai/langflow/assets/1476272/9c6562b3-cedd-444b-b103-7cbc2a3593d4)

Command:

```langflow python -m langflow --dev --log-level info```

Output

```
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow                             │
│                                                   │
│ Access http://127.0.0.1:7860                      │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
INFO:     127.0.0.1:57591 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:57591 - "GET /api/v1/all HTTP/1.1" 200 OK
INFO:     127.0.0.1:57591 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:57591 - "GET /flow/8d613a83-bea1-4427-95a2-b1d62e9d8ead HTTP/1.1" 200 OK
INFO:     127.0.0.1:57591 - "GET /api/v1/version HTTP/1.1" 200 OK
INFO:     127.0.0.1:57592 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:57592 - "GET /api/v1/all HTTP/1.1" 200 OK
INFO:     127.0.0.1:57592 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:57592 - "GET /api/v1/build/8d613a83-bea1-4427-95a2-b1d62e9d8ead/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:57713 - "PATCH /api/v1/flows/8d613a83-bea1-4427-95a2-b1d62e9d8ead HTTP/1.1" 200 OK
INFO:     127.0.0.1:57713 - "POST /api/v1/build/init/8d613a83-bea1-4427-95a2-b1d62e9d8ead HTTP/1.1" 201 Created
INFO:     127.0.0.1:57713 - "GET /api/v1/build/stream/8d613a83-bea1-4427-95a2-b1d62e9d8ead HTTP/1.1" 200 OK
[11:44:01] INFO     [11:44:01] - INFO - Anonymized telemetry enabled. See                                  posthog.py:16
                    https://docs.trychroma.com/telemetry for more information.
           INFO     [11:44:01] - INFO - Successfully imported ClickHouse Connect C data optimizations       ctypes.py:22
           INFO     [11:44:01] - INFO - Using orjson library for writing JSON byte strings               json_impl.py:45
(langflow) ➜  langflo
```

**Comment by ogabrielluiz** [comment]
Hey,

Could you try running it with `--log-level debug`?

**Comment by xavicolomer** [comment]
Hi @ogabrielluiz 

I did, this is the output:

`                    'type': 'VectorStoreInfo', 'list': False}, '_type': 'vectorstore_agent'}, 'description':
                    'Construct an agent from a Vector Store.', 'base_classes': ['AgentExecutor'],
                    'display_name': 'VectorStoreAgent', 'custom_fields': {}, 'output_types': [],
                    'documentation': ''}, 'id': 'VectorStoreAgent-z9JbO', 'value': None})]
           DEBUG    [12:30:41] - DEBUG - Building PyPDFDirectoryLoader                                       base.py:129
[12:30:44] DEBUG    [12:30:44] - DEBUG - Building node PyPDFDirectoryLoader(77 documents)                    chat.py:128

                    Av...
           DEBUG    [12:30:44] - DEBUG - Building OpenAI                                                     base.py:129
           DEBUG    [12:30:44] - DEBUG - Building node Built sucessfully ✨                                  chat.py:128
           DEBUG    [12:30:44] - DEBUG - Building OpenAIEmbeddings                                           base.py:129
           DEBUG    [12:30:44] - DEBUG - Building node Built sucessfully ✨                                  chat.py:128
           DEBUG    [12:30:44] - DEBUG - Building Chroma                                                     base.py:129
           INFO     [12:30:44] - INFO - Anonymized telemetry enabled. See                                  posthog.py:16
                    https://docs.trychroma.com/telemetry for more information.
           INFO     [12:30:44] - INFO - Successfully imported ClickHouse Connect C data optimizations       ctypes.py:22
           DEBUG    [12:30:44] - DEBUG - Successfully import ClickHouse Connect C/Numpy optimizations       ctypes.py:31
           INFO     [12:30:44] - INFO - Using orjson library for writing JSON byte strings               json_impl.py:45
➜  langflow
➜  langflow
➜  langflow`

**Comment by grutty** [comment]
I'm also experiencing Langflow crashing with PDF flow on M1 Mac.

`MacBook-Pro-2:~ grutty$ python3 -m langflow --dev --log-level debug
[13:51:09] INFO     [13:51:09] - INFO - Logger set up with log level: 10(debug)                                            logger.py:28
           INFO     [13:51:09] - INFO - Log file: logs/langflow.log                                                        logger.py:30
INFO:     Started server process [91201]
INFO:     Waiting for application startup.
           DEBUG    [13:51:09] - DEBUG - Setting up LLM caching with SQLiteCache                                            utils.py:76
           INFO     [13:51:09] - INFO - LLM caching setup with SQLiteCache                                                  utils.py:78
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7860 (Press CTRL+C to quit)
INFO:     127.0.0.1:58321 - "GET /health HTTP/1.1" 200 OK
[13:51:10] DEBUG    [13:51:10] - DEBUG - HTTP Request: GET http://127.0.0.1:7860/health "HTTP/1.1 200 OK"               _client.py:1022
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ LangFlow                             │
│                                                   │
│ Access http://127.0.0.1:7860                      │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
INFO:     127.0.0.1:58322 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58322 - "GET /assets/index-baa2e6b2.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58322 - "GET /assets/index-59b24323.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58322 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:58322 - "GET /api/v1/all HTTP/1.1" 200 OK
INFO:     127.0.0.1:58322 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:58323 - "GET /health HTTP/1.1" 200 OK
`

**Comment by grutty** [comment]
I'm also experiencing Langflow crashing on M1 Mac with PDF flow.
```python


`MacBook-Pro-2:~ grutty$ python3 -m langflow --dev --log-level debug
[13:51:09] INFO     [13:51:09] - INFO - Logger set up with log level: 10(debug)                                            logger.py:28
           INFO     [13:51:09] - INFO - Log file: logs/langflow.log                                                        logger.py:30
INFO:     Started server process [91201]
INFO:     Waiting for application startup.
           DEBUG    [13:51:09] - DEBUG - Setting up LLM caching with SQLiteCache                                            utils.py:76
           INFO     [13:51:09] - INFO - LLM caching setup with SQLiteCache                                                  utils.py:78
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7860 (Press CTRL+C to quit)
INFO:     127.0.0.1:58321 - "GET /health HTTP/1.1" 200 OK
[13:51:10] DEBUG    [13:51:10] - DEBUG - HTTP Request: GET http://127.0.0.1:7860/health "HTTP/1.1 200 OK"               _client.py:1022
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ LangFlow                             │
│                                                   │
│ Access http://127.0.0.1:7860                      │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
INFO:     127.0.0.1:58322 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58322 - "GET /assets/index-baa2e6b2.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58322 - "GET /assets/index-59b24323.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:58322 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:58322 - "GET /api/v1/all HTTP/1.1" 200 OK
INFO:     127.0.0.1:58322 - "GET /api/v1/flows/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:58323 - "GET /health HTTP/1.1" 200 OK
`
```
