### ISSUE TITLE
Langflow occurs error when building Pinecone node 

### ISSUE THREAD

**Issue by toanmx0101** [logspace-ai/langflow#686]
**Describe the bug**
Error building node Pinecone: __init__() got an unexpected keyword argument 'pinecone_api_key'

```
ValueError: Error building node Pinecone: __init__() got an unexpected keyword argument 'pinecone_api_key'                                                                                      
ERROR    [09:31:59] - ERROR - Error while building the flow: Error building node Pinecone: __init__() got an unexpected keyword argument 'pinecone_api_key'                                   
```

**Browser and Version**
 - Browser [chrome]
 - Version [langflow v0.3.3, python 3.9.17]

**To Reproduce**
<img width="1127" alt="Screenshot 2023-07-26 at 09 33 58" src="https://github.com/logspace-ai/langflow/assets/25922489/7ba59849-50ae-4d52-8885-cc942b2e83e7">

<img width="687" alt="Screenshot 2023-07-26 at 09 47 00" src="https://github.com/logspace-ai/langflow/assets/25922489/74df2058-8435-4140-92be-ce68c93d8f61">

Command

```
python -m langflow --log-level debug
```

**Screenshots**
<img width="604" alt="Screenshot 2023-07-26 at 09 33 20" src="https://github.com/logspace-ai/langflow/assets/25922489/ea96128a-fc5c-4e0e-b7ea-f5771bfff494">

**Comment by LongRodSilver** [comment]
Did you solve it? I am encoutering the same error message on LangFlow?

**Comment by toanmx0101** [comment]
> Did you solve it? I am encoutering the same error message on LangFlow?

@LongRodSilver not yet. I just used Chroma instead of Pinecone.

**Comment by prek-prek** [comment]
Any solve for that? Im encountering the same issue

**Comment by toanmx0101** [comment]
@prek-prek
I think it was fixed on [newest Langflow version](https://github.com/logspace-ai/langflow/tree/v0.4.6). I tested this version on my local and it works.

**Comment by simonau123** [comment]
seems to be broken still

**Comment by Ayelaurencena** [comment]
still broken

**Comment by tmaian** [comment]
Same problem

**Comment by matthieubouilde** [comment]
Same error here too...
