### ISSUE TITLE
Sample SQL Database 

### ISSUE THREAD

**Issue by russokb** [logspace-ai/langflow#699]
trying to fork sample database example and in just loading before the display of the flow it says ..."Opps unknow error has occurred, reset application or create issue"  .....it also puts a message notice of   "SQL Node can't be rendered .....

Has anyone tried this DB example.....running  locally

**Comment by anovazzi1** [comment]
Appreciate the feedback! Could you let me know which operating system you're using? It would be really helpful if you could provide some additional details. I gave it a try on my end, and everything seems to be working fine.

**Comment by russokb** [comment]
I am using Windows 11

**Comment by anovazzi1** [comment]
@Cristhianzl can you try to reproduce the error please?

**Comment by Cristhianzl** [comment]
Hello @russokb,
I made an attempt to replicate the issue on my end, but I encountered no errors, which is puzzling. To troubleshoot further, could you consider clearing your browser's cache and also verifying your Python versions?

In my case, I'm utilizing Anaconda version 23.3.1 along with Python 3.10.9. Would it be possible for you to test running the application within this specific environment?

**Comment by russokb** [comment]
I just moved to Anaconda, so let me try this and get back to you.
