### ISSUE TITLE
Syntax error on WIndows11

### ISSUE THREAD

**Issue by swaticolab** [logspace-ai/langflow#707]
I want to use langflow from my local machine, for which I have used the command `pip install langflow`
The command executed successfully. BUt when I try to run langlow using the command `langflow`, it throws me the below error:
`File "<unknown>", line 1
    typing_extensions.['news', 'search', 'places', 'images']
                      ^
SyntaxError: invalid syntax`

Any leads on this will be helpful.

PS: I have created a completely new virtual env with below packages:
Python =3.10. 
langflow =  0.3.3

**Comment by dvmorris** [comment]
I am experiencing this issue as well, while trying to debug the langflow backend from VS Code on an M1 Mac. 

Python 3.9.6
langflow 0.4.0

Did you make any progress?
