### ISSUE TITLE
Feature Request: credentials support for Production 

### ISSUE THREAD

**Issue by leonvanzyl** [logspace-ai/langflow#708]
In order to be useful in Production, we need to ability to password protect our Langflow instances in Production / public domain.

**Comment by toanmx0101** [comment]
Agree 👍 , we need to protect the UI and API as well

**Comment by shuvocasanova** [comment]
Yes it's needed. We need to protect our deployment environment

**Comment by anovazzi1** [comment]
Thank you for the feedback! We're actively working on implementing this improvement, and you can expect it to be fully addressed in the upcoming release.
