### ISSUE TITLE
pip install langflow[local] gives: no matches found: langflow[local]

### ISSUE THREAD

**Issue by cahitakin19** [logspace-ai/langflow#714]
langflow installs fine, however, pip install langflow[local] results in "no matches found: langflow[local]"

I am on a m2 macbook air.

**Comment by ogabrielluiz** [comment]
Hey @cahitakin19

That's weird. I just ran it and it works. Could you try  `pip install "langflow[local]"` ?

**Comment by cahitakin19** [comment]
Yes, adding the quotations around langflow[local] did the trick! Thanks for the speedy response/resolution. Adding that extra information to the readme page might be a good idea.

**Comment by bjornslib** [comment]
Amazing, thank you from my end too!
