### ISSUE TITLE
PythonFunctionTool error

### ISSUE THREAD

**Issue by imJunaidAfzal** [logspace-ai/langflow#715]
I'm using pythonFunctionTool, ZeroshotAgent and Chat-LLM, but getting error as my function use poylon library and it is unable to find it. How can i install it and build a complete agent

### Error
![image](https://github.com/logspace-ai/langflow/assets/54235418/6a376b47-b22c-45b0-9d86-59515c774bc7)

### Flow
![image](https://github.com/logspace-ai/langflow/assets/54235418/33218a88-fa01-4cf4-864f-d61c28a10b5f)

### On running

```bash
> Entering new AgentExecutor chain...
I need to get the open-close aggregate information for Apple's stock for today's date.
Action: get_daily_open_close_agg_info(stock_symbol,_date)
Action Input: ("AAPL", "2022-01-01")
Observation: get_daily_open_close_agg_info(stock_symbol,_date) is not a valid tool, try another one.
Thought:I must have misunderstood the available tools. I'll try again.
Action: None.
Final Answer: I'm sorry, but I currently do not have the ability to fetch live stock prices. I suggest referring to a reliable financial news website or your stock trading platform for the current value of Apple's stock.

> Finished chain.
{'input': 'Current apple stock value',
 'output': "I'm sorry, but I currently do not have the ability to fetch live stock 
```

**Comment by ogabrielluiz** [comment]
If you plan on using a package that is not a dependency of Langflow's you should install it first (e.g  run `pip install polygon` on the same environment as Langflow)

**Comment by imJunaidAfzal** [comment]
@ogabrielluiz thanks for your help, I resolved it by running it locally, as I have everything installed on local, that was the issue on HF space,

**Comment by imJunaidAfzal** [comment]
I resolved it by running it locally, as I have everything installed on local, that was the issue on HF space,
