### ISSUE TITLE
Azure OpenAI setup with Langflow 0.4.0

### ISSUE THREAD

**Issue by aidin-zadeh** [logspace-ai/langflow#716]
Hey team, Incredible app. Could anyone please let me know if Langflow 0.4.0 supports the use of Azure OpenAI? I attempted to set the environment variables for Azure `OPENAI_API_TYPE=azure`, but unfortunately, it didn't work out. 

If anyone has detailed instructions on how to make it work, I'd greatly appreciate it! Thanks a bunch in advance! 😄

**Comment by yassineselmi** [comment]
I use the v0.4.19, and I was able to make it work as follows:

I used the component `ChatOpenAI`, and added the following json to the `model_kwargs1 attribute:

```json
{
    "engine": "<YOUR AZURE DEPLOYMENT NAME>",
    "api_version": "2023-05-15",
    "api_type": "azure"
}
```


In addition, I set the `openai_api_base` attribute as `https://YOUR_AZURE_RESOURCE_NAME.openai.azure.com/`.
