### ISSUE TITLE
Multiline WebBaseLoader

### ISSUE THREAD

**Issue by youzhou-youpi** [logspace-ai/langflow#719]
I am trying to load multiple webpages and it works with multiple WebBaseLoader. However, it would be much more convenient if one WebBaseLoader can accept an array of URLs.

I don't find a way to do it on UI, but I found a "multiline" param in the generated JSON file. Is that related? If the UI is not ready for such use case, could I just modify the JSON? Thanks 

      {
        "width": 384,
        "height": 379,
        "id": "WebBaseLoader-u3VOm",
        "type": "genericNode",
        "position": { "x": 60.14567996902622, "y": 402.15940661142673 },
        "data": {
          "type": "WebBaseLoader",
          "node": {
            "template": {
              "metadata": {
                "required": true,
                "placeholder": "",
                "show": true,
                "multiline": false,
                "value": "{}",
                "password": false,
                "name": "metadata",
                "display_name": "Metadata",
                "advanced": false,
                "dynamic": false,
                "info": "",
                "type": "code",
                "list": false
              },
              "web_path": {
                "required": true,
                "placeholder": "",
                "show": true,
                "multiline": false,
                "value": "https://python.langchain.com/docs/integrations/memory/",
                "password": false,
                "name": "web_path",
                "display_name": "Web Page",
                "advanced": false,
                "dynamic": false,
                "info": "",
                "type": "str",
                "list": false
              },
              "_type": "WebBaseLoader"
            },
            "description": "Loader that uses urllib and beautiful soup to load webpages.",
            "base_classes": ["Document"],
            "display_name": "WebBaseLoader",
            "custom_fields": {},
            "output_types": ["Document"],
            "documentation": "https://python.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_base",
            "beta": false,
            "error": null
          },
          "id": "WebBaseLoader-u3VOm",
          "value": null
        },
        "selected": false,
        "positionAbsolute": { "x": 60.14567996902622, "y": 402.15940661142673 },
        "dragging": false
      }
    ],

**Comment by youzhou-youpi** [comment]
Anyone can take a look at this?

**Comment by anovazzi1** [comment]
Appreciate the feedback! We're eager to incorporate this improvement. In the meantime, I wanted to ask if you've explored utilizing custom components?

**Comment by youzhou-youpi** [comment]
Not yet. I created 30 `WebBaseLoader` instead. Took a while to do that :P
