### ISSUE TITLE
You cannot use custom model names in the ChatOpenAI LLM Widget

### ISSUE THREAD

**Issue by NewtonTrendy** [logspace-ai/langflow#720]
This means you can't use lmsys/fastchat or custom openai endpoint to host a custom openAI endpoint without renaming the llms after openai llms.

**Comment by NewtonTrendy** [comment]
Upon looking deeper i found there is also an OpenAI widget where you can input the model name, I'm not sure if LocalAI and Fastchat support chat but maybe they will.

**Comment by anovazzi1** [comment]
Thanks for the feedback! Have you ever given custom components a shot? I've got a feeling they might be a great fit for your situation

**Comment by juztim** [comment]
this would be amazing to have, please reopen

**Comment by maxpaynebupt** [comment]
this is very useful, as we finetuned a model, and now we can not just define and use it in langflow...

**Comment by abdullahalzubaer** [comment]
It will be super if we can have this ! Thank you.
