### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT when automatically pulling from huggingface hub 

### ISSUE THREAD

**Issue by evolu8** [logspace-ai/langflow#722]
**Describe the bug**
[CRITICAL] WORKER TIMEOUT when automatically pulling from huggingface hub. 

**Browser and Version**
 - Chrme
 - Version 115.0.5790.114 (Official Build) (x86_64)

**To Reproduce**
1. Go to cTransformers LLM
2. give model but not the model file value
3. build a flow to use the model

**Screenshots**
<img width="1676" alt="image" src="https://github.com/logspace-ai/langflow/assets/1828165/f50fe0a0-a0bf-41e0-b400-073853a0532f">

**Additional context**
Would be so helpful to allow auto fetch via transformers. LangFlow is an amazing tool already for fast prototyping of LLM solutions. This would make it even more so.

**Comment by ogabrielluiz** [comment]
Hey @evolu8

The CLI has a `timeout` option that sets the worker timeout in Gunicorn. Have you tried changing it to support longer downloads?

Improving that experience is one of our goals but we haven't designed a good experience around that yet.

**Comment by evolu8** [comment]
I'd missed that. Thank you for the response! I've thoroughly enjoyed spending a weekend getting to know many models and how to chain them effectively. Very valuable work. I'll give the CLI option a spin and see what happens.
