### ISSUE TITLE
Extend with custom components

### ISSUE THREAD

**Issue by chris-boson** [logspace-ai/langflow#73]
Is there a way to import custom LangChain components (tools, chains, agents, etc.)? The current selection is very limited and doesn't seem to keep up with what's already in the core LangChain library.

**Comment by ogabrielluiz** [comment]
We are working on that.

Now, we'd like to add the possibility of custom tools—this is something we made very good progress in the last few days and we might release this soon.

Custom Chains would require custom classes and to do that we'd have to think through a bit more. 
Once we have the Custom Tools, creating the Custom Class node might be a lot easier but I can't say for sure now as have a lot of tests to run.

**Comment by Luodian** [comment]
Looking forward this feature, then a lot of developers can contribute their ideas!

**Comment by ogabrielluiz** [comment]
Absolutely. We have a working version in dev branch that allows you to add a PythonFunction node and point it to a Tool Node.

You can import whatever is needed in that code and it should work. 

We need more testing because we significantly changed how the graph is processed in the backend.
This change is part of the plan to make it easier for people to contribute.

**Comment by nate2427** [comment]
where in the code can I add my own custom tool? I would love for it to be in the UI, but it's fine if it isn't yet. I looked thru the yaml and saw the the tools listed, so im guessing ill update that with my tool name once the tool is developed and added to langchain. Any quick tutorial on how to do that for langflow?

**Comment by filipecaixeta** [comment]
Any update on this?

**Comment by AbhiramP0405** [comment]
That's cool! @ogabrielluiz ,Could you also tell me how to do it through code?all the steps that are needed to be taken. I tried implementing but i am getting  error on the backend. I dont want to use the PythonFunction. Here is the error i got

**ValueError(f"Type cannot be None. Check if {name} is in the config file."*
