### ISSUE TITLE
Relationship between chat memory and conversation

### ISSUE THREAD

**Issue by nathangary** [logspace-ai/langflow#730]
hi,
I want to use this api,/api/v1/process.
If I configure conversationbuffermemory,Whether the memory is valid for the current interface or the current session？

**Comment by ogabrielluiz** [comment]
Hi, @nathangary 

If the flow is the same, then the cache is used. If you pass tweaks to it, a new cache is created.

I just implemented a better solution to this. We'll test it a bit and see if it's good enough.

**Comment by nathangary** [comment]
Good. I need it.
