### ISSUE TITLE
UI Dissapears when loading invalid json file

### ISSUE THREAD

**Issue by JacobFV** [logspace-ai/langflow#74]
1. Langflow worked when I installed it using pip. 
2. I wanted to add additional agents from the langchain-hub. So I clicked the import button on the top-right import button and selected the self-ask-with-search/agent.json file.
3. From that point onward, the UI would disappear within milliseconds of loading. IE, when I Ctrl+Shift+R'ed, I would briefly see the origonal UI, but it would be gone by the 0.25 second mark. In the Chrome debugger, I observed this message appear at the time that the UI went blank:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at tp (index.tsx:164:21)
    at Ea (react-dom.production.min.js:167:137)
    at El (react-dom.production.min.js:290:337)
    at xs (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:271:88)
    at is (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)
```

By setting a breakpoint in the debugger, I could see the UI correctly rendered prior to the error. After this error happens, the screen is completely white.

4. I tried restarting the langflow server. I tried force reloading. I also tried uninstalling and reinstalling langflow. No change in behavior.

**How can I revert my system to its state prior to importing the json file?** I don't need recovery, I just need to restart as a fresh user. Thanks!

**Comment by ogabrielluiz** [comment]
We fixed that in #71 we'll push that later today.

If you could try testing with it, it would help us a lot.

**Comment by carlorscoelho** [comment]
@JacobFV Does the error persist?

**Comment by JacobFV** [comment]
0.0.46 fixes this issue. Thank you :)
