### ISSUE TITLE
Socket Hang Up Error in Vite HTTP Proxy While Using slackDirectory Loader with OpenAI Embeddings and Chroma Storage

### ISSUE THREAD

**Issue by robertoamoreno** [logspace-ai/langflow#747]
**Describe the bug**

While using Vite for handling HTTP proxy requests in the  flow-frontend service, we encountered a "socket hang up" error during a request to the /api/v1/build/stream/85c9db04-7bcf-47a1-a91d-56ffda742a41 endpoint.

We have to restart services as API dies 

**Browser and Version**
Docker-Compose Dev Branch 

**To Reproduce**

The issue occurred while using the slackDirectory loader to handle a **large** file. We were utilizing OpenAI embeddings, storing the data in Chroma, and subsequently sending a request to the /api/v1/build/stream/85c9db04-7bcf-47a1-a91d-56ffda742a41 endpoint. During this process, we encountered a "socket hang-up" error that resulted in an unexpected connection termination.

**Additional context**
Attached Is flow 
[Chroma-Slack-Embedings.json.txt](https://github.com/logspace-ai/langflow/files/12308258/Chroma-Slack-Embedings.json.txt)

**Comment by robertoamoreno** [comment]
Might be related to docker

**Comment by pseudo-usama** [comment]
@robertoamoreno Did you find any solutions for this? Or any reason why this error is popping up?
