### ISSUE TITLE
Better error message for required fields not fulfilled

### ISSUE THREAD

**Issue by ogabrielluiz** [logspace-ai/langflow#75]
The error currently just tells us there's something missing but it would be very useful if told what is missing.

**Comment by cayal** [comment]
Ah, I think this is the same issue I ran into. I made a small PR #126 that lists missing fields during chat submit validation, is it relevant? @anovazzi1

**Comment by anovazzi1** [comment]
Oh that's really nice, i will test your pr locally and merge it asap.  Thanks a lot 👍
