### ISSUE TITLE
Feature Request: Authentication needed for public domain

### ISSUE THREAD

**Issue by shuvocasanova** [logspace-ai/langflow#752]
In order to use in Public domain, we need to ability to password protect our Langflow instances in  public domain. Without this feature I cant use langflow on a vps or vm instances .

**Comment by mynumu** [comment]
Going to second this. Why is there no authentication? Basic password and username option is a quick add. Thanks

**Comment by anovazzi1** [comment]
Thank you for the feedback! We're actively working on implementing this improvement, and you can expect it to be fully addressed in the upcoming release.

**Comment by faiwongyip** [comment]
Very much needed, would like to have authentication

**Comment by lucianotonet** [comment]
I was going to open this same feature request just right now. Following...

**Comment by namastex888** [comment]
also in need of this :)

**Comment by ogabrielluiz** [comment]
We have a working pre-release version (0.5.0a0, you should be careful deploying it over your current setup) and the dev branch also is constantly being updated to flesh out this feature.
