### ISSUE TITLE
PDF loader example: Error reported after clicking on lightning in the lower right corner

### ISSUE THREAD

**Issue by zhengxiang5965** [logspace-ai/langflow#756]
**Describe the bug**
![image](https://github.com/logspace-ai/langflow/assets/31379313/c1d75ea8-c919-42b2-b161-9b52d1daf335)

**Browser and Version**
0.4.8
**To Reproduce**

**Screenshots**

**Additional context**

**Comment by anovazzi1** [comment]
Appreciate the feedback! Could you let me know which operating system you're using? It would be really helpful if you could provide some additional details. I gave it a try on my end, and everything seems to be working fine.
