### ISSUE TITLE
Few Shot Prompt Template causes "Error: Invalid examples format. Only list or string are supported."

### ISSUE THREAD

**Issue by miguelemosreverte** [logspace-ai/langflow#76]
Hello!

It would seem that `FewShotPromptTemplate` expects a `dict list` which if not placed, will throw this error
<img width="1240" alt="Screenshot 2023-03-28 at 00 54 21" src="https://user-images.githubusercontent.com/9152392/228084851-451536a3-9629-4fd7-b8a4-65e907a9c8e9.png">

How exactly to place a `dict list` inside a `FewShotPromptTemplate`? 
I have not seen a way to instance a `dict list` inside the UI

**Comment by ibiscp** [comment]
I will check this, but I don't think we are handling this case in this version.
