### ISSUE TITLE
Chat with Pinecone not happening!

### ISSUE THREAD

**Issue by MuazAshraf** [logspace-ai/langflow#782]
![image](https://github.com/logspace-ai/langflow/assets/98591478/064180f8-38ec-4c55-a838-60ff59a6399c)

I already mentioned the pinecone api key, index name, namespace. I just hide it. When I remove prompt runner it works fine but when not as in Image it gave me error of unexpected keyword in api key. I try to chat with documents already stored in pinecone in vector form. I am not uploading any document. I don't know how to resolve this isse. Please help me

**Comment by anovazzi1** [comment]
Appreciate the feedback! Could you let me know which operating system you're using? It would be really helpful if you could provide some additional details, like the flow JSON.
