### ISSUE TITLE
Error building node FAISS: FAISS.__init__() got an unexpected keyword argument 'documents'

### ISSUE THREAD

**Issue by alt3rmann** [logspace-ai/langflow#791]
I'm trying to use the FAISS vector database.
I input the RecursiveCharacterTextSplitter along with HuggingFaceEmbeddings or OpenAIEmbeddings.
When I run it, I get an error message "Error building node FAISS: FAISS.init() got an unexpected keyword argument 'documents'"
If I use Chroma instead of FAISS, everything works correctly.
What could be the problem?
<img width="1237" alt="Снимок экрана 2023-08-19 в 17 54 49" src="https://github.com/logspace-ai/langflow/assets/6911130/0e76fee2-e65e-492d-ad1b-3202932f489b">
<img width="1223" alt="Снимок экрана 2023-08-19 в 17 51 57" src="https://github.com/logspace-ai/langflow/assets/6911130/0e76c32b-64ee-4731-979f-7fa304939894">

**Comment by alt3rmann** [comment]
Switched to using only TextLoader instead of WebBaseLoader and without RecursiveCharacterTextSplitter.
Now there's a different error: "Error building node FAISS: FAISS.__init__() got an unexpected keyword argument 'embedding'"
![Uploading Снимок экрана 2023-08-19 в 22.35.48.png…]()

**Comment by sri-dhurkesh** [comment]
I've encountered a similar error when using Chroma DB. What I did to resolve it was to develop a custom component that takes the file as input and returns the list of document instance. This approach works for me..

**Comment by lionelrc** [comment]
I have exactky the sale issue with FAISS.
Error message is : "got an unexpected keyword argument 'documents'"
