### ISSUE TITLE
Invalid session ID when stram build

### ISSUE THREAD

**Issue by zjlearn** [logspace-ai/langflow#797]
**Describe the bug**
when  stream build, error “Invalid session ID”  appear Sometimes。

**env and Version**
 - linux
 - any version

**To Reproduce**
1.  Make the worker's configuration greater than 2
2. Creating flow and build  on web

**Root cause of the problem I guess**
the stream build consists of two steps。 init and stream.  Two steps may be handled by different workers

![image](https://github.com/logspace-ai/langflow/assets/7760670/6dbe44da-4d05-48eb-b69d-466ce9321c43)

Multiple worker processes cannot share memory
```
flow_data_store: LRUCache = LRUCache(maxsize=10)
```

how to solve the problem，thanks!

**Comment by diaa-abushaqra** [comment]
I have the same issue. If I put print statements before the try except block, I can see the flow_id and flow_data_store, but the evaluation still fails.

/opt/homebrew/lib/python3.10/site-packages/langflow/api/v1/chat.py

try:
            if flow_id not in flow_data_store:
                error_message = "Invalid session ID"
                yield str(StreamData(event="error", data={"error": error_message}))
                return
