### ISSUE TITLE
[Question] Can I use langflow to expose an application as a service and share with others

### ISSUE THREAD

**Issue by gyliu513** [logspace-ai/langflow#800]
After the app was created, I can test and debug it. If the app become mature, can I publish it as a service and share with others via langflow? Thanks!

**Comment by anovazzi1** [comment]
Yes you can, just need to share your own hosted version

**Comment by gyliu513** [comment]
Thanks @anovazzi1 , do you have some document that I can refer or any examples for this for how to share?

**Comment by anovazzi1** [comment]
Absolutely, feel free to delve into our [documentation](http://docs.langflow.org/) for more information. To make things even clearer, we have a simple option called the [embedded chat](https://github.com/logspace-ai/langflow-embedded-chat) that you can explore. Give it a look to see if it matches what you're looking for. And don't forget, there's also a live demonstration provided in the documentation. If you have any questions, don't hesitate to ask!

**Comment by gyliu513** [comment]
@anovazzi1 thanks! Let me check and ping you if I have more comments.

**Comment by gyliu513** [comment]
I can publish an app via huggingface.
