### ISSUE TITLE
pip install langflow[local] does not work

### ISSUE THREAD

**Issue by gyliu513** [logspace-ai/langflow#801]
```console
% pip install langflow[local]
zsh: no matches found: langflow[local]
```

Any comments for how can I fix this? Thanks

**Comment by anovazzi1** [comment]
Appreciate the feedback! Could you let me know which operating system you're using? It would be really helpful if you could provide some additional details.

**Comment by gyliu513** [comment]
Hey @anovazzi1 , sorry I should append this when I open the issue

```console
% uname -a
Darwin xxx-MacBook-Pro-2.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64
```

**Comment by gyliu513** [comment]
`% pip install langflow` works well on MacOS

**Comment by gyliu513** [comment]
Seems the python library was not updated, if I clone the code and run `pip install -e .[local]`, it works. @anovazzi1

**Comment by anovazzi1** [comment]
Oh very nice, I'm glad that everything worked.

**Comment by qpdian** [comment]
Works with python 3.9  (langflow require python >=3.9,<3.11
`python3.9 -m venv env
 source env/bin/activate
 pip install langflow`
works well :)
