### ISSUE TITLE
Add BabyAGI Agent

### ISSUE THREAD

**Issue by alphaDev23** [logspace-ai/langflow#803]
This feature request was previously requested, the issue, #445, marked closed, but its unclear as to whether this agent is fully incorporated into LangFlow or if it ever will be incorporated.  Adding this issue to re-open this request.

An issue should not automatically be closed, especially by a "stale bot" unless it is a actually addressed.

**Comment by anovazzi1** [comment]
Hey there! Have you ever given custom components a shot? I've got a feeling they might be a great fit for your situation

**Comment by alphaDev23** [comment]
@anovazzi1 Thank you for the suggestion.  I'm looking into this now.  I still believe that this feature request should remain open to maintain consistency with LangChain's functionality.

**Comment by anovazzi1** [comment]
Of course, we will look to add this feature in near future, for now try the custom components. If you build it with the custom component we can create a component from that code asap.
