### ISSUE TITLE
[Question] Can I have multiple models in one flow

### ISSUE THREAD

**Issue by gyliu513** [logspace-ai/langflow#812]
Seems I can only have one model in one flow now, but just wondering can langflow chain together multiple models? Or this task should belong to langchain but not langchain? Thanks

**Comment by gyliu513** [comment]
Hi @anovazzi1 , this is perfect! I think we are on same picture, evaluating https://docs.langflow.org/components/custom it now :-)

**Comment by anovazzi1** [comment]
You are welcome, call me if you need ;)
