### ISSUE TITLE
Oops! An unknown error has occurred.

### ISSUE THREAD

**Issue by jayita13** [logspace-ai/langflow#820]
https://logspace-langflow.hf.space/flow/e26bfbb1-50d6-49ea-b0fb-f06f1813f3da
Oops! An unknown error has occurred.
Please click the 'Reset Application' button to restore the application's state. If the error persists, please create an issue on our GitHub page. We apologize for any inconvenience this may have caused.

**Comment by anovazzi1** [comment]
Hello, could you please specify which example or workflow you were attempting to execute? This information will help me assist you more effectively.

**Comment by kathekon** [comment]
I'm seeing the same thing on multiple / most of the "Community Examples"  e.g.:  CSV Loader, Multiple Vector Stores, PDF Loader, etc.  

(Probably unrelated, but sharing here just in case:  After seeing those issues I tried cloning the repo and using docker-compose.  When the interface came up I could successfully click into any community example I wanted, but trying to use the chat interface results in a "Input must be bytes, bytearray, memoryview, or str:"  message.

**Comment by anovazzi1** [comment]
Which branch are you using the docker compose version? dev or main?

**Comment by kathekon** [comment]
I'm using dev.  I'll try to switch to main and see what happens.

**Comment by kathekon** [comment]
> Which branch are you using the docker compose? dev or main?

I'm using dev. I'll try to switch to main and see what happens.
