### ISSUE TITLE
Load custom component with env variables not work

### ISSUE THREAD

**Issue by vincent-pli** [logspace-ai/langflow#822]
**Describe the bug**
It's not work follow the guide here:
https://github.com/logspace-ai/langflow/blob/f950bd8a2c0a717d42878a592dbeaa185d371a4f/docs/docs/guidelines/custom-component.mdx#L390C5-L390C5

I set 
`export LANGFLOW_COMPONENTS_PATH=/Users/lipeng/workspaces/github.com/vincent-pli/langflow/new-components
and I got 
`pydantic.env_settings.SettingsError: error parsing env var "langflow_components_path"`

I checked code here:
https://github.com/logspace-ai/langflow/blob/7987a10f921b480b292025e6005ed0ef4f04e7ed/src/backend/langflow/settings.py#L37

seems we expect to a list of path, so I try
`export LANGFLOW_COMPONENTS_PATH='["/Users/lipeng/workspaces/github.com/vincent-pli/langflow/new-components"]'`

it works

**Comment by vincent-pli** [comment]
That's ok, but why we expect a path list at the very beginning? @ogabrielluiz

**Comment by bhaks12** [comment]
I have tried to add the custom component but I am getting the error **SettingsError: error parsing env var**. "langflow_components_path". Can I get the proper steps to add the custom component?
