### ISSUE TITLE
PromptTemplate do not work

### ISSUE THREAD

**Issue by vincent-pli** [logspace-ai/langflow#826]
With one `openai`, one `prompttemplate` and one 'llmchain'
I keep getting 
`Error handling websocket: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)`
when I try to chat.

The build is succeded

**Comment by kathekon** [comment]
Maybe related to what I'm seeing here? https://github.com/logspace-ai/langflow/issues/820#issuecomment-1694394915
