### ISSUE TITLE
Oops! An unknown error has occurred. Trying to edit the PDF source gives out this error

### ISSUE THREAD

**Issue by CorrosiveMoon** [logspace-ai/langflow#827]
![image](https://github.com/logspace-ai/langflow/assets/89851845/07d67f64-0d9e-410f-9812-c73ab024fd16)

Good evening,
So I've been trying to add my own personal pdf in the flow and I always get this error.
Any help would be appreciated.

Thank you.

**Comment by anovazzi1** [comment]
Which branch is that? main or dev?
