### ISSUE TITLE
Tried to fork PDF Loader and got an exception

### ISSUE THREAD

**Issue by bertohuste** [logspace-ai/langflow#831]
OOps! An unknown error occurred.
Please click the 'Reset Application' button to restore the application's state. If the error persists, please create an issue on our GitHub page. We apologize for any inconvenience this may have caused.

The error persists no matter how many times I reset the application.

**Comment by anovazzi1** [comment]
Could you please specify the environment in which this issue is occurring? Additionally, could you provide me with the Langflow version and the specific branch that you are currently running?
