### ISSUE TITLE
Cannot for community templates on the Langflow space in huggingface

### ISSUE THREAD

**Issue by yosifonoren** [logspace-ai/langflow#832]
visit: https://huggingface.co/spaces/Logspace/Langflow
go to community examples
click fork on one of them
get an error

**Comment by anovazzi1** [comment]
Which specific flow is causing the error? I've tested it on my machine, and everything appears to be functioning normally from my end.

**Comment by ruifcruz** [comment]
The same happens to me. It happens with all the flows on the "Community Examples". Have in mind this happens when using it via HuggingFace Spaces.
<img width="948" alt="image" src="https://github.com/logspace-ai/langflow/assets/55488477/38247517-bc02-47a9-943a-998675cf86f0">

**Comment by ruifcruz** [comment]
Ok, have just tried it with another computer and it worked. In the machine I got the error i am under a VPN, so maybe that explains the problem

**Comment by anovazzi1** [comment]
Hugging Face Spaces seems to be experiencing some difficulties with the iframe. For a smoother experience, you can access the content directly using the following link: 
https://logspace-langflow.hf.space/

**Comment by ruifcruz** [comment]
It works! Thanks
