### ISSUE TITLE
Support AzureOpenAI configuration

### ISSUE THREAD

**Issue by bluesheep** [logspace-ai/langflow#85]
The AzureOpenAI LLM is functionally identical to the OpenAI LLM but requires different parameters.

[Azure OpenAI](https://python.langchain.com/en/latest/reference/modules/llms.html?highlight=AzureOpenAI#langchain.llms.AzureOpenAI)

It would be great to be able to use this configuration!

**Comment by ogabrielluiz** [comment]
Hey, we are adding it in our next release. It might some more testing but should work.

**Comment by abetlen** [comment]
Just FYI this would also make it possible to use any llama.cpp compatible models (llama, alpaca, gpt4al, etc) via https://github.com/abetlen/llama-cpp-python#web-server

**Comment by ogabrielluiz** [comment]
This looks very interesting. I have started working on it. It requires a few extra parameters other than the API key. In the case of llama-cpp-python is it exactly the same as the [docs](https://python.langchain.com/en/latest/modules/models/llms/integrations/azure_openai_example.html)?

In LangFlow, if you don't pass the API key, LangChain will still try to find it in the environment but according to the example in the docs, there are a few variables you need to set to be able to use it. What is your opinion on that? 

Are those variables normally set in the environment of the average Azure user?

The deployment_name param is now really simple to add, but we must have a clear template of the node and how it is used.

**Comment by ogabrielluiz** [comment]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/24829397/230503319-fabaac0a-3e0c-49e8-bb95-bf3526d8100f.png">
What do you think of this approach?

**Comment by abetlen** [comment]
@ogabrielluiz woops, after looking into it a little deeper it looks like this was actually already possible with the just the regular `OpenAI` llm. I missed that you could just change the `OPENAI_API_BASE` environment variable. This is actually preferrable as the azure endpoints seem to be using an older version of the OpenAI API.

Anyways, sorry for the confusion. Great tool btw!

![image](https://user-images.githubusercontent.com/6826477/230520544-a9b6bd00-d00e-4691-bac9-97ea97886208.png)

**Comment by ogabrielluiz** [comment]
Oh, nice!

Maybe we could put that functionality into the OpenAI node to allow the person to chose.

I've been thinking about dynamic nodes that change depending on params. Maybe this would be a good use case to explore.

Anyway, with what you described it is possible to use your project?

**Comment by abetlen** [comment]
Yes it should, I'm trying to make it as interoperable as possible with existing tools that already are built against the OpenAI API. 

Currently switching between models doesn't actually do anything as the server only supports a single llama.cpp model loaded in at once but I'm working on allowing the user to provide aliases so e.g. `gpt-3.5-turbo` -> `llama-7b` or `text-davinci-003` -> `llama-30b`

**Comment by adumont** [comment]
> <img alt="image" width="216" src="https://user-images.githubusercontent.com/24829397/230503319-fabaac0a-3e0c-49e8-bb95-bf3526d8100f.png">
> 
> What do you think of this approach?

Nice, ¿but what about these?

```
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_KEY"] = ""
os.environ["OPENAI_API_BASE"] = ""
os.environ["OPENAI_API_VERSION"] = ""
```

**Comment by adumont** [comment]
> <img alt="image" width="216" src="https://user-images.githubusercontent.com/24829397/230503319-fabaac0a-3e0c-49e8-bb95-bf3526d8100f.png">
> 
> What do you think of this approach?

Nice, but right now the OpenAI node takes the `OPENAI_API_KEY`. Azure OpenAI requires 4 values: `OPENAI_API_TYPE`, `OPENAI_API_KEY``, `OPENAI_API_BASE` and `OPENAI_API_VERSION`. The user should also be able to provide them.

**Comment by adumont** [comment]
In addition we'd also need an Azure Open AI Embedding node.

**Comment by mycaule** [comment]
I got an Azure OpenAI account and can test if necessary.
Is the code already written? Do you need help?

**Comment by adumont** [comment]
Same here I have an Azure Account, I can help with testing.

**Comment by SOUMYABROTOBANERJEE** [comment]
Me too!

**Comment by TheodorosGalanos** [comment]
Just bumping this one, I feel it will enable a lot of users. And indeed, I can also help test.

**Comment by khu834** [comment]
bump!
