### ISSUE TITLE
How can i link to llmchain to zeroshotagent

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#851]
![image](https://github.com/logspace-ai/langflow/assets/141118378/101b7a5d-0bc0-4778-8ecc-5f3ee36dd3a8)

In older versions of Langflow, it was possible to add the LLM chain to the Zero Shot Agent, but it doesn't seem to work anymore. How do I achieve the same effect?

**Comment by thigger** [comment]
Apologies for the necro, but how did you solve this?

**Comment by yamonkjd** [comment]
> Apologies for the necro, but how did you solve this?


It's hard to say it's a solution, but I implemented my own zero-shot agent using custom components from LangFlow. I followed the basic examples of LangChain and achieved the desired results without any issues.

**Comment by thigger** [comment]
Thanks - I was just about to start doing that myself - is there any chance I could steal your code?

**Comment by thigger** [comment]
(I've managed to create a custom component which returns an AgentExecutor from a ZeroShotAgent, but the prompt is back up at the LLMChain level so isn't being passed at the moment; I'm pretty new to LangChain and LangFlow)

**Comment by ogabrielluiz** [comment]
That is one of the reasons we moved away from the ZeroShotAgent. 

Try using the initialize_agent function or some other newer method.

**Comment by thigger** [comment]
Just when I have it working! (I removed the memory from the LLMChain and it's attached directly to the agent now). Thanks - I'll have a look at the agent initializer.
