### ISSUE TITLE
How to reset the admin password?

### ISSUE THREAD

**Issue by Decikingship** [logspace-ai/langflow#854]
**Describe the bug**
After updating to the latest version of langflow, I was asked to use a username and password to login. However I don't set the password or created any user. How should I create a new user or reset the admin password?

**Additional context**
I used docker compose to deploy langflow

**Comment by vxacezxcv** [comment]
`langflow superuser` is what you're looking for;
by the way, you should also change the startup command to `langflow run` (instead of `langflow`).

**Comment by vxacezxcv** [comment]
Yes, but maybe not necessary.
Since you seen the login interface, the startup command should be correct.
Use `docker exec -it {your langflow container} langflow superuser` to create an admin account and you're ready to go.

**Comment by Decikingship** [comment]
> Yes, but maybe not necessary. Since you seen the login interface, the startup command should be correct. Use `docker exec -it {your langflow container} langflow superuser` to create an admin account and you're ready to go.

Thank you, problem solved. It was that I couldn't find commands like "superuser". Is there a documentation as such?

**Comment by AdolfVonKleist** [comment]
Also, in case you are running the frontend/backend locally _without_ docker, you can run the backend command:
```
% cd langflow/
% make backend
# then kill it once then:
% poetry run langflow superuser
% make backend
# now login with the new super user and password you created
```

there appears to be no documentation for this anywhere.
