### ISSUE TITLE
RetrievalQAWithSourcesChain Not showing sources of the information

### ISSUE THREAD

**Issue by ojaragodwin** [logspace-ai/langflow#856]
**Describe the bug**
tWhen i use RetrievalQAWithSourcesChain and build the flows successfully, When i chat with what i have built, i get the right responses but i dont get the sources of the information as shown in the picture below.

**Browser and Version**
 - Browser: Chrome
 - Version 116.0.5845.110 (Official Build) (64-bit)

**To Reproduce**
Build the above flows and chart with it, it will give you the righ responses but not sources of the infromation

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/38132692/16e195cf-c3a8-4f82-bfb7-b211056c7f14)

Here is the conversation i had with the bot
![image (1)](https://github.com/logspace-ai/langflow/assets/38132692/143a27e6-dbcd-43ee-8de9-c5f25419a509)

**Comment by sqrt676** [comment]
use embeddings (chunks & vector db), there i got the sources.

**Comment by jaymangukiya0001** [comment]
@ojaragodwin any luck brother on this issue?

**Comment by jaymangukiya0001** [comment]
@sqrt676 could you please share your flow?

**Comment by sqrt676** [comment]
Okay I’ll share it asap.

**Comment by jaymangukiya0001** [comment]
Thanks a lot @sqrt676

**Comment by sqrt676** [comment]
Hi! @jaymangukiya0001 , which type of sources are you expecting, I used retrivalQAchain and it showed.

**Comment by sqrt676** [comment]
My diagram is the one from community example of langchain @jaymangukiya0001 naming PDF....

**Comment by sqrt676** [comment]
is your issue solved? @jaymangukiya0001
