### ISSUE TITLE
”PDF Loader“ can't be started.

### ISSUE THREAD

**Issue by longmarchw** [logspace-ai/langflow#861]
in "Community Examples" or "My Collection", none of them can be started。

**Comment by niklaspm** [comment]
Can you provide further context? I checked with langflow versions 0.4.17 and 0.5.0a0 (Python 3.10.12, Microsoft Edge) and everything works as expected.

**Comment by longmarchw** [comment]
It‘s error info by prtsc.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: niklaspm ***@***.***>
发送时间: Monday, September 4, 2023 4:16:35 PM
收件人: logspace-ai/langflow ***@***.***>
抄送: longmarchw ***@***.***>; Author ***@***.***>
主题: Re: [logspace-ai/langflow] ”PDF Loader“ can't be started. (Issue #861)


Can you provide further context? I checked with langflow versions 0.4.17 and 0.5.0a0 (Python 3.10.12, Microsoft Edge) and everything works as expected.

―
