### ISSUE TITLE
Cannot install on Mac M1

### ISSUE THREAD

**Issue by Jchang4** [logspace-ai/langflow#864]
**Describe the bug**
Runing `pip install langflow` fails with error: 

```
ERROR: Cannot install jina because these package versions have conflicting dependencies.

The conflict is caused by:
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.40b0 depends on opentelemetry-instrumentation==0.40b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.39b0 depends on opentelemetry-instrumentation==0.39b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.38b0 depends on opentelemetry-instrumentation==0.38b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.37b0 depends on opentelemetry-instrumentation==0.37b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.36b0 depends on opentelemetry-instrumentation==0.36b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.35b0 depends on opentelemetry-instrumentation==0.35b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.34b0 depends on opentelemetry-instrumentation==0.34b0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Browser and Version**
 - Chrome
 - 116

**To Reproduce**
`pip install langflow` on Mac M1

**Comment by lubancafe** [comment]
+1

**Comment by songw** [comment]
I have the same error.

**Comment by niklaspm** [comment]
Which python and pip version do you guys use? Have you tried running `pip install --upgrade pip` before installing?

**Comment by lubancafe** [comment]
> Which python and pip version do you guys use? Have you tried running `pip install --upgrade pip` before installing?

Just updated pip. Successfully installed pip-23.2.1; still get above error when pip install langflow

**Comment by omorilewa** [comment]
We got stuck with this errror too. 😞  Looks like it suddenly started yesterday.

**Comment by kirandeol** [comment]
+1 I am also getting this same error, but on Google Colab.

**Comment by niklaspm** [comment]
The issue is caused by the Jina package. The fix (https://github.com/jina-ai/jina/pull/6037) has already been merged into Jina's master branch, but until they've released the changes to the package, the easiest way to install LangFlow is to clone the repo and add `opentelemetry-sdk = ">=1.14.0,<1.20.0"` to the dependencies listed in `pyproject.toml`  and then install the package using `pip install .` from within the cloned repo's base directory.

**Comment by PenziSu** [comment]
> The issue is caused by the Jina package. The fix ([jina-ai/jina#6037](https://github.com/jina-ai/jina/pull/6037)) has already been merged into Jina's master branch, but until they've released the changes to the package, the easiest way to install LangFlow is to clone the repo and add `opentelemetry-sdk = ">=1.14.0,<1.20.0"` to the dependencies listed in `pyproject.toml` and then install the package using `pip install .` from within the cloned repo's base directory.

Thanks @niklaspm, I followed your recommendation and successfully installed langflow. 
However, I encountered an error saying "RuntimeError: Static files directory anaconda3/envs/langchain/lib/python3.10/site-packages/langflow/frontend does not exist." 
Have you experienced the same issue?

**Comment by jihun-bang** [comment]
I installed it like this

`pip3 install "opentelemetry-sdk >=1.14.0,<1.20.0" langflow`

**Comment by songw** [comment]
@PenziSu same error.

**Comment by songw** [comment]
> > The issue is caused by the Jina package. The fix ([jina-ai/jina#6037](https://github.com/jina-ai/jina/pull/6037)) has already been merged into Jina's master branch, but until they've released the changes to the package, the easiest way to install LangFlow is to clone the repo and add `opentelemetry-sdk = ">=1.14.0,<1.20.0"` to the dependencies listed in `pyproject.toml` and then install the package using `pip install .` from within the cloned repo's base directory.
> 
> Thanks @niklaspm, I followed your recommendation and successfully installed langflow. However, I encountered an error saying "RuntimeError: Static files directory anaconda3/envs/langchain/lib/python3.10/site-packages/langflow/frontend does not exist." Have you experienced the same issue?

same error.

**Comment by CyrilleVi** [comment]
> I installed it like this
> 
> `pip3 install "opentelemetry-sdk >=1.14.0,<1.20.0" langflow`

Hello all,
thanks for the tip, I could install langflow locally with your method. 
the app opened fine in chrome but ended up crashing python when trying to use it 

i'm also on M1 mac. 

this is the error message i got on the terminal 
"objc[42670]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[42670]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug." 

Inside langflow, the error message went 
"There was an error on web connection, please:
Refresh the page
Use a new flow tab
Check if the backend is up" 


looking forward to the fixed pip install 
cheers

**Comment by AlexeyDep** [comment]
same error  Windows 11

**Comment by Kamalsky-dev** [comment]
> I installed it like this
> 
> `pip3 install "opentelemetry-sdk >=1.14.0,<1.20.0" langflow`

this one worked for me (windows).

**Comment by tschadha** [comment]
I am getting the following errors after using the following commands to build langflow on Mac Mini, running M4 Pro:

pip3 install "opentelemetry-sdk >=1.14.0,<1.20.0" langflow

no errors reported.

But after running langflow get the following errors:

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/_api/module_import.py:120: LangChainDeprecationWarning: Importing SQLDatabase from langchain is deprecated. Please replace deprecated imports:

        from langchain import SQLDatabase

with new imports of:

        from langchain_community.utilities import SQLDatabase

warn_deprecated(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/_api/module_import.py:120: LangChainDeprecationWarning: Importing RequestsWrapper from langchain is deprecated. Please replace deprecated imports:

        from langchain import RequestsWrapper

with new imports of:

        from langchain_community.utilities import RequestsWrapper

warn_deprecated(
╭───────────────────────────────────────────────────╮
│ Welcome to ⛓ Langflow │
│ │
│ Access http://127.0.0.1:7860/ │
│ Collaborate, and contribute at our GitHub Repo 🚀 │
╰───────────────────────────────────────────────────╯
[01/07/25 21:37:33] INFO 2025-01-07 21:37:33 - INFO - service - Alembic already initialized service.py:142
INFO 2025-01-07 21:37:33 - INFO - service - Running DB migrations in service.py:150
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langflow/alembic
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
context.run_migrations()
No new upgrade operations detected.
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langflow/alembic/env.py:82: SAWarning: WARNING: SQL-parsed foreign key constraint '('user_id', 'user', 'id')' could not be located in PRAGMA foreign_keys for table flow
context.run_migrations()
No new upgrade operations detected.
INFO 2025-01-07 21:37:33 - INFO - utils - No LLM cache set.
