### ISSUE TITLE
[Question] use custom chain in custom component

### ISSUE THREAD

**Issue by lookoutking** [logspace-ai/langflow#867]
Is it possible to use a custom chain: https://python.langchain.com/docs/modules/chains/how_to/custom_chain in a custom component? 

The flow should end with a Langchain `Chain` or vector store. I want to customize my own `Chain` to do something like the [TransformChain](https://python.langchain.com/docs/modules/chains/foundational/transformation), but pre-set the input value before `chain.run()` is called. Could I assign the inputs of the `Chain` inside the flow?

**Comment by yamonkjd** [comment]
I don't know if this answers what you want, but I needed to run another chain and this example helped me. I think this is an alternative to Langflow and is more sophisticated.

https://docs.langflow.org/examples/flow-runner

**Comment by lookoutking** [comment]
Thank you for your suggestion, @yamonkjd. Instead of using `CustomComponent`, I referenced the `CombineDocsChain` class to implement my custom chain. This allowed me to achieve what I wanted.

**Comment by yamonkjd** [comment]
Since I responded previously, I am also investigating the issue for the same reason. I am researching how to create and overwrite a Wrapper class that inherits Langchain's basic chain with a custom component, and I will continue to share the content.

**Comment by yaelhol** [comment]
I also didn't success to custom Chain in langflow using CustomComponent (the issue is that the output type is not recognized in the UI). 
@lookoutking can you explain how you did it without using CustomComponent?

**Comment by lookoutking** [comment]
My workaround to add custom langchain `Chain` in langflow:
1. Add your custom `Chain` class in `src\backend\langflow\interface\chains\custom.py`
Reference to https://python.langchain.com/docs/modules/chains/how_to/custom_chain

2. Add Frontend node in `src/backend/langflow/template/frontend_node/chains.py` that inherit `FrontendNode`

3. Add the key-value in the chains of `CUSTOM_NODES` in `src/backend/langflow/custom/customs.py`

4. Add the class in the `src/backend/langflow/config.yaml`
