### ISSUE TITLE
Where is the code of chat widget component?

### ISSUE THREAD

**Issue by Nov1c444** [logspace-ai/langflow#868]
I want to change the chat widget component's code, where can i find it?

**Comment by Nov1c444** [comment]
> 1. Click on the </> code symbol on the upper left side within your flow / project
> 
> ![image](https://user-images.githubusercontent.com/89383596/265664119-15323e82-5823-4762-a582-457105340f26.png)
> 
> 2. Then select tab "Chat Widget HTML"
> 
> ![image](https://user-images.githubusercontent.com/89383596/265664232-0acc0fb5-96df-406d-a65c-8f64cbd067d3.png)

thanks for your reply, but I want to find the chat component source code and change it. I can only see the min.js file through the screenshot, it's compressed code.

**Comment by niklaspm** [comment]
Are you asking for this (https://github.com/logspace-ai/langflow-embedded-chat) repo?

**Comment by Nov1c444** [comment]
yeah, that's what i need. thanks. love you!😁

**Comment by Nov1c444** [comment]
it works.
