### ISSUE TITLE
Oops! An unknown error has occurred.

### ISSUE THREAD

**Issue by souravjamwal77** [logspace-ai/langflow#871]
Whenever I'm trying to fork any **community examples** from this repo [Link](https://huggingface.co/spaces/Logspace/Langflow). I'm getting below error
![Screenshot from 2023-09-05 15-55-14](https://github.com/logspace-ai/langflow/assets/25997760/07786f4e-f7fa-409a-9f4e-c3119e5fe489)

**Comment by niklaspm** [comment]
I just tried it and it works just fine for me. Which browser do you use?
