### ISSUE TITLE
Continuously asking the same question, langflow will automatically use the cached results to return

### ISSUE THREAD

**Issue by zhengxiang5965** [logspace-ai/langflow#880]
Continuously asking the same question, Langflow will automatically use the cache result to return, which is very unfriendly to some tools that add, delete, or modify types. How to close this cache? Every time a question is asked, the tool will be called

**Comment by zhengxiang5965** [comment]
@ogabrielluiz @anovazzi1 @lucaseduoli

**Comment by ogabrielluiz** [comment]
hey, @zhengxiang5965 

This will be in our next release, possibly later today.
