### ISSUE TITLE
FloatComponent support min max range 

### ISSUE THREAD

**Issue by loleek** [logspace-ai/langflow#884]
Currently，float type only support rang on [0.0, 1.0], but some parameters have range exceed [0.0, 1.0]  like presence_penalty and frequency_penalty which min is -2. and 2.0.

**Comment by Cristhianzl** [comment]
Hello @loleek,

I'll explore expanding the FloatComponent's range. After reviewing the OpenAI documentation, it aligns with your explanation. Thanks!
