### ISSUE TITLE
Can't add langchain components in custom config.yaml

### ISSUE THREAD

**Issue by yaelhol** [logspace-ai/langflow#885]
**Describe the bug**
I run langflow with the option --config and give my own config.yaml. I added to my yaml langchain components: RouterChain, LLMRouterChain, MultiRouteChain etc. but I don't see those components in the list in the Canvas.  

When I debug I see that ChainCreator.type_to_loader_dict contains the list  

**To Reproduce**
1. create config.yaml that is copy of langflow config.yaml. under chains add:
  RouterChain:
    documentation: "" 
2. run 'langflow --config <path to your config.yaml>
3. The RouterChain doesn't appear in the canvas

**Comment by yamonkjd** [comment]
As far as I know, there is no reason to edit the config file simply to add your custom chain to the chain list. Enter your source code in the "chains" folder in the component folder and it will automatically be displayed in the chains list.

**Comment by yamonkjd** [comment]
If you provide your source, I can review it as well.
