### ISSUE TITLE
Can't use API endpoint: This session is in 'prepared' state

### ISSUE THREAD

**Issue by moelllerniklas** [logspace-ai/langflow#887]
**Describe the bug**`

Endpoint: `POST /v1/process`
```curl
{"detail":"This session is in 'prepared' state; no further SQL can be emitted within this transaction."}
```

**Browser and Version**
 - cURL
 - Latest LangFlow version (0.5.0a)
 - PostgreSQL 14.9 as database backend

**To Reproduce**
Setup a flow and call the api endpoint using cURL

**Screenshots**
![image](https://github.com/logspace-ai/langflow/assets/89383596/f46a782d-4985-4db5-abb4-389e6397ac6c)
![image](https://github.com/logspace-ai/langflow/assets/89383596/61f7811a-93e2-4a1f-a034-a3cbdfb90667)

**Comment by niklaspm** [comment]
```python
try:
    session.commit()
except AttributeError:
    pass
flow = (
    session.query(Flow)
    .filter(Flow.id == flow_id)
    .filter(Flow.user_id == api_key_user.id)
    .first()
)
```

Trying to commit the session before querying for the flow solves the issues but this more a workaround than a solution there must happen some weird things with the session management in the background.
