### ISSUE TITLE
How to use output of LLMChain as input in another Chain?

### ISSUE THREAD

**Issue by thepok** [logspace-ai/langflow#89]
I would like to have one chain produce some text, and another chain refine that text.

**Comment by ogabrielluiz** [comment]
This is something we are planning on releasing very soon. We just need some more testing haha

**Comment by dnrico1** [comment]
Hi @ogabrielluiz ! Just wanted to ask if you have an ETA for this feature? I think that this is what would really make the visual interface be worth it!

**Comment by dnrico1** [comment]
Thanks for the quick reply @ogabrielluiz! I just installed the library today through pip install langflow, but I don't seem to be able to do that. How is it supposed to work, and do I perhaps just have an outdated version?

**Comment by ogabrielluiz** [comment]
I think I know what you mean now. 

LangFlow allows you to connect modules, not their inputs and outputs.
So, the module itself goes into another one to build the final module.

One way to achieve what you want would be to create a Tool using a PythonFunction node and create the modules inside the function passing the output of one to the other.
