### ISSUE TITLE
 Building using the Make command does not work properly.

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#901]
I did "Make init" according to the manual, then ran "Make backend" and "Make frontend" to check that the UI was displayed. When you try to edit a flow or create a new flow, the following error screen is displayed.

![image](https://github.com/logspace-ai/langflow/assets/141118378/ffeed956-7d6b-48e9-9e95-daa5e6bf028d)

Even if I press the reset application button, the result is the same.

"Make build_and_run" works fine.

**Comment by yamonkjd** [comment]
After research by our developers, it appears that there is a dependency problem.

sudo npm i -D @swc/cli @swc/core

The command was executed.

**Comment by yamonkjd** [comment]
gflow-frontend-1  |   VITE v4.3.9  ready in 748 ms
langflow-frontend-1  | 
langflow-frontend-1  | 
langflow-frontend-1  |   ➜  Local:   http://localhost:3000/
langflow-frontend-1  |   ➜  Network: http://172.23.0.3:3000/
langflow-backend-1   | ERROR:    Error loading ASGI app. Attribute "app" not found in module "langflow.main".
langflow-frontend-1  | Bindings not found.
langflow-frontend-1  | 7:25:05 AM [vite] Internal server error: Bindings not found.
langflow-frontend-1  |   Plugin: vite:react-swc
langflow-frontend-1  |   File: /home/node/app/src/index.tsx
langflow-frontend-1  |       at Com

**Comment by ogabrielluiz** [comment]
Hey @yamonkjd 

Could you try running `make frontendc`?

**Comment by yamonkjd** [comment]
> Hey @yamonkjd
> 
> ~Could you try running `make frontendc`?~
> 
> Just saw you are running using docker-compose. What branch are you running at the moment?

I chekouted 0.4.18 of branches

**Comment by yamonkjd** [comment]
I still don't know what the problem is, but it works normally after updating to version 0.4.20. Close the issue.
