### ISSUE TITLE
Error building node JsonSpec: 'path'

### ISSUE THREAD

**Issue by mirkancal** [logspace-ai/langflow#902]
**Describe the bug**
Couldn't make json agent flow work. Path error.

**Browser and Version**
 - Browser brave and chrome
 - Version 1.57.62

**To Reproduce**
1. Import json agent example.
2. Pick a json file
3. Try to run

**Screenshots**
<img width="1727" alt="image" src="https://github.com/logspace-ai/langflow/assets/26160059/5add5e39-cfc3-48a5-95f7-3df376b1ab9c">

**Additional context**

**Comment by aolowude** [comment]
+1 having the same issue
