### ISSUE TITLE
[Question]: Import Error When Running Custom Component

### ISSUE THREAD

**Issue by alexnodeland** [logspace-ai/langflow#920]
Hello,

I've been working on a custom component which is designed to load a file from the project directory using an internal script and return it as a Langchain Document.

The component works as expected when I test it locally using a Python script. However, when I try to run it on the Langflow server, I encounter an import error: `Module helpers.scripts.config_reader not found`.

Here's my code:

<details>

```python
from langflow import CustomComponent
from langchain.schema import Document
import json
import codecs
import markdown
from helpers.scripts.config_reader import read_file

class ProjectFileLoader(CustomComponent):
    display_name = "Project File Loader"
    description = "This component loads a piece of context or a template from the project directory and returns it as a Langchain Document."

    def build_config(self) -> dict:
        return {
            "file_path_key": {
                "display_name": "File Path Key",
                "type": "str"
            },
            "file_type_key": {
                "display_name": "File Type Key",
                "type": "str"
            },
            "fail_silently": {
                "display_name": "Fail Silently",
                "value": False,
                "type": "bool"
            }
        }

    def build(self, file_path_key: str, file_type_key: str, fail_silently: bool) -> Document:
        try:
            content = read_file(file_path_key, file_type_key)
            self.repr_value = content  # Display the content in the UI
            return Document(page_content=str(content))
        except (FileNotFoundError, json.JSONDecodeError) as e:
            if fail_silently:
                return Document(page_content="")
            else:
                raise e
``` 

</details>

The `helpers.scripts.config_reader` module is located in a sibling directory to the `custom_components directory`, where this `ProjectFileLoader` lives. I've tried adjusting the import statement and the Python path, but none of these solutions have resolved the issue.

I'm wondering if there's something specific about the way the Langflow server handles Python imports that I'm not aware of. Any guidance would be greatly appreciated.

Thank you!

**Comment by gyliu513** [comment]
Also have same question: How to enable custom component can use custom libraries?

**Comment by yamonkjd** [comment]
As I understand it, the working principle of custom components is that LangFlow monitors the "components" folder, and if there is a new component, it goes through the process of building the corresponding source internally. At this time, the Python file that exists in the folder is a draft for building. It only provides the code, but does not actually execute the code itself. If you want to include a separate library, it is correct to include the entire source in the "build" function.

**Comment by yamonkjd** [comment]
My recommendation is to write "from helpers.scripts.config_reader import read_file" as a new custom component and link it to "ProjectFileLoader" as a parameter.

**Comment by yamonkjd** [comment]
Although the main contributors are working hard to create custom components, I agree that it is difficult to properly understand how they work due to the lack of manuals. I'm not sure if it's accurate since this is an inference I obtained through reverse engineering, but I created a tool using the same method as above.

**Comment by yamonkjd** [comment]
The "PythonFunction" component may also be helpful in your implementation.
