### ISSUE TITLE
Install missing dependencies - sentence_transformers

### ISSUE THREAD

**Issue by bizrockman** [logspace-ai/langflow#936]
Hi,

I tried langflow today using the docker compose command.

With HuggingFaceEmbeddings I am getting this error:

`Error building node HuggingFaceEmbeddings: Could not import sentence_transformers python package. Please install it with 'pip install sentence_transformers'.`

Since langflow is using Poetry for dependency management, what I am unfamiliar with I wonder how can I install missing dependencies in langflow especially in the docker image.

Running "pip install sentence_transformer" is not removing this issue.

**Comment by gyliu513** [comment]
Hi @bizrockman , run `poetry run pip install sentence_transformer`, this will install it on your poetry virtual env and it should works.
