### ISSUE TITLE
Custom llm

### ISSUE THREAD

**Issue by joelr45** [logspace-ai/langflow#938]
Hey guys, 

I have been trying to create an interface for my custom llm, is there a way to do this through the CustomComponent? Or what is the best approach to do so?

Thanks!

**Comment by gyliu513** [comment]
@joelr45 Yes, custom component is a good option, you can follow https://docs.langflow.org/guidelines/custom-component to build your own component.

Check https://docs.langflow.org/components/custom#the-customcomponent-class for the return values for `build_config` and `build`. Basically `build_config` will help you build the drag-and-drop box and `build` will return the value as you want, like `langchain.schema.Document` or `langchain.llms.base.BaseLLM`.  

For your case, the `build` return value will be `langchain.llms.base.BaseLLM`. 

A sample code for your reference, hope it helps.

```python
from langflow import CustomComponent
from langchain.chains import LLMChain
from langchain import PromptTemplate
import requests

from langchain.llms.base import BaseLLM

from typing import Any, Callable, List, Mapping, Optional

from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.llms.base import LLM
from langchain.llms.utils import enforce_stop_tokens
from langchain.pydantic_v1 import Field

class PromptLLM(CustomComponent):
    display_name = "PromptLLM"
    description = "This component leverage huggingface space service to generator a prompt"

    def build_config(self) -> dict:
        return { "Space URL": { "multiline": True, "required": True } }

    def build(self, url: str) -> BaseLLM:
        return yourLLM
```

**Comment by gyliu513** [comment]
This may help you https://github.com/gyliu513/langflow101/blob/main/new-components/custom_components/prompt_llm.py

**Comment by joelr45** [comment]
@gyliu513 This is very helpful, thanks so much!
