### ISSUE TITLE
[Proposal] Build a new repo named as `langflow-contrib` or `langflow-custom-component` for custom components

### ISSUE THREAD

**Issue by gyliu513** [logspace-ai/langflow#940]
Custom components is a great feature and I believe people already have many great custom components in hand but did not share with others yet (Probably because no place to host the code centrally).

Can we build a new repo named as `langflow-contrib` or `langflow-custom-component` which will be the repo to host some custom components? Anyone who has a custom component can contribute there with a simple documentation. I think this can help a lot for people to play with custom component and enlarge the eco-system for langflow.

Comments? Thanks

**Comment by yamonkjd** [comment]
Very good idea.

**Comment by yassineselmi** [comment]
+1

**Comment by anovazzi1** [comment]
That's a fantastic idea! The exciting news is that we're currently in the process of creating a platform for sharing custom components. In the meantime, you can utilize our Discord community to share your components.

**Comment by gyliu513** [comment]
> creating a platform for sharing custom components. 

Thanks @anovazzi1 , what do you mean a platform for sharing custom component? Can you elaborate? :)

**Comment by anovazzi1** [comment]
I can't really tell much about it yet, but we will provide an easy way to share your components, for now, I suggest using Discord or Gist.

**Comment by gyliu513** [comment]
Good, thanks @anovazzi1 , let me close this issue.
