### ISSUE TITLE
Running langflow in replit

### ISSUE THREAD

**Issue by carlosrcoelho** [logspace-ai/langflow#95]
This issue is for us to discuss this topic and its implementation.

Let's discuss langflow in [replit](https://replit.com/) and test it so that we can see if it works.

**Comment by ogabrielluiz** [comment]
Click on Run Example to the right and it should show LangFlow.
https://replit.com/@GabrielAlmeida8/Langflow?v=1

**Comment by ibiscp** [comment]
@ogabrielluiz can we close this one?

**Comment by jetblaise** [comment]
what do you have to modify in the langflow codebase to allow you to fork the langflow repo and deploy your own copy in replit? i think i'm more limited in how to use replit than langflow lol, but i'd like to mess around with langflow codebase on replit so i can collab with my buddies. It looks like you use the 0.0.0.0, I assume that's the standard for replit deployment?

To clarify, i want to be able to sync my fork with the main branch, but it looks like if we used your template @ogabrielluiz we wouldn't be able to do that and when I used yours as a template, it looks like and old branch of langflow. Any guidance?

**Comment by ogabrielluiz** [comment]
I'm not too familiar with replit either. A person from the community created this one once: https://replit.com/@SunziAI/LangFlow-Production-SunziAI

Maybe you could give it a try.
