### ISSUE TITLE
Unable to edit parameter or toggle visibility in edit menu for any component

### ISSUE THREAD

**Issue by gestalt73** [logspace-ai/langflow#953]
**Describe the bug**
I'm unable to [show] or [hide] any parameter listed in the edit popup menu for any component.
I'm also unable to edit any parameter in the edit popup menu for any component.  I can only make changes to visible parameters on the component main view.

**Browser and Version**
 - Browser: chrome 117.0.5938.88 (Official Build) (64-bit)
 - Langflow Version: v0.4.21 from pip install langflow, python 3.10

**To Reproduce**
1. Go to any existing project with components
2. Click on the edit button for the selected component
3. Click on the show/hide toggle for any parameter
4. Note how the toggle changes the icon to a hand, you are unable to change the visibility of any parameter
5. Also I cannot edit the parameter from the edit menu.  :-(

**Screenshots**
![Screenshot from 2023-09-21 19-44-06](https://github.com/logspace-ai/langflow/assets/7560718/35ceb83c-f311-4478-b86c-99d692f912df)

**Additional context**
The only reason it's bugging me is because I need to redirect the OpenAIEnbeddings to my local API but cannot as the parameter is hidden and I am unable to edit it from the edit menu.  :-(

Thanks for your help!

**Comment by yamonkjd** [comment]
I also turned on the visibility with JSON and confirmed that it was working properly, but I don't understand why they didn't even allow that part to be selected.

**Comment by gestalt73** [comment]
Ok, I see what you mean now.  I exported the json and figured out that the `"advanced": true` was keeping the parameter from being visible and editable on the main component window.  Flipping it to false and importing gave me a version of the component that I could edit.  Also flipped the `"password": true` to false for good measure. no reason to hide the endpoint.

```
"openai_api_base": {
    "required": false,
    "placeholder": "",
    "show": true,
    "multiline": false,
    "password": false,
    "name": "openai_api_base",
    "display_name": "OpenAI API Base",
    "advanced": false,
    "dynamic": false,
    "info": "",
    "type": "str",
    "list": false,
    "value": ""
},
```

![2023-09-22_12-58-51](https://github.com/logspace-ai/langflow/assets/7560718/52b7ca78-e00d-4326-bfed-b5e6087c7562)

**Comment by gestalt73** [comment]
Hey @anovazzi1 was this defect fixed in a recent commit?
I don't see any recent commits that would address the issue.

The bug is that the show/hide toggle doesn't do anything in the edit modal for components.

**Comment by anovazzi1** [comment]
which branch are you in? dev or main?
