### ISSUE TITLE
Chat is not responding

### ISSUE THREAD

**Issue by Hyman00** [logspace-ai/langflow#961]
Hi all. I tried to use longflow with some simple examples. Everything seems to be working: Green circles, no errors. However, the chat is not responding to my request. I have chatGPT plus, trying Basic chat example with gpt-3.5-turbo on a Mac in Chrome and Safari. The Terminal is stuck on the initial command:

> Entering new chain...

Prompt after formatting:

The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:

Human: test

AI:

Do you have any ideas why it is not responding? Thanks.

**Comment by yamonkjd** [comment]
You must enclose the Key to be assigned to the formatted variable in the prompt with {}.


The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:
{chathistory}

Human: {input}

AI:

**Comment by ian2743** [comment]
@Hyman00 I have encountered the same problem, how did you solve it？
