### ISSUE TITLE
Method for Dynamically Manipulating Parameters of a Custom Component

### ISSUE THREAD

**Issue by yamonkjd** [logspace-ai/langflow#965]
```python
class DynamicConfigCustomComponent(CustomComponent):
    def build_config(self, prev_selection=None):
        config = {
            "param1": {"display_name": "Parameter 1"},
            "param2": {
                "display_name": "Parameter 2",
                "options": [1, 2, 3],
                "value": 1,
            },
        }
        
        if prev_selection is not None:
            if prev_selection == 2:
                config["param3"] = {"display_name": "Parameter 3", "value": "hello"}
                
        return config

``` 
I want to dynamically change different values depending on the type of component that is input or connected when using a custom component, as shown in the attached code. For example, in Langflow's prompt template, when you change the text, the key value input into that component is dynamically displayed in the list. Is there any way to do this?

**Comment by yamonkjd** [comment]
langflow/src/frontend/src/types/components/index.ts

When the onChange event occurs in this UI component, I think an effective way would be to recursively implement it by re-entering the custom component along with the current variable according to the console I attached above.

**Comment by anovazzi1** [comment]
At this time, executing Python code within the browser is not achievable. The challenge with the suggested approach is that it would run on the backend instead of directly within the user interface. so your if only will run on the back, after the build.
