### ISSUE TITLE
Invalid session ID

### ISSUE THREAD

**Issue by liningwangyi** [logspace-ai/langflow#973]
<img width="1426" alt="image" src="https://github.com/logspace-ai/langflow/assets/4555550/f28a2f77-e93d-4cb0-ba9b-3632cae88064">
after build ，error message is “Invalid session ID”

**Comment by gitTreeYoung** [comment]
+1 遇到了同样的问题 same question

**Comment by eugenechoD** [comment]
Same issue as well

**Comment by anovazzi1** [comment]
which branch is this happening?

**Comment by dogeisler** [comment]
Same issue here

**Comment by SweeftAchi** [comment]
Same here

**Comment by gzark1** [comment]
One possible reason may be that you are not using a paid version of OpenAI (GPT-3.5, GPT-4 etc). In other words, you have zero Credit balance in your OpenAI account. That was the problem in my case when I got `Invalid session ID`

**Comment by diaa-abushaqra** [comment]
Same here, and I'm not using OpenAI so I shouldn't be getting session timeout. I'm using llamacpp. Langlfow was installed used pip install langflow[local]

**Comment by 4n3ver** [comment]
I ran into the same issue and I was able to work around it by running:
```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

I'm on ARM MacOS for context

**Comment by nath-byond** [comment]
same issue

**Comment by yassineselmi** [comment]
I have the same issue in v0.6.3, and only when I deploy the services in my k8s cluster.
The error happens 3 times out 5 (average). And it is when I try to build a flow.

The error is in [src/backend/langflow/api/v1/chat.py#L121](https://github.com/logspace-ai/langflow/blob/v0.6.3/src/backend/langflow/api/v1/chat.py#L121):

```python
  if flow_id not in cache_service:
      error_message = "Invalid session ID"
      yield str(StreamData(event="error", data={"error": error_message}))
      return
```

So, it means that the `flow_id` is not (yet) in the `cache`. However, in [#L79](https://github.com/logspace-ai/langflow/blob/v0.6.3/src/backend/langflow/api/v1/chat.py#L79), the cache is being filled during the build.

So, I guess it is something related to the LRU  cache. Any ideas?

**Comment by yassineselmi** [comment]
This workaround worked for me, but idk if it has an impact on the performance or not:

I set `--workers="1"` so uvicorn will just use a single worker (and I guess a single cache instance).
