### ISSUE TITLE
Unable to edit model in HuggingFaceEmbeddings page

### ISSUE THREAD

**Issue by techmasknet** [logspace-ai/langflow#978]
Hello, I'm a newbie to langflow. I've been trying to use the HuggingFaceEmbeddings and wanted to change the model. However, I noticed that the page is non-editable. Could you guide me on how to modify the model?
<img width="1098" alt="image" src="https://github.com/logspace-ai/langflow/assets/52841380/1595d248-4d5a-4285-a38b-28f17ef02fd2">

**Comment by anovazzi1** [comment]
it's supposed to be editable, I tried it on my machine and it worked, did you try setting the show to true?

**Comment by dixan51** [comment]
i've the same problem, not only for Embeddings, but also other node....

**Comment by anovazzi1** [comment]
can you see if there is any error on the console?

**Comment by dixan51** [comment]
No errors in the console.  It's very stranges, failing to modify the parameters is unusable.
- Windows 11 (IT)
- Anaconda (Python 3.10.13)
- create new virtual env and then: pip install langflow[local]

any help is appreciated
