### ISSUE TITLE
Custom Component input gets deleted on opening the Code section

### ISSUE THREAD

**Issue by checksanjay** [logspace-ai/langflow#979]
**Describe the bug**
Custom Component input gets deleted on opening the Code section

**Browser and Version**

**To Reproduce**
1. create a new flow
2. drag a custom component on to canvas
3. enter url value
4. click on code
5. url field gets empty

**Screenshots**

**Additional context**

**Comment by anovazzi1** [comment]
When you save the code of the custom component, it undergoes a complete rebuild, effectively overwriting any default values with your new code.
