### ISSUE TITLE
Compile error: "langchain.chains" has no attribute 'SQLDatabaseChain'

### ISSUE THREAD

**Issue by techmasknet** [logspace-ai/langflow#991]
**Describe the bug**
As shown in the screenshot below, I encountered a compile error when using SQLDatabaseChain. The error message is: "langchain.chains" has no attribute 'SQLDatabaseChain'.

**Browser and Version**
 - Version v0.4.21

**Screenshots**
<img width="889" alt="image" src="https://github.com/logspace-ai/langflow/assets/52841380/9925dfd4-76f0-447b-a411-7ffc31d7eefd">

**Comment by jonathan-np-dev** [comment]
I’m getting the same error. I’ve tried deploying the last code to Render which seems to have several commits related to fixing this problem.
