### ISSUE TITLE
langflow backend always report websocket disconnect error

### ISSUE THREAD

**Issue by gyliu513** [logspace-ai/langflow#992]
Build a conversationchain with different models, but neither of them works, and I always got a exception as follows:

```python
╭─────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────╮
                             │ /Users/guangyaliu/ycliu/lib/python3.10/site-packages/langflow/services/chat/manager.py:204 in handle_websocket                                                   │
                             │                                                                                                                                                                  │
                             │   201 │   │   │   await websocket.send_json(chat_history)                                                                                                        │
                             │   202 │   │   │                                                                                                                                                  │
                             │   203 │   │   │   while True:                                                                                                                                    │
                             │ ❱ 204 │   │   │   │   json_payload = await websocket.receive_json()                                                                                              │
                             │   205 │   │   │   │   try:                                                                                                                                       │
                             │   206 │   │   │   │   │   payload = orjson.loads(json_payload)                                                                                                   │
                             │   207 │   │   │   │   # except TypeError or JSONDecodeError how?                                                                                                 │
                             │                                                                                                                                                                  │
                             │ /Users/guangyaliu/ycliu/lib/python3.10/site-packages/starlette/websockets.py:133 in receive_json                                                                 │
                             │                                                                                                                                                                  │
                             │   130 │   │   │   │   'WebSocket is not connected. Need to call "accept" first.'                                                                                 │
                             │   131 │   │   │   )                                                                                                                                              │
                             │   132 │   │   message = await self.receive()                                                                                                                     │
                             │ ❱ 133 │   │   self._raise_on_disconnect(message)                                                                                                                 │
                             │   134 │   │                                                                                                                                                      │
                             │   135 │   │   if mode == "text":                                                                                                                                 │
                             │   136 │   │   │   text = message["text"]                                                                                                                         │
                             │                                                                                                                                                                  │
                             │ /Users/guangyaliu/ycliu/lib/python3.10/site-packages/starlette/websockets.py:105 in _raise_on_disconnect                                                         │
                             │                                                                                                                                                                  │
                             │   102 │                                                                                                                                                          │
                             │   103 │   def _raise_on_disconnect(self, message: Message) -> None:                                                                                              │
                             │   104 │   │   if message["type"] == "websocket.disconnect":                                                                                                      │
                             │ ❱ 105 │   │   │   raise WebSocketDisconnect(message["code"])                                                                                                     │
                             │   106 │                                                                                                                                                          │
                             │   107 │   async def receive_text(self) -> str:                                                                                                                   │
                             │   108 │   │   if self.application_state != WebSocketState.CONNECTED:                                                                                             │
                             ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                             WebSocketDisconnect: 1005
```

**Comment by liushuaikobe** [comment]
@gyliu513  Did you solve this problem? I am encountering the same issue.

**Comment by prathigajd** [comment]
@liushuaikobe @gyliu513 Did you guys able to solve ? Am getting the same problem

**Comment by ezpzzz** [comment]
Same problem here as well

**Comment by prathigajd** [comment]
@ezpzzz let me know if you find the solution

**Comment by ezpzzz** [comment]
> @ezpzzz let me know if you find the solution

I was able to get it to work by installing Langfuse v1.8.0

**Comment by prathigajd** [comment]
@ezpzzz I did the same. But still am facing issue. Which langchain-community and langchain version you have ?

**Comment by fabiancaicedo9019** [comment]
I have the same problem, I don't know why or if it is because the Ollama takes a while to respond and the problem occurs.
Has anyone found a solution?
`   
                             starlette.websockets.WebSocketDiscon               
                             nect: (1006, None)                                 
                                                                                
                             ╭─ Traceback (most recent call las─╮               
                             │ /usr/local/lib/python3.10/site-p │               
                             │ ackages/langflow/services/chat/s │               
                             │ ervice.py:199 in                 │               
                             │ handle_websocket                 │               
                             │                                  │               
                             │   196 │   │   │   await websocke │               
                             │   197 │   │   │                  │               
                             │   198 │   │   │   while True:    │               
                             │ ❱ 199 │   │   │   │   json_paylo │               
                             │   200 │   │   │   │   if isinsta │               
                             │   201 │   │   │   │   │   payloa │               
                             │   202 │   │   │   │   elif isins │               
                             │                                  │               
                             │ /usr/local/lib/python3.10/site-p │               
                             │ ackages/starlette/websockets.py: │               
                             │ 139 in receive_json              │               
                             │                                  │               
                             │   136 │   │   │   │   'WebSocket │               
                             │   137 │   │   │   )              │               
                             │   138 │   │   message = await se │               
                             │ ❱ 139 │   │   self._raise_on_dis │               
                             │   140 │   │                      │               
                             │   141 │   │   if mode == "text": │               
                             │   142 │   │   │   text = message │               
                             │                                  │               
                             │ /usr/local/lib/python3.10/site-p │               
                             │ ackages/starlette/websockets.py: │               
                             │ 111 in _raise_on_disconnect      │               
                             │                                  │               
                             │   108 │                          │               
                             │   109 │   def _raise_on_disconne │               
                             │   110 │   │   if message["type"] │               
                             │ ❱ 111 │   │   │   raise WebSocke │               
                             │   112 │                          │               
                             │   113 │   async def receive_text │               
                             │   114 │   │   if self.applicatio │               
                             ╰──────────────────────────────────╯               
                             WebSocketDisconnect: (1006, None)                  
[2024-04-12 16:43:59 +0000] [15] [INFO] connection closed
[2024-04-12 16:43:59 +0000] [15] [INFO] ('X.X.X.X', 8720) - "WebSocket /api/v1/chat/X-X-X-X-X?token=XXXXXX" [accepted]`

**Comment by ansitun** [comment]
I have a similar issue:

 ╭────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮               
                             │ /Users/ansurajkhadanga/projects/mongo-rag/lib/python3.10/site-packages/langflow/services/chat/service.py:199   │               
                             │ in handle_websocket                                                                                            │               
                             │                                                                                                                │               
                             │   196 │   │   │   await websocket.send_json(chat_history)                                                      │               
                             │   197 │   │   │                                                                                                │               
                             │   198 │   │   │   while True:                                                                                  │               
                             │ ❱ 199 │   │   │   │   json_payload = await websocket.receive_json()                                            │               
                             │   200 │   │   │   │   if isinstance(json_payload, str):                                                        │               
                             │   201 │   │   │   │   │   payload = orjson.loads(json_payload)                                                 │               
                             │   202 │   │   │   │   elif isinstance(json_payload, dict):                                                     │               
                             │                                                                                                                │               
                             │ /Users/ansurajkhadanga/projects/mongo-rag/lib/python3.10/site-packages/starlette/websockets.py:139 in          │               
                             │ receive_json                                                                                                   │               
                             │                                                                                                                │               
                             │   136 │   │   │   │   'WebSocket is not connected. Need to call "accept" first.'                               │               
                             │   137 │   │   │   )                                                                                            │               
                             │   138 │   │   message = await self.receive()                                                                   │               
                             │ ❱ 139 │   │   self._raise_on_disconnect(message)                                                               │               
                             │   140 │   │                                                                                                    │               
                             │   141 │   │   if mode == "text":                                                                               │               
                             │   142 │   │   │   text = message["text"]                                                                       │               
                             │                                                                                                                │               
                             │ /Users/ansurajkhadanga/projects/mongo-rag/lib/python3.10/site-packages/starlette/websockets.py:111 in          │               
                             │ _raise_on_disconnect                                                                                           │               
                             │                                                                                                                │               
                             │   108 │                                                                                                        │               
                             │   109 │   def _raise_on_disconnect(self, message: Message) -> None:                                            │               
                             │   110 │   │   if message["type"] == "websocket.disconnect":                                                    │               
                             │ ❱ 111 │   │   │   raise WebSocketDisconnect(message["code"], message.get("reason"))                            │               
                             │   112 │                                                                                                        │               
                             │   113 │   async def receive_text(self) -> str:                                                                 │               
                             │   114 │   │   if self.application_state != WebSocketState.CONNECTED:                                           │               
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯               
                             WebSocketDisconnect: (1005, None)
